### ISSUE TITLE
Update the lsp4j to match the latest version of the Language Server Protocol

### ISSUE THREAD

**Issue by othomann** [eclipse/lsp4j#1]
Hi,

In order to use your implementation to provide the lsp communication layer for the jdtls project, we would need the support of the latest version of the protocol. Changes have been made recently especially in the completionItem to be able to return additional text edits and a command.
See protocol.md around line 1015:

	/**
	 * An optional array of additional text edits that are applied when
	 * selecting this completion. Edits must not overlap with the main edit
	 * nor with themselves.
	 */
	additionalTextEdits?: TextEdit[];
	/**
	 * An optional command that is executed *after* inserting this completion. *Note* that
	 * additional modifications to the current document should be described with the
	 * additionalTextEdits-property.
	 */
	command?: Command;

Having the latest changes of the Language Server Protocol is important to us. So in order to be able to consume your deliverables, we need support of the latest LSP changes.

**Comment by svenefftinge** [comment]
Of course it is important keep LSP4J in sync with the original LSP. 
We plan to use the json schema as the source for code generation once it is merged and complete. See https://github.com/Microsoft/language-server-protocol/pull/40.
Until then we need to track and compare as you did. Thanks!
