### ISSUE TITLE
Use generated Java as source.

### ISSUE THREAD

**Issue by tsmaeder** [eclipse/lsp4j#103]
When I use lsp4j in Eclipse, I get the xtext source attached as the source for lsp4j classes. However, this doesn't help me at all when debugging through the code. Stuff like equals, hashCode, getters/setters are simply not visible.
I would much prefer to have the generated Java source as the mvn source artifact.

**Comment by akosyakov** [comment]
Generated Java code is already part of the maven source artifact:
- during debugging you should be able to switch to Java with the context menu of the current frame
- in the editor, you should be able to switch to sources with the context menu too

**Comment by tsmaeder** [comment]
> in the editor, you should be able to switch to sources with the context menu too
I don't see that. Right-click in the editor, and then?

**Comment by kittaakos** [comment]
@tsmaeder, reference details below. I hope this helps.

 - Opening the generated source:
<img width="606" alt="gh_103_a" src="https://user-images.githubusercontent.com/1405703/27542968-1b0ef80c-5a89-11e7-988a-ea20510b34f4.png">


 - Switching between the sources when debugging:
<img width="489" alt="gh_103_b" src="https://user-images.githubusercontent.com/1405703/27542996-3210bed2-5a89-11e7-92d1-80871a98aca5.png">


 - Debug the generated source:
<img width="360" alt="gh_103_c" src="https://user-images.githubusercontent.com/1405703/27543018-433d3f64-5a89-11e7-81e2-0ab30b96018d.png">

**Comment by tsmaeder** [comment]
Not showing for me. Do I need to install some extra tooling?

**Comment by kittaakos** [comment]
You can get and install the `Xtend IDE` feature into your Eclipse from [here]. It might happen that you have to pull the `Xtext Complete SDK` feature too. Also, there might be more up to date p2 sites available somewhere. This is what I use now. If you need further assistance, feel free to ask. Cheers.

[here]: http://download.eclipse.org/modeling/tmf/xtext/updates/milestones/head/S201704271113/

**Comment by kittaakos** [comment]
@tsmaeder, did you manage to solve your problem? Does the debugging works for you after installing the Xtend IDE feature?

**Comment by tsmaeder** [comment]
Sorry, but I won't install the xtend ide just to use lsp4j. I don't really see the use of including the xtext source for anybody outside of the lsp4j project.

**Comment by svenefftinge** [comment]
You don't need to install xtend, to have the `show source` entry during debug, as it is a JDT feature. I agree that we should probably disable the bytecode enhancement and just use the generated java source always, as we are talking about very readable code here (just the data objects)

**Comment by svenefftinge** [comment]
Seems like we don't use JSR-45 but install the xtend source as primary source code in the bytecode : https://github.com/eclipse/lsp4j/blob/master/gradle/xtend-compiler-settings.gradle#L13
We need to change that setting.

**Comment by tsmaeder** [comment]
@svenefftinge I appreciate you looking into it, but I still have to politely disagree with you generally: I still think that the maven source artifact should contain the generated java source, not xtext. The problem I have is that I cannot use the regular JDT tools with lsp4j. Stuff like quick outline do not work on the xtext source attached to the lsp4j maven artifacts.

**Comment by spoenemann** [comment]
@tsmaeder Could you try if your experience is better with the current snapshot?

**Comment by tsmaeder** [comment]
Works fine for me, thx.
