### ISSUE TITLE
Implements equals on Message classes

### ISSUE THREAD

**Issue by JiahuiJiang** [eclipse/lsp4j#104]
Right now it's very hard to write unit tests because ``message`` classes don't implement an ``equals`` method

**Comment by spoenemann** [comment]
We usually write unit tests by comparing the string output, see e.g. [JsonParseTest](https://github.com/eclipse/lsp4j/blob/master/org.eclipse.lsp4j/src/test/java/org/eclipse/lsp4j/test/services/JsonParseTest.xtend)
