### ISSUE TITLE
`equals` seems broken for RemoteEndpoint

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lsp4j#106]
Here is a piece of code
```java
Collection<LanguageServer> file2LanguageServers = LanguageServiceAccessor.getLanguageServers(testFile2, c -> Boolean.TRUE); // 
LanguageServer ls = file2LanguageServers.iterator().next();
assertTrue(file2LanguageServers.contains(ls)); // FAILS, so I investigated with next lines
assertSame(ls, ls); // ok
assertEquals(ls, ls); // FAILS
```
`ls` is an instance of `org.eclipse.lsp4j.jsonrpc.RemoteEndpoint`.
`hashCode()` seems to be properly working as I can add the same `ls` multiple time in an `HashSet` without the set being modified. I imagine this is because the `HashSet` also checks for identity equality `==` before trying `equals()` so it's not facing the bug in `equals()`.
This is org.eclipse.lsp4j.jsonrpc_0.2.0.v20170518-0647.jar

**Comment by tsmaeder** [comment]
At least in master, RemoteEndpoint does not even implement equals(). I think you're barking up the wrong tree.

**Comment by mickaelistria** [comment]
@tsmaeder you're right, it's actually a Proxy ( `com.sun.proxy.$Proxy27` ) that suffers from this issue.

**Comment by spoenemann** [comment]
We're using `java.lang.reflect.Proxy` to create endpoint instances. I fear we cannot change anything on how they behave regarding `equals`.

**Comment by cdietrich** [comment]
handling the equals and hashCode in the invocationhandler is no option?

**Comment by spoenemann** [comment]
Thanks for the hint, @cdietrich
