### ISSUE TITLE
Documentation: class path is incorrect in Getting Started

### ISSUE THREAD

**Issue by nturley** [eclipse/lsp4j#111]
lsp4j/documentation/README.md

says

> The first thing you should do is to implement your language server. To do so just implement the interface org.eclipse.lsp4j.LanguageServer.
>
>If you are implementing a client (e.g. an editor) you simply need to implement org.eclipse.lsp4j.LanguageClient instead.

I think that's out of date. Both of those classes are at org.eclipse.lsp4j.services

**Comment by spoenemann** [comment]
Thanks for the hint!
