### ISSUE TITLE
Difficulty to debug language server

### ISSUE THREAD

**Issue by ainslec** [eclipse/lsp4j#113]
I'm having a problem debugging a language server (non-xtext language server). I am using VSCode as a client currently.

I have basic hovers, autocompletes and validations working in my language server, but I have some bugs in my server code that I would like to step debug. It is this part that is proving a challenge. I am in a situation where I cannot debug at all.

I am utilising stdin and stdout.

If I enable remote debugging on the jvm process via "-Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=9999", then the problem is that the JVM emits this on stdout : "Listening for transport dt_socket at address: 9999", which then breaks the protocol.

So, I guess the question is, is there a way to enable remote debugging when using lsp4j + stdout/stdin, and if not, if it has to be custom ports, could this approach be documented somewhere with regards to the vscode bootstrap + lsp4j bootstrap?

**Comment by cdietrich** [comment]
Hi, do you know the magic `quiet=y` option for debugging e.g. `-Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8000,suspend=n,quiet=y`

**Comment by ainslec** [comment]
Works PERFECTLY. Thank you.
