### ISSUE TITLE
0.3.0 release plan?

### ISSUE THREAD

**Issue by jonahkichwacoders** [eclipse/lsp4j#114]
Hello LSP4J devs,

Do you have a future release plan for LSP4J? At the moment the project
page doesn't state your intentions AFAICT[1].

I ask because LSP4E is currently depending on LSP4J 0.2.0 and I would
like to know if LSP4E can depend on LSP4J master[2]. LSP4E intends to
release with Oxygen.1[3].

Thanks,
Jonah

PS I posted this on the mailing list, then realised that no one has ever sent an email on that list, so perhaps it is not in use[4]?

[1] https://projects.eclipse.org/projects/technology.lsp4j
[2] https://dev.eclipse.org/mhonarc/lists/lsp4e-dev/msg00102.html
[3] https://projects.eclipse.org/projects/technology.lsp4e
[4] https://dev.eclipse.org/mhonarc/lists/lsp4j-dev/msg00001.html

**Comment by svenefftinge** [comment]
I have added a release for the same date as lsp4e : https://projects.eclipse.org/projects/technology.lsp4j/reviews/0.3.0-release-review

**Comment by mickaelistria** [comment]
Do you plan to build the release candidate for 0.3.0 in advance? I'd like to produce the RC of LSP4E 0.3.0 as soon as possible, using a stable build of LSP4J 0.3.0.

**Comment by spoenemann** [comment]
@mickaelistria yes, we can do 0.3.0.RC1 soon.

**Comment by mickaelistria** [comment]
@spoenemann cool. Can you please put a comment on this issue whenever there's a RC so I'll cascade the LSP4E build?

**Comment by spoenemann** [comment]
Milestone 0.3.0.RC1 is done. It is not yet available on http://download.eclipse.org/lsp4j/updates/milestones/ because the person who usually uploads the stuff there is on vacation, but until then you can use this URL:

https://hudson.eclipse.org/lsp4j/job/lsp4j-release/10/artifact/build-result/p2.repository/
