### ISSUE TITLE
Add Jackson annotations

### ISSUE THREAD

**Issue by gatesn** [eclipse/lsp4j#115]
Would you be against modifying the code generator to add jackson annotations? This wouldn't break GSON compatibility, and we could move to Jackson fully later if desired.

I'm happy to look into doing so but wanted to know if it's something that would be flat out rejected before I put the work in!

**Comment by akosyakov** [comment]
@gatesn What is the motivation?

**Comment by gatesn** [comment]
First benefit is that we use Jackson everywhere else in our stack, so providing support for it makes things simpler for us (and doesn't break any existing clients of this library).

Second benefit, is that types know how to deserialise themselves. This means you don't need to know which interfaces your language server / client supports in order to construct the MessageJsonHandler object. Instead, any Jackson OBJECT_MAPPER can be used and it will support the entire protocol plus any extensions.

**Comment by spoenemann** [comment]
Could you provide web links to the annotations you are referring to, and to the Maven module they're contained in?

**Comment by gatesn** [comment]
Having dug into it a bit. The issue with Jackson is that the Message object would still need to know how to decode the parameters based on the method name. So there would need to exist something akin to the existing GSON Type Adapter regardless. Closing this out.
