### ISSUE TITLE
Support for proposed color provider.

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lsp4j#118]
VSCode  provides color provider for CSS and JSON that I have started to implement in bluesky with my PR https://github.com/mickaelistria/eclipse-bluesky/pull/43

VSCode has defined in their proposed https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.proposed.d.ts this color provider feature:

```

/**
	 * The document color provider defines the contract between extensions and feature of
	 * picking and modifying colors in the editor.
	 */
	export interface DocumentColorProvider {
		/**
		 * Provide colors for the given document.
		 *
		 * @param document The document in which the command was invoked.
		 * @param token A cancellation token.
		 * @return An array of [color ranges](#ColorRange) or a thenable that resolves to such. The lack of a result
		 * can be signaled by returning `undefined`, `null`, or an empty array.
		 */
		provideDocumentColors(document: TextDocument, token: CancellationToken): ProviderResult<ColorRange[]>;
	}

```

It should be cool if lsp4j could support this feature too. For the moment I use lsp4j Range and my own structure and I cannot test colorProvider capabilities (see https://github.com/mickaelistria/eclipse-bluesky/pull/43/files#diff-e43b97ca17c7165ca88ef3cc690c9fecR61).

**Comment by akosyakov** [comment]
There is now a node package containing the LSP definitions for typescript: https://github.com/Microsoft/vscode-languageserver-node/tree/9d6b53e0feb4039af95e2d108c376d8fc92d8b37/protocol

It contains the LSP as well as proposed extensions to it to support in VS code. We could add java interfaces for proposed extensions as well. E.g. for coloring: https://github.com/Microsoft/vscode-languageserver-node/blob/9d6b53e0feb4039af95e2d108c376d8fc92d8b37/protocol/src/protocol.colorProvider.proposed.ts

**Comment by akosyakov** [comment]
PRs are welcomed.

An interface extending `LanguageServer` providing `textDocument/documentColor` request according to https://github.com/Microsoft/vscode-languageserver-node/blob/9d6b53e0feb4039af95e2d108c376d8fc92d8b37/protocol/src/protocol.colorProvider.proposed.ts should be put under https://github.com/eclipse/lsp4j/tree/master/org.eclipse.lsp4j/src/main/java/org/eclipse/lsp4j/services/proposed/colorProvider

@angelozerr Could you look into it?

**Comment by angelozerr** [comment]
@akosyakov my problem is that I don't know xtend that you seems using. I don't know which files I must update?

**Comment by mniewrzal** [comment]
@angelozerr I will try to prepare PR for this.

**Comment by angelozerr** [comment]
> @angelozerr I will try to prepare PR for this.

Thanks a lot! So I think we could provide color support directly in lsp4e once you will support that.

**Comment by spoenemann** [comment]
@akosyakov how does this relate to the already existing [LanguageClientExtensions](https://github.com/eclipse/lsp4j/blob/master/org.eclipse.lsp4j/src/main/java/org/eclipse/lsp4j/services/LanguageClientExtensions.java)?

**Comment by akosyakov** [comment]
@spoenemann I think it is unrelated to this issue. It was our proposals for coloring that does not seem to be accepted. We will need eventually deprecate it or propose properly according to https://github.com/Microsoft/language-server-protocol/issues/293

**Comment by angelozerr** [comment]
Is there any news about this issue? I have seen that you have added `ColorProviderCapabilities` but I don't understand how to consume color? Any help are welcome!

**Comment by angelozerr** [comment]
Please note ‘textDocument/documentColor’ is well specified at https://microsoft.github.io/language-server-protocol/specification#document-color-request-leftwards_arrow_with_hook

IMHO, I think lsp4j should clean the color structure (like removing ColoringInformation, ColorStyle and have ColorInformation and Color structure):

```
Request:

method: ‘textDocument/documentColor’
params: DocumentColorParams defined as follows
interface DocumentColorParams {
	/**
	 * The text document.
	 */
	textDocument: TextDocumentIdentifier;
}
Response:

result: ColorInformation[] defined as follows:

interface ColorInformation {
	/**
	 * The range in the document where this color appers.
	 */
	range: Range;

	/**
	 * The actual color value for this color range.
	 */
	color: Color;
}

/**
 * Represents a color in RGBA space.
 */
interface Color {

	/**
	 * The red component of this color in the range [0-1].
	 */
	readonly red: number;

	/**
	 * The green component of this color in the range [0-1].
	 */
	readonly green: number;

	/**
	 * The blue component of this color in the range [0-1].
	 */
	readonly blue: number;

	/**
	 * The alpha component of this color in the range [0-1].
	 */
	readonly alpha: number;
} 
```

defines too ColorPresentation:

```
interface ColorPresentationParams {
	/**
	 * The text document.
	 */
	textDocument: TextDocumentIdentifier;

	/**
	 * The color information to request presentations for.
	 */
	colorInfo: Color;

	/**
	 * The range where the color would be inserted. Serves as a context.
	 */
	range: Range;
}
Response:

result: ColorPresentation[] defined as follows:
interface ColorPresentation {
	/**
	 * The label of this color presentation. It will be shown on the color
	 * picker header. By default this is also the text that is inserted when selecting
	 * this color presentation.
	 */
	label: string;
	/**
	 * An [edit](#TextEdit) which is applied to a document when selecting
	 * this presentation for the color.  When `falsy` the [label](#ColorPresentation.label)
	 * is used.
	 */
	textEdit?: TextEdit;
	/**
	 * An optional array of additional [text edits](#TextEdit) that are applied when
	 * selecting this color presentation. Edits must not overlap with the main [edit](#ColorPresentation.textEdit) nor with themselves.
	 */
	additionalTextEdits?: TextEdit[];
}
```

TextDocumentService should perhaps updated to support color provider (like codelens, completion, etc). I don't know if it's a good API like this:

```
public interface TextDocumentService {
.....
        @JsonRequest("textDocument/documentColor")
	CompletableFuture<List<ColorInformation>> documentColors(DocumentColorParams  params);

	@JsonRequest("textDocument/colorPresentation")
	CompletableFuture<List<ColorPresentationParams>> colorPresentations(ColorPresentationParams params);
```

**Comment by spoenemann** [comment]
The color provider has become part of the specification with version 3.6 (see #167). We will include that in LSP4J version 0.4.0.

We should deprecate our old coloring code in https://github.com/eclipse/lsp4j/blob/master/org.eclipse.lsp4j/src/main/java/org/eclipse/lsp4j/ProtocolExtensions.xtend. @svenefftinge what do you think?

**Comment by akosyakov** [comment]
@spoenemann The color provider in the LSP is for color picking: https://code.visualstudio.com/docs/extensionAPI/language-support#_show-color-decorators Our proposal is for semantic coloring. Confusing naming.

**Comment by spoenemann** [comment]
Yes, I realized that in the meantime. Do we still use those classes anywhere? In any case we should clearly mark them as non-standard.

**Comment by svenefftinge** [comment]
Yes, we use them. Moreover, we might soon be able to revise that work and the corresponding PR to get  semantic-coloring into the LSP.

**Comment by spoenemann** [comment]
I added the `@Beta` annotation to those classes in #179.
