### ISSUE TITLE
Server is not versatile

### ISSUE THREAD

**Issue by gorkem** [eclipse/lsp4j#12]
The server stops to responds if one of the endpoints for a request unexpectedly throws an exception. You can easily see this by throwing a NPE from one of the `@JsonRequest` annotated functions. When the exception is received it causes the server to exit the listen loop and server no longer responds to requests. 

Ideally server should be able to respond to further requests even after one of the requests fails unexpectedly.

**Comment by svenefftinge** [comment]
I changed the code such that RuntimeExceptions are caught and logged for notification and response message handling. For request messages a RuntimeException is returned as an exceptional Future.

**Comment by gorkem** [comment]
Is this change deployed to maven repo? My builds do not seem to pick it.

**Comment by svenefftinge** [comment]
It is only deployed once a day (at 3am UTC) if not triggered manually (which i forgot to do, sorry).
But it is published now.
