### ISSUE TITLE
Confusion around cancel notifictions

### ISSUE THREAD

**Issue by JanKoehnlein** [eclipse/lsp4j#122]
I am a bit confused about cancel notifications.
According to the LSP definition, it's

```
export namespace ErrorCodes {
	// Defined by JSON RPC
	...
	// Defined by the protocol.
	export const RequestCancelled: number = -32800;
}
```

In lsp4j:
* it is called `ResponseErrorCodes` instead of just `ErrorCodes`
* the literal `RequestCancelled` is only defined in `org.eclipse.lsp4j.jsonrpc.messages.ResponseErrorCodes` but not in `org.eclipse.lsp4j.ResponseErrorCode` which looks the wrong way around.

Could somebody please clarify?

**Comment by spoenemann** [comment]
I marked `org.eclipse.lsp4j.ResponseErrorCode` as deprecated. It'n not used anywhere, anyway. Anything else to clarify?
