### ISSUE TITLE
Exception at launch

### ISSUE THREAD

**Issue by gabro** [eclipse/lsp4j#127]
Hi, I've tried extending `LanguageServer` and I get this exception when I launch it:

```
Exception in thread "main" java.lang.IllegalStateException: Duplicate RPC method initialized.
```

Any hint of what I may be doing wrong?

**Comment by gabro** [comment]
Ok, apparently if I provide a dummy implementation of `initialized` the problem goes away.
I have another runtime check failing, but that looks unrelated.

**Comment by gabro** [comment]
I minimized the bug here, and it happens only when using lsp4j from Scala :(

https://github.com/gabro/lsp4j-initialize-bug

**Comment by gabro** [comment]
Argh, ok, it's confirmed. If I switch back to Scala 2.11 the bug disappears, so it must be due to some weird interplay of trait <-> interface encoding (which changed in Scala 2.12) with the runtime reflection

**Comment by ShaneDelmore** [comment]
For anyone else that runs into this you can workaround the issue by setting the scalac flat -Xmixin-force-forwarders to either "junit" or "false".  It defaults to true which will reproduce this issue.  
For example, add the following in build.sbt:

```
scalacOptions += "-Xmixin-force-forwarders:false"
```
