### ISSUE TITLE
Support Debug Server Protocol

### ISSUE THREAD

**Issue by jonahkichwacoders** [eclipse/lsp4j#130]
The Debug Server Protocol, originating in VS code, provides a generic debug protocol with numerous "adapters" to connect VS code to different debuggers (such as Chrome debugger, gdb, etc.).

To support the Debug Server Protocol in Eclipse and Che, or to be able to write an adapter in Java, it will be useful to have a common library. This issue is to track extending the lsp4j library to support the debug protocol.

The protocol itself is defined at https://github.com/Microsoft/vscode-debugadapter-node/blob/master/debugProtocol.json

**Comment by jonahkichwacoders** [comment]
PR #131 created.

**Comment by mickaelistria** [comment]
Just out of curiosity: how easier it would have been to implement it if the debug protocol were using JSON-RCP? I'm asking this to evaluate whether it would still be interesting to influence the debug protocol in adopting JSON-RCP or to write a some JSON-RCP proxy for this Debug Server Protocol.

**Comment by jonahkichwacoders** [comment]
It would certainly be easier. How much is harder to say, certainly days of work. I initially attacked everything in parallel, from the low level implementation of the protocol to the very complicated (but complete and extensible Eclipse Platform Debug)  to the simpler debug layer in Eclipse Che.

However, if I did not have lsp4j.jsonrpc to build on top of, it would have been even more work. Fortunately the two protocols are not that dissimilar, and now the work is done.

**Comment by jonahkichwacoders** [comment]
This PR is a dependency of the Eclipse implementation (DSP4E, part of the LSP4E project) see: https://bugs.eclipse.org/bugs/show_bug.cgi?id=508470

**Comment by jonahkichwacoders** [comment]
This has been merged now. There is more than likely going to be refinements, but they will best be handled in new bug reports (like #139)

**Comment by mickaelistria** [comment]
Awesome!
