### ISSUE TITLE
Support workspaceFolders proposal

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lsp4j#132]
https://github.com/Microsoft/language-server-protocol/issues/298#issuecomment-336700314 covers a discussion about allowing multi root/projects in language servers. This is not finalized in the protocol specification yet, but the vscode client api already covers it. This seems to be an important step forward and a major change, so it would be nice to start investigating support for it soon.

See https://bugs.eclipse.org/bugs/show_bug.cgi?id=526489 (PS: you should ask webmaster to remove bugzilla component if you're not using it).

**Comment by martinlippert** [comment]
Is there a way to get the related pull request accepted and a snapshot build that includes this up somewhere? I am eagerly waiting for this to make our language servers ready for the latest VSCode 1.18 release (which released support for multi-root workspaces).

**Comment by mickaelistria** [comment]
FYI, I've prepared a patch in LSP4E which takes advantage of this change in LSP4J to implement multi-root support, and it seems to work with JDT-LS https://git.eclipse.org/r/#/c/111750/
That doesn't validate everything though as JDT-LS ignores the "static" capabilities and mostly go through the registerCapability approach; but the operations to change workspaceFolder seem to work as expected between LSP4E and JDT-LS, using LSP4J as API on client side.

**Comment by svenefftinge** [comment]
closing since https://github.com/eclipse/lsp4j/pull/133 is merged
