### ISSUE TITLE
URI mapping in a remote scenario

### ISSUE THREAD

**Issue by sjka** [eclipse/lsp4j#134]
Imagine a client (like e.g. VSCode) running on one computer and the language server running embedded within another process on a server (e.g. Eclipse SmartHome)[1]. They both of course have to "see" the same files, therefore the client accesses them via e.g. a samba share or similar:

```text
/----------\   lsp via TCP          /----------\
|  Client  |  ------------------>   |  Server  |
| (VSCode) |  ------------------>   |   (ESH)  |
\----------/   files via SMB        \----------/
```

This leads to the funny situation that although they see the identical files, their URIs look fundamentally different on both ends. Which makes it fail in all kinds of miserable ways, of course.

So now I'm wondering if there already is an obvious way of tweaking the language server in order to do map the URIs correctly which I didn't spot so far...? 

However, as this setup is a rather not-so-common use-case I rather fear this is not yet supported at all. Would you consider integrating something like this? Or do you at least have an advice how to workaround it? Implementing an own RemoteEndpoint and reflectively replacing every string inside messages which looks like the old path with the new one seems technically doable but obviously not viable. Any proper (or at least better) solution is highly appreciated!

[1]: The DSL needs to have access to some live dynamic objects in order to fully resolve all variables etc., therefore this process cannot simply run on the client side.

**Comment by cdietrich** [comment]
@sjka the uris are mapped inside the xtext language server when incoming (see UriExtensions) as well locally (see JavaIoFileSystemScanner).
so if you do some mapping on one of these sides you should be fine.

please note there is https://github.com/eclipse/xtext-core/issues/528 which says the uri conversion is a bit buggy anyway.

and you might need a uri mapping on the outbound way as well

**Comment by sjka** [comment]
Wow, that was quick (once again)! 
Thanks, it looks like this was the missing hint. I will have a go at that...

**Comment by cdietrich** [comment]
for the outbound mapping see org.eclipse.xtext.ide.server.UriExtensions.toUriString(URI)

**Comment by sjka** [comment]
Awesome, having some fun with my own UriExtensions indeed did the trick. Thanks again!
