### ISSUE TITLE
Guidance on runtime-extension of protocol

### ISSUE THREAD

**Issue by tsmaeder** [eclipse/lsp4j#143]
In Eclipse Che, we're extending jdt.ls with our own custom commands, so far, so good. However, we would also like to send custom notification (classpath changed, etc.). 
For that, we'd like to make a remote endpoint, that we can extend at runtime (via an Eclipse extension point). My first Idea is to extend remote endpoint with the ability to add handlers and to copy Launcher.createIOLauncher to return an extensible endpoint. Do you think that would be a feasible approach?

**Comment by spoenemann** [comment]
Just call `notify()` on RemoteEndpoint. The RemoteEndpoint is currently not exposed by `Launcher.createIoLauncher()`. @svenefftinge do you think we should extend the Launcher interface to also expose the RemoteEndpoint?

@tsmaeder for now you could just copy the ~20 lines of code from `createIoLauncher()` in order to get both the remote proxy and the underlying RemoteEndpoint.

**Comment by svenefftinge** [comment]
Yes, we could do that

**Comment by tsmaeder** [comment]
Thx folks, I'll go with @spoenemann's suggestion.

**Comment by tsmaeder** [comment]
I really think the most elegant way to solve this would be to allow for multiple interfaces to be handled in the EndpointProxy class and to allow multiple local object in GenericEndpoint.
Launcher.createIOLauncher would then look like this:
```
static <T> Launcher<T> createIoLauncher(Object[] localServices, Class<T>[] remoteInterfaces, ...
```
I could build these things myself, but I'd have to copy AnnotationUtil because MethodInfo is package private. Also, the case of a single service object or remote interface is really just a special case.

**Comment by spoenemann** [comment]
You can combine multiple interfaces by creating a subinterface. And you can combine multiple local services using the `@JsonDelegate` annotation as it is done for [LanguageServer](https://github.com/eclipse/lsp4j/blob/master/org.eclipse.lsp4j/src/main/java/org/eclipse/lsp4j/services/LanguageServer.java).

**Comment by tsmaeder** [comment]
@spoenemann but only when you know the extensions at compile time. jdl.ls allows extension of the language server via eclipse plugins. So subinterfaces & @JsonDelegate are not an option.

**Comment by spoenemann** [comment]
From the [Proxy](https://docs.oracle.com/javase/8/docs/api/java/lang/reflect/Proxy.html#getProxyClass-java.lang.ClassLoader-java.lang.Class...-) documentation:

> All of the interface types must be visible by name through the specified class loader. In other words, for class loader cl and every interface i, the following expression must be true:
> `Class.forName(i.getName(), false, cl) == i`

With a flat classpath that's not a problem. In an OSGi context, however, it means you have to provide a "merged" ClassLoader that delegates to the ClassLoaders of all involved interfaces.

@tsmaeder is that doable for your use case?

**Comment by tsmaeder** [comment]
@spoenemann hmh...that is a very good question to which I have no ready answer.
