### ISSUE TITLE
Support for snippetSyntax

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lsp4j#149]
Protocol defines the snippetSyntax formally at https://github.com/Microsoft/language-server-protocol/blob/master/snippetSyntax.md . LSP4J should probably include support for it by defining the symbols and providing operations to process the string replacement as defined, that clients could use in their code instead of reimplementing them.

**Comment by KamasamaK** [comment]
VS Code chose to make `SnippetString` a separate type with the following definition to facilitate building a snippet.

```typescript
/**
 * A snippet string is a template which allows to insert text
 * and to control the editor cursor when insertion happens.
 *
 * A snippet can define tab stops and placeholders with `$1`, `$2`
 * and `${3:foo}`. `$0` defines the final tab stop, it defaults to
 * the end of the snippet. Variables are defined with `$name` and
 * `${name:default value}`. The full snippet syntax is documented
 * [here](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_creating-your-own-snippets).
 */
export class SnippetString {

	/**
	 * The snippet string.
	 */
	value: string;

	constructor(value?: string);

	/**
	 * Builder-function that appends the given string to
	 * the [`value`](#SnippetString.value) of this snippet string.
	 *
	 * @param string A value to append 'as given'. The string will be escaped.
	 * @return This snippet string.
	 */
	appendText(string: string): SnippetString;

	/**
	 * Builder-function that appends a tabstop (`$1`, `$2` etc) to
	 * the [`value`](#SnippetString.value) of this snippet string.
	 *
	 * @param number The number of this tabstop, defaults to an auto-increment
	 * value starting at 1.
	 * @return This snippet string.
	 */
	appendTabstop(number?: number): SnippetString;

	/**
	 * Builder-function that appends a placeholder (`${1:value}`) to
	 * the [`value`](#SnippetString.value) of this snippet string.
	 *
	 * @param value The value of this placeholder - either a string or a function
	 * with which a nested snippet can be created.
	 * @param number The number of this tabstop, defaults to an auto-increment
	 * value starting at 1.
	 * @return This snippet string.
	 */
	appendPlaceholder(value: string | ((snippet: SnippetString) => any), number?: number): SnippetString;

	/**
	 * Builder-function that appends a variable (`${VAR}`) to
	 * the [`value`](#SnippetString.value) of this snippet string.
	 *
	 * @param name The name of the variable - excluding the `$`.
	 * @param defaultValue The default value which is used when the variable name cannot
	 * be resolved - either a string or a function with which a nested snippet can be created.
	 * @return This snippet string.
	 */
	appendVariable(name: string, defaultValue: string | ((snippet: SnippetString) => any)): SnippetString;
}
```

It seems to be missing **Choice**, but a util like this should help.

**Comment by spoenemann** [comment]
AFAICT that code allows to construct snippets, but not to parse them, right? Parsing is certainly the harder part.

For reference:
https://github.com/microsoft/vscode/blob/a7cc79a55439bce5ea2e173b4d46655bdebe79a9/src/vs/workbench/api/common/extHostTypes.ts#L692

**Comment by KamasamaK** [comment]
You're correct, that util would be used by the server, not the client. I forgot that LSP4J is also a client SDK.

**Comment by jonahgraham** [comment]
Is this still an issue? What did LSP4E do in this area? Is there some code that can/should be moved from LSP4E to LSP4J for wider consumption?

**Comment by mickaelistria** [comment]
LSP4E support for template is relatively basic and weak. It's all contained in `LSIncompleteCompletionProposal#apply()`. At the moment, I don't have seen concrete need for improving that, most LS we look at behave fine with the basic support from LSP4E.
So feel free to close if you're willing to, and if we happen to work on it again in LSP4E, we can try to factorize things in a way that can allow moving to LSP4J to facilitate reuse by other Java projects.

**Comment by jonahgraham** [comment]
Thanks @mickaelistria for the info.

**Comment by angelozerr** [comment]
I don't know if LSP4IJ could be interested but I hav eimplemented a Snippet parser at https://github.com/redhat-developer/intellij-quarkus/tree/main/src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/snippet for LSP4IJ which have no dependencies to IJ.

 * here some tests https://github.com/redhat-developer/intellij-quarkus/tree/main/src/test/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/snippet which are independant from IJ
 * here the implementation for IJ https://github.com/redhat-developer/intellij-quarkus/blob/main/src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/completion/SnippetTemplateLoader.java

IMHO I think it will simplify more the LSP4E apply completion code.

**Comment by jonahgraham** [comment]
Thanks @angelozerr, is what @mickaelistria said in https://github.com/eclipse-lsp4j/lsp4j/issues/149#issuecomment-812527023 relevant:

> [...] if we happen to work on it again in LSP4E, we can try to factorize things in a way that can allow moving to LSP4J to facilitate reuse by other Java projects.

Of course if you are willing to contribute to LSP4J that would be great. In the meantime if others are looking for support for snippetSyntax, then hopefully they will see your message.
