### ISSUE TITLE
Use primitive types in debug protocol

### ISSUE THREAD

**Issue by spoenemann** [eclipse/lsp4j#150]
For LSP we are using primitive types for required fields where applicable. This could also be done for the debug protocol. For example,

```
	@NonNull
	Long threadId;
```

could be changed to

```
	long threadId;
```

I'm not sure about the `@NonNull` annotation in that case. We have omitted it for LSP primitive fields, but it could still be useful to enable validation for those fields, so we might change that.

**Comment by KamasamaK** [comment]
@jonahgraham Since we're breaking compatibility anyway with #392, do you think it's a good time to also address this?

**Comment by jonahgraham** [comment]
Yes

**Comment by jonahgraham** [comment]
Fixed merged as part of PR #401
