### ISSUE TITLE
Should the debug protocol be namespaced using JsonSegment?

### ISSUE THREAD

**Issue by gatesn** [eclipse/lsp4j#151]
I notice the debug protocol currently isn't namespaced, meaning it's quite likely to collide with the LSP, or LSP extensions. Would you be opposed to adding `JsonSegment("debug")` ?

**Comment by jonahkichwacoders** [comment]
Hi @gatesn, The debug protocol does not conflict because it is run on a completely independent transport. The debug protocol is a spec defined by MS. See https://github.com/Microsoft/vscode-debugadapter-node/tree/master/protocol

**Comment by gatesn** [comment]
For our use case, which is a Monaco front-end talking to language servers over websockets I was hoping to avoid an extra transport link. I suppose it might be possible to modify RemoteEndpoint so we can fiddle method names during registration.

________________________________

**Comment by jonahkichwacoders** [comment]
A couple of things to keep in mind. The debug protocol at the lowest level is not JSON RPC2.0, but instead something quite similar. So if you are going to talk to existing debug adapters after transporting over the websocket you need to translate that too.

Additionally, there are fundamental differences in the life cycle of a debug adapter and a language server.  Among other things, the debug adapter is stateful. Unlike the language server you can't silently restart a debug adapter.

**Comment by spoenemann** [comment]
@gatesn if you really want to do it, you could try creating a subinterface of IDebugProtocolServer and adding a `@JsonSegment` to it. We can't change the message scheme in general since that would not work with existing clients / servers.

**Comment by gatesn** [comment]
Oh yes, I forgot a sub-interface would work with the method discovery, thanks!

The idea here is that with a small translation layer, VSCode extensions built around language servers could add debug support.

________________________________
