### ISSUE TITLE
Launcher future marked as `done` whenever parsing error happens

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lsp4j#152]
Some LS do sometimes return erroneous values (not conforming to the specification, placing null when null is not allowed and so on). When this happens, it seems like LSP4J stops working, close the streams and so on. It would be nice if such case were properly handled by LSP4J by simply logging the erroneous message and continuing to process new requests/responses/notifications.

**Comment by gatesn** [comment]
I saw this behaviour too, I think the problem is that StreamMessageProducer only catches a couple of exception types. 

Perhaps it should catch more (or all) exceptions, in particular a JsonParseException should be caught and converted to a JsonRPC ParseError (code -32700)

**Comment by spoenemann** [comment]
@mickaelistria, @gatesn: This was harder to get right than I thought initially. Please have a look at my proposed solution in #158 and tell me whether you have any concerns.

**Comment by mickaelistria** [comment]
Sorry I'm a bit late on this one.
I still see that by default, the future seems to completes in cases like https://github.com/OmniSharp/omnisharp-roslyn/issues/1087 . How should I create the Launcher to prevent the error from closing the future? Should I just catch exceptions in the MessageConsumer passed as parameter?

**Comment by spoenemann** [comment]
@mickaelistria I added a test for that in #208, but I cannot reproduce the problem. In the test, the result future of the hover request completes exceptionally as expected, and the launcher is not marked as done. Did I miss something in the test?

**Comment by mickaelistria** [comment]
I tried with latest snapshot and couldn't reproduce the issue.
Not sure whether it's related to the change you made in #208 or I got it failing earlier because of erroneous test scenario on my side... Anyway, it now works for LSP4E with Omnisharp, thanks!
