### ISSUE TITLE
Document where Maven artifacts are available

### ISSUE THREAD

**Issue by PerBothner** [eclipse/lsp4j#153]
It appears that lsp4j is meant to be useful for language servers for many languages on the Java platform.  Furthermore, the whole point of LSP is to separate the language-specific support from the IDE.

Hence I would expect that lsp4j is not specifically tied to Eclipse, and thus lsp4j releases should be easily to download  without having to run Eclipse.  But that appears not to be the case.

**Comment by JanKoehnlein** [comment]
How do you think it's tied to Eclipse?

I don't see any dependencies to Eclipse runtime, you can consume Maven artifacts are from [JCenter](https://bintray.com/bintray/jcenter/org.eclipse.lsp4j%3Aorg.eclipse.lsp4j/0.3.0) and it can be built with Gradle.

**Comment by spoenemann** [comment]
LSP4J is published on two different platforms: [Eclipse update site](http://download.eclipse.org/lsp4j/updates/releases/) and [Maven Central](https://repo.maven.apache.org/maven2/org/eclipse/lsp4j/) / JCenter as mentioned by @JanKoehnlein. The Maven repositories are easily consumable by Java projects that are completely independent of Eclipse, e.g. using Maven or Gradle for dependency management.

**Comment by PerBothner** [comment]
The only links under "releases" or "milestone" on the front page (https://github.com/eclipse/lsp4j) go to a page that says "This URL is an Eclipse software repository; you must use it in Eclipse (see how).".  How is that not tied to Eclipse?

I don't see a link or mention of to the Maven artifacts on the front page.  There is a link to a non-Eclipse repository but only under "Nightly", as well as in the Snapshots section.

**Comment by spoenemann** [comment]
Ok we'll update the README.
