### ISSUE TITLE
Json primitives are leaking to the apps. 

### ISSUE THREAD

**Issue by gorkem** [eclipse/lsp4j#166]
I have attempted to switch jdt.ls to the latest milestone and noticed that lsp4j is leaking Gson primitives to the application. 
For instance `CodeLens#getData()` used to return a `Map` now it returns JsonObject which is breaking jdt.ls. Similarly we  get JsonPrimitives instand of Strings in places which causes expections such as below. 

Can we possibly restore the previous behavior so that applications do not have to deal with JSON APIs?

```
com.google.gson.JsonPrimitive cannot be cast to java.lang.String
	at com.microsoft.java.test.plugin.internal.JUnitTestFetcher.fetchTests(JUnitTestFetcher.java:47)
	at com.microsoft.java.test.plugin.internal.TestDelegateCommandHandler.executeCommand(TestDelegateCommandHandler.java:29)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:142
```

**Comment by spoenemann** [comment]
This was done due to #126. The idea is that it is nicer to work with the Gson tree API instead of a tree of Maps and Lists.

**Comment by gorkem** [comment]
Of course, I should have suspected @tsmaeder :)

**Comment by spoenemann** [comment]
@tsmaeder @gorkem How should we proceed here? Do you prefer reverting #154 or keeping it?

**Comment by gorkem** [comment]
After talking with @tsmaeder, we decided to keep it as it is. Closing.
