### ISSUE TITLE
Adapt to Protocol Level 3.6 

### ISSUE THREAD

**Issue by cdietrich** [eclipse/lsp4j#167]
https://github.com/Microsoft/language-server-protocol/blob/master/protocol-changelog.md

**Comment by jvalkeal** [comment]
Yeah it'd be a good to know plans for this. Noticed this when poking around `vscode-languageserver-node` that `rootUri` in `InitializeParams` is now deprecated. For some reason this deprecation is not reflected to api samples in a spec.

https://github.com/Microsoft/vscode-languageserver-node/blob/583ba3878faa9e550461337afefb1618505a4601/protocol/src/protocol.ts#L796-L803

```
	/**
	 * The rootUri of the workspace. Is null if no
	 * folder is open. If both `rootPath` and `rootUri` are set
	 * `rootUri` wins.
	 *
	 * @deprecated in favour of workspaceFolders.
	 */
	rootUri: string | null;
```

**Comment by spoenemann** [comment]
I scheduled release 0.4.0 for April 25th, which should include the missing parts of LSP 3.6.
