### ISSUE TITLE
value returned by executeCommand() is undefined in Visual Studio Code

### ISSUE THREAD

**Issue by joshtynjala** [eclipse/lsp4j#168]
Inside a VSCode extension, when I execute a command that is defined on the language server, I can't seem to access the value that the language server returns.

Here's a simple implementation of `executeCommand()` inside the language server:

``` java
public CompletableFuture<Object> executeCommand(ExecuteCommandParams params)
{
	if(params.getCommand().equals("myCommand"))
	{
		return CompletableFuture.completedFuture(true);
	}
	return CompletableFuture.completedFuture(new Object());
}
```

For brevity, I've omitted the code that registers the command.

Inside my VSCode extension, I execute the command like this:

``` typescript
vscode.commands.executeCommand("myCommand").then((value) =>
{
	console.log("command complete:", value);
});
```

The command executes to completion, but `value` is always `undefined` in the callback, for some reason.

Is it a bug? Or am I doing something wrong?

**Comment by mickaelistria** [comment]
Can you have a look at the actual JSon message that's sent?

**Comment by joshtynjala** [comment]
I figured out how to create a custom InputStream and OutputStream implementations that log the JSON messages to the console. Here's what I'm seeing.

executeCommand from VSCode:

```
{"jsonrpc":"2.0","id":2,"method":"workspace/executeCommand","params":{"command":"myCommand","arguments":[]}}
```

Response from LSP4J:

```
{"jsonrpc":"2.0","id":2,"result":{}}
```

In my actual implementation, I'm returning a boolean value, and the response is similar.

```
{"jsonrpc":"2.0","id":2,"result":true}
```

I guess that means LSP4J is behaving correctly, and it's a bug in VSCode.

To compare, I tried creating a command in Visual Studio Code without LSP4J, and this is working correctly:

``` typescript
vscode.commands.registerCommand("myCommand", () =>
{
	return true;
});
vscode.commands.executeCommand("myCommand").then((result) =>
{
	console.log("myCommand result:", result);
});
```

Unfortunately, I need the command to be in the language server.

**Comment by joshtynjala** [comment]
I found the bug in VSCode's language client implementation:

https://github.com/Microsoft/vscode-languageserver-node/blob/c0446d0f878d148f11a1e3d6a3478baacf3a57ff/client/src/client.ts#L2165

I was able to modify this code to replace `undefined` with `(result) => result`, and that seemed to make it work. I'll open a pull request over there.

**Comment by joshtynjala** [comment]
For reference:

Microsoft/vscode-languageserver-node#323
