### ISSUE TITLE
Return '"result":null' in answer when there is a null value

### ISSUE THREAD

**Issue by apupier** [eclipse/lsp4j#172]
VS Code language server client is not supporting to have a response which is only:
```
{
    "jsonrpc": "2.0",
    "id": "1"
}
```

The specification is stating that either a result or an error needs to be provided.

It seems to be the response sent by LSP4J when a 'null' value is provided as answer.

see https://github.com/Microsoft/vscode-languageserver-node/issues/311#issuecomment-370353550

**Comment by spoenemann** [comment]
We have some code that explicitly writes null values in such cases:

https://github.com/eclipse/lsp4j/blob/a0dc7816b4c9ca6969a47a74b56afedf72d786ce/org.eclipse.lsp4j.jsonrpc/src/main/java/org/eclipse/lsp4j/jsonrpc/json/adapters/MessageTypeAdapter.java#L389-L390

I added a test to verify this:

https://github.com/eclipse/lsp4j/blob/a0dc7816b4c9ca6969a47a74b56afedf72d786ce/org.eclipse.lsp4j/src/test/java/org/eclipse/lsp4j/test/services/JsonSerializeTest.xtend#L505-L511

Could you check with the current milestone of LSP4J (0.4.0.M6)?

**Comment by apupier** [comment]
I cannot reproduce the issue with 0.4.1.
it seems that it has been fixed with 0.4.0 by this commit https://github.com/eclipse/lsp4j/commit/bf163adb66dd63d4e3e90a623c988504d640317e
