### ISSUE TITLE
EitherTypeAdapter works wrong for Either<object, object>

### ISSUE THREAD

**Issue by svor** [eclipse/lsp4j#173]
The EitherTypeAdapter works wrong when it try to read json. 
It happens when both objects are complex. In that case only left object will be chosen.

Here is a test to define this problem:

```diff
diff --git a/org.eclipse.lsp4j.jsonrpc/src/test/java/org/eclipse/lsp4j/jsonrpc/test/json/EitherTest.java b/org.eclipse.lsp4j.jsonrpc/src/test/java/org/eclipse/lsp4j/jsonrpc/test/json/EitherTest.java
index d19f728..c4a8ddf 100644
--- a/org.eclipse.lsp4j.jsonrpc/src/test/java/org/eclipse/lsp4j/jsonrpc/test/json/EitherTest.java
+++ b/org.eclipse.lsp4j.jsonrpc/src/test/java/org/eclipse/lsp4j/jsonrpc/test/json/EitherTest.java
@@ -7,6 +7,7 @@
  *******************************************************************************/
 package org.eclipse.lsp4j.jsonrpc.test.json;
 
+import com.google.gson.JsonElement;
 import org.eclipse.lsp4j.jsonrpc.json.adapters.EitherTypeAdapter;
 import org.eclipse.lsp4j.jsonrpc.messages.Either;
 import org.eclipse.lsp4j.jsonrpc.messages.Either3;
@@ -34,6 +35,19 @@ public class EitherTest {
 		Object actual = gson.fromJson(string, expected.getClass());
 		Assert.assertEquals(expected, actual);
 	}
+
+	@Test
+	public void testSerializeAndDeserializeEitherWithComplexObjects() {
+		MyObjectC myObject = new MyObjectC();
+		myObject.myProperty = Either.forRight(new B("b"));
+
+		Gson gson = createGson();
+		JsonElement jsonElement = gson.toJsonTree(myObject);
+		MyObjectC newObject = gson.fromJson(jsonElement, MyObjectC.class);
+
+		Assert.assertNotNull(newObject.myProperty.getRight());
+		Assert.assertEquals(myObject.myProperty.getRight().b, newObject.myProperty.getRight().b);
+	}
 	
 	@Test
 	public void testSerializeEither() {
@@ -105,4 +119,56 @@ public class EitherTest {
 		}
 	}
 
+	protected static class MyObjectC {
+		public Either<A, B> myProperty;
+
+		@Override
+		public boolean equals(Object obj) {
+			if (obj instanceof MyObjectA) {
+				MyObjectA other = (MyObjectA) obj;
+				return this.myProperty == null && other.myProperty == null
+						|| this.myProperty != null && this.myProperty.equals(other.myProperty);
+			}
+			return false;
+		}
+
+		@Override
+		public int hashCode() {
+			if (myProperty != null)
+				return myProperty.hashCode();
+			return 0;
+		}
+	}
+
+	private static class A {
+		int a;
+
+		@Override
+		public boolean equals(Object obj) {
+			if (obj instanceof A) {
+				A other = (A) obj;
+				return this.a == other.a;
+			}
+			return false;
+		}
+	}
+
+	private static class B {
+		String b;
+
+		public B(String b) {
+			this.b = b;
+		}
+
+		@Override
+		public boolean equals(Object obj) {
+			if (obj instanceof B) {
+				B other = (B) obj;
+				return this.b == null && other.b == null
+						|| this.b != null && this.b.equals(other.b);
+			}
+			return false;
+		}
+	}
+
 }
```

**Comment by svor** [comment]
@gorkem you might be interested on it. It is needed for new structure of  `WorkspaceEdit` which has `List<Either<ResourceChange, TextDocumentEdit>>` field

**Comment by spoenemann** [comment]
The current implementation of Either assumes that we can decide whether to take the left or right type by peeking the next Json token. It does not support cases where both types start with the same token, e.g. the start of an object. As far as I can think, such a case can be handled correctly only by implementing a Gson TypeAdapter for that particular class.

We have overlooked this problem when merging #163.

@gorkem do you see a chance of changing this part of the proposal for the resourceChanges capability? The best solution would be to avoid a union type in the specification.

**Comment by gorkem** [comment]
@spoenemann Specification is not finalized yet. I think we can still do updates

**Comment by spoenemann** [comment]
I propose to revert #163 and wait until that part of the specification is clarified. @gorkem do you agree?

**Comment by gorkem** [comment]
@spoenemann let me take another stab at unifying the array. If it takes longer we can revert on Monday.

**Comment by spoenemann** [comment]
In #179 I marked that part of the protocol with `@Beta`, which is documented as 

> Signifies that a public API (public class, method or field) is subject to incompatible changes, or even removal, in a future release. An API bearing this annotation is exempt from any compatibility guarantees made by its containing library.

So let's keep it in the current state (even if it doesn't work) and change it later on.

**Comment by spoenemann** [comment]
#230 fixes this particular problem. Regarding the original issue, now an exception is thrown whenever the EitherTypeAdapter cannot decide whether to take the left or the right alternative. When such an exception is found at runtime, a TypeAdapterFactory must be attached to that type usage as I did in #230.
