### ISSUE TITLE
Invalid JSON message sent on shutdown

### ISSUE THREAD

**Issue by fbricon** [eclipse/lsp4j#18]
From the [Java extension for VS Code](https://github.com/redhat-developer/vscode-java), when closing the current folder, a shutdown request is emitted to the [Java Language server](https://github.com/gorkem/java-language-server).

From the current implementation of shutdown:

```
	@Override
	public CompletableFuture<Void> shutdown() {
	        ...
		return CompletableFuture.completedFuture(null);
	}
```

an invalid message is received by the client:
```
Received message which is neither a response nor a notification message:
{
    "id": "3",
    "jsonrpc": "2.0"
}
```

Before we moved to lsp4j, shutdown was handled by sending [an empty Object](https://github.com/gorkem/java-language-server/blob/de56e21692e4553bdab3593c622b28f39dbef50d/org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/handlers/ShutdownHandler.java#L30).

I think the current behavior of the LSP4J wrt shutdown() is incorrect, it should always return an empty result, from my understanding of https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#shutdown-request. 

Originally reported as https://github.com/gorkem/java-language-server/issues/106

**Comment by cdietrich** [comment]
i see vscode hanging when closing with xtext language server as well

**Comment by svenefftinge** [comment]
It is published to maven central now.

**Comment by cdietrich** [comment]
hmmm i am still seeing this. have to investigate

**Comment by cdietrich** [comment]
Xtext currently implements this as 

```
	override CompletableFuture<Object> shutdown() {
		return CompletableFuture.completedFuture(null);
	}
```
in `NullResponseTest` (created for this issue) it is explictely tested that there is no result.
=> should we return new Object() to make vscode happy?

**Comment by svenefftinge** [comment]
Yes, such thinks need to be clarified between the client and the server. lsp4j should not automatically turn a null into an object.

**Comment by vossad01** [comment]
@svenefftinge Can you explain how this works?  It is very counterintuitive when the [spec says to return _null_](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#shutdown-request) but to make JSP4J work we need to return an object.
