### ISSUE TITLE
Switch to GSON from orbit

### ISSUE THREAD

**Issue by dhuebner** [eclipse/lsp4j#19]
We can pull gson from p2 now:
http://download.eclipse.org/tools/orbit/N-builds/N20161124181148/repository/

By the end of the week we can use the S build for Oxigen M4

**Comment by dhuebner** [comment]
@spoenemann New stable build is published:
[S20161205183421](http://download.eclipse.org/tools/orbit/downloads/drops/S20161205183421/repository/)

**Comment by spoenemann** [comment]
Done with 62436e2
