### ISSUE TITLE
Cannot consume language server with lsp4j 0.5.0 because of colorprovider

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lsp4j#190]
I'm trying to consume CSS language server from vscode with lsp4j 0.5.0 but I have an error of parsing with colorprovider.

It seems that lsp4j wait for a result for colorprovider with an object although all CSS, JSON, HTML language server returns a boolean https://github.com/Microsoft/vscode/search?utf8=%E2%9C%93&q=colorprovider&type=

When I change the colorprovider from true to {} in the CSS language server, all features are working.

Is lsp4j or vscode which have done an error?

**Comment by spoenemann** [comment]
You mean LSP4J 0.4.0, right?

In the [specification](https://microsoft.github.io/language-server-protocol/specification), the type of the `colorProvider` field of ServerCapabilities is given as
```
colorProvider?: ColorProviderOptions | (ColorProviderOptions & TextDocumentRegistrationOptions & StaticRegistrationOptions);
```

They should either fix the CSS, JSON and HTML language servers or update the specification to make clear that `boolean` is also allowed.

**Comment by spoenemann** [comment]
> But I don't understand why TypeScript is working although it defines colorProvider like Java

Probably because TypeScript is JavaScript, which allows any expression to evaluate to `boolean`. And by using `JSON.parse(...)` they don't perform any checks on the JSON structure.

**Comment by spoenemann** [comment]
> No I mean 0.5.0

You mean 0.5.0-SNAPSHOT? There is no release 0.5.0 yet. the current SNAPSHOT is still on the same state as the 0.4.0 release.

> Today we cannot consume CSS, HTML, JSON Language server with LSP4j 0.4.0 because it crashes on the initialisation because colorProvider is an boolean on server side.

Please open issues at VS Code / LSP. We can keep this one open and update LSP4J in case they decide to allow `boolean` for `colorProvider`.

**Comment by angelozerr** [comment]
> Please open issues at VS Code / LSP. We can keep this one open and update LSP4J in case they decide to allow boolean for colorProvider.

Done at https://github.com/Microsoft/vscode-languageserver-node/issues/349

**Comment by spoenemann** [comment]
I'll update LSP4J according to Microsoft/vscode-languageserver-node#348 and Microsoft/vscode-languageserver-node#349 and then release a version 0.4.1 with these updates.

Is there anything else that should be included in version 0.4.1?

**Comment by angelozerr** [comment]
> I'll update LSP4J according to Microsoft/vscode-languageserver-node#348 and Microsoft/vscode-languageserver-node#349 and then release a version 0.4.1 with these updates.

Wow it's a very cool news!

> Is there anything else that should be included in version 0.4.1?

For color, I think it's OK, but it's hard to confirm that without testing. Is there an update site where I could try it?

An another question, @mickaelistria told me if lsp4j 0.4.1 could be in part of Photon https://bugs.eclipse.org/bugs/show_bug.cgi?id=533322#c5 If yes it will be a very cool news because LSP4e could host color support.

**Comment by spoenemann** [comment]
> For color, I think it's OK, but it's hard to confirm that without testing. Is there an update site where I could try it?

http://services.typefox.io/open-source/jenkins/job/lsp4j/job/release_0.4.1/lastStableBuild/artifact/build/p2-repository/

> if lsp4j 0.4.1 could be in part of Photon

We'll include LSP4J 0.4.1 in Photon M7.

**Comment by spoenemann** [comment]
Please close this once the fix is verified.

**Comment by angelozerr** [comment]
Which update site can I use to consume 0.4.1 ? I have tried http://download.eclipse.org/lsp4j/updates/milestones/ but its 0.40 and not 0.4.1?

Thanks for your help

**Comment by spoenemann** [comment]
It's not released yet, so the only available update site is

http://services.typefox.io/open-source/jenkins/job/lsp4j/job/release_0.4.1/lastStableBuild/artifact/build/p2-repository/

**Comment by angelozerr** [comment]
Perfect @spoenemann ! I will give you feedback ASAP

**Comment by angelozerr** [comment]
@spoenemann it works like a charm with 0.4.1 ! Thanks for your fix.

Do you know when you could do a release of 0.4.1 which will be available with http://download.eclipse.org/lsp4j/updates/releases/?

**Comment by spoenemann** [comment]
Tomorrow.

**Comment by angelozerr** [comment]
@spoenemann I have tested now and it seems http://download.eclipse.org/lsp4j/updates/releases/ is 0.4.0 again? Sorry I'm so impatient :)

**Comment by angelozerr** [comment]
Thank a lot @spoenemann, it works like a charm now.

Here the result with LSP4e from https://bugs.eclipse.org/bugs/show_bug.cgi?id=533322:

![lspcolorsupport](https://user-images.githubusercontent.com/1932211/40189948-e80921ce-59fd-11e8-8f70-932ac500cd18.gif)

**Comment by angelozerr** [comment]
@spoenemann I don't know if you are using lsp4j mailing list https://dev.eclipse.org/mhonarc/lists/lsp4j-dev/msg00022.html I repost the question from @martinlippert

```
I don't see lsp4j 0.4.1 in the Photon staging repo yet (it still contains 0.4.0)
```

**Comment by martinlippert** [comment]
@angelozerr @spoenemann got the answer already, having lsp4j 0.4.1 in Photon RC1 is perfect. Thanks!!!
