### ISSUE TITLE
Maven artifact for LSP4J 0.4.1 seems to have missing/erroneous dep to GSon

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lsp4j#191]
I'm migrating a LS made with Java/Maven from LSP4J 0.2 to 0.4.1. I just updated the pom to use new version and fixed minor API change.

In a unit test, running with plan Maven, I then get
```
java.lang.NoClassDefFoundError: com/google/gson/TypeAdapterFactory
  at org.eclipse.lsp4j.jsonrpc.Launcher$Builder.createJsonHandler(Launcher.java:351)
  at org.eclipse.lsp4j.jsonrpc.Launcher$Builder.create(Launcher.java:271)
  at org.eclipse.lsp4j.launch.LSPLauncher.createClientLauncher(LSPLauncher.java:102)
```
So I looked at the dependency tree and saw GSon is indeed not there
```
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ chamrousse-languageserver ---
[INFO] fr.alpesjug:chamrousse-languageserver:jar:0.0.1-SNAPSHOT
[INFO] +- org.eclipse.lsp4j:org.eclipse.lsp4j:jar:0.4.1:compile
[INFO] |  \- org.eclipse.lsp4j:org.eclipse.lsp4j.generator:jar:0.4.1:compile
[INFO] |     \- org.eclipse.xtend:org.eclipse.xtend.lib:jar:2.14.0:compile (version selected from constraint [2.11.0,3))
[INFO] |        +- org.eclipse.xtext:org.eclipse.xtext.xbase.lib:jar:2.14.0:compile
[INFO] |        |  \- com.google.guava:guava:jar:22.0-SNAPSHOT:compile (version selected from constraint [14.0,22))
[INFO] |        |     +- com.google.code.findbugs:jsr305:jar:1.3.9:compile
[INFO] |        |     +- com.google.errorprone:error_prone_annotations:jar:2.0.18:compile
[INFO] |        |     +- com.google.j2objc:j2objc-annotations:jar:1.1:compile
[INFO] |        |     \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.14:compile
[INFO] |        \- org.eclipse.xtend:org.eclipse.xtend.lib.macro:jar:2.14.0:compile
[INFO] +- org.eclipse.lsp4j:org.eclipse.lsp4j.jsonrpc:jar:0.4.1:compile
[INFO] \- junit:junit:jar:4.11:test
[INFO]    \- org.hamcrest:hamcrest-core:jar:1.3:test
```
I manually added
```xml
<dependency>
    <groupId>com.google.code.gson</groupId>
    <artifactId>gson</artifactId>
    <version>2.8.5</version>
</dependency>
```
to the pom.xml, and my test could move forward.
But most tests are failing, and when digging about the cause, I can find some
```
Caused by: java.lang.ClassNotFoundException: com.google.common.base.Strings
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```
Which are suprising as Guava 22.0-SNAPSHOT is in the dependency tree so should be in the classpath. I tried forcing newer versions of Guava in the pom.xml, but without success, I still get the same error.

**Comment by spoenemann** [comment]
https://repo.maven.apache.org/maven2/org/eclipse/lsp4j/org.eclipse.lsp4j.jsonrpc/0.4.1/org.eclipse.lsp4j.jsonrpc-0.4.1.pom

We have a dependency to `com.google.code.gson:gson:2.7` with scope `compile`, which [is documented](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Scope) as "Compile dependencies are available in all classpaths of a project. Furthermore, those dependencies are propagated to dependent projects."

Is something wrong with your Maven project configuration?

**Comment by mickaelistria** [comment]
You're right. Seems like I was using a strange version of Maven shipped by Red Hat and that behaves differently and is not suitable for regular Java developers (it's more intended to rpm package providers).  Switching back to a regular Maven worked.
