### ISSUE TITLE
Is license note an OR or an AND?

### ISSUE THREAD

**Issue by hyandell** [eclipse/lsp4j#193]
For the text in the readme on licensing, does it mean LSP4J is published under EPL or EDL, or LSP4J contains EPL and EDL elements?

---

  LSP4J is published under two licenses:
  
  Eclipse Public License v1.0
  Eclipse Distribution License - v 1.0 A BSD 3-clause License

**Comment by svenefftinge** [comment]
It is licensed under both, so you can pick the one you want.
