### ISSUE TITLE
Add deprecated property to CompletionItem and SymbolInformation 

### ISSUE THREAD

**Issue by fbricon** [eclipse/lsp4j#195]
See LSP change: Microsoft/language-server-protocol#139

**Comment by apupier** [comment]
seems it has been provided https://github.com/eclipse/lsp4j/commit/27caca0f27b5cd36a21b72dd11ecef1f52cd0ce1

https://github.com/eclipse/lsp4j/blob/eb082012a1f7c90d24b69da9f4507cf38bab81e3/org.eclipse.lsp4j/src/main/xtend-gen/org/eclipse/lsp4j/CompletionItem.java#L52-L55

**Comment by apupier** [comment]
it is available in v 0.4.1 https://github.com/eclipse/lsp4j/releases/tag/v0.4.1

**Comment by fbricon** [comment]
Cool, jdt.ls will be able to use those.
