### ISSUE TITLE
On first opening or cleaning projects non-modified files are showing up with changes

### ISSUE THREAD

**Issue by jonahgraham** [eclipse/lsp4j#199]
Doing a simple `./gradlew build eclipse` causes numerous files to have diffs. I presume this is due to differences between versions used to originally create files and current versions.

Similarly, doing a clean in Eclipse causes some java files to be generated with different content.

I would like to submit *my* version of the files to the repo so that I don't see these diffs, but I expect that means that someone else will have the problem.

Any suggestions on best way to deal with this?

**Comment by pisv** [comment]
This almost made me cry as a first time contributor.

Before discovering this description of the issue, I thought there was something wrong with my Eclipse installation and relentlessly tried to find a proper combination of Buildship and Xtend IDE going back as far as Oxygen without success.

One way to solve it might be to pinpoint the versions of Buildship and Xtend IDE that everyone should use and regenerate everything using these versions. The information about the used versions could then be stated in the contribution guide. Also, the required tool versions could be described in a `.p2f` file.

**Comment by jonahgraham** [comment]
I raised PR#492 to better document what is happening with `xtend-gen`. 

> One way to solve it might be to pinpoint the versions of Buildship and Xtend IDE that everyone should use and regenerate everything using these versions. 

The key thing is that `./gradlew build` is the "correct" one to use. I am not sure what combination in the IDE that is. It is annoying that xtend-gen directories differ.

It may be better to have the discussion about why xtend-gen directories are checked in. @spoenemann Why are the xtend-gen directories checked in? I saw that you a while ago stopped doing that for test directories. I assume there is some value in having them in source control, and if so I would like to document that as part of PR#492.

**Comment by spoenemann** [comment]
I think it should be fine to remove the generated code from source control. I don't remember why we decided to include it at some point.

**Comment by pisv** [comment]
> I raised PR#492 to better document what is happening with `xtend-gen`.
> The key thing is that `./gradlew build` is the "correct" one to use.

Oh, I see now. I missed that part, and instead of using the command line, tried to follow the steps described in the Eclipse section of the contributing guide, with mixed results. Perhaps it would not be an issue for someone who knows the gradle/Buildship/Xtend stack a bit more than I do. Thanks a lot for the detailed description in #492, I really appreciate it.

Not keeping the generated code under source control seems reasonable indeed.

**Comment by jonahgraham** [comment]
> I think it should be fine to remove the generated code from source control. I don't remember why we decided to include it at some point.

In that case, rather than try to explain complicated thing in PR#492 I will just remove the generated code.

Thanks @pisv for reminding us of this issue so that future contributors don't have this issue.

**Comment by jonahgraham** [comment]
The generated xtend files have now been removed, and the .project files have been brought up to date.

This should hopefully remove friction for future contributors.

**Comment by pisv** [comment]
Great! Thanks Jonah. Seemingly, the root .project file (`lsp4j/.project`) has not been updated, it is the only one that still gets modified when running the `lsp4j-build-gradle` launch configuration.

**Comment by jonahgraham** [comment]
Thanks for testing and reporting back - I will see if I can figure out what happened to the root .project file. I think it is a conflict between Gradle and Buildship updating things :-( There may not be a single version that fixes it.

**Comment by jonahgraham** [comment]
I have committed the modified version of `.project` - it isn't generated by gradle at the command line, but is modified when running in Eclipse with buildship. The meaning of the file contents is the same, just the order of XML elements differs. I suspect this isn't the end of the story for .project files, so I added a short comment to Contributing.md to help mitigate.

**Comment by pisv** [comment]
Thank you very much Jonah! This is very helpful.

>  I suspect this isn't the end of the story for .project files

I'm getting used to the Buildship/Xtend IDE tool stack, which seems to be rather finicky indeed.

At the risk of bothering you, I thought I should share one observation of my experiments with the tool chain: it seems unnecessary to have the .project files under source control.

Here are the steps I have done for checking it out:

1. Fork/Clone the LSP4J repository

2. Remove all .project files

3. Run ./gradlew build (successful, no .project files are generated)

4. Launch Eclipse IDE (with Buildship and Xtend IDE installed)

5. Import all projects via Import Existing Gradle Project (successful, all .project files are regenerated with *effectively* the same contents as currently in master)

6. Run 'lsp4j-build-gradle' and refresh the workspace (successful, all .project files now have *effectively and almost exactly* the same contents as currently in master: only project nature order sometimes differs for *some* projects)

Also, I have repeated this with the step 3 omitted, with the same results.

**Comment by pisv** [comment]
Also, I have just noticed that .classpath files are listed in .gitignore already, so one cannot already import the Java projects without using the Buildship import wizard. So, removing the .project files from source control does look like the next logical step to do.

**Comment by jonahgraham** [comment]
Thanks @pisv. No bother, I am delighted you are taking the time to improve this. I will reopen this and look to further improve the flow. Removing this kind of friction makes it better for everyone.
