### ISSUE TITLE
Missing xtend sources

### ISSUE THREAD

**Issue by SuperOok** [eclipse/lsp4j#20]
I see a lot of generated Java files from Xtend files in xtend-gen directories. However, the repository does not contain any *.xtend file. Are they not part of the repository? Is that done by purpose?

**Comment by svenefftinge** [comment]
It is here https://github.com/eclipse/lsp4j/blob/master/org.eclipse.lsp4j/src/main/java/org/eclipse/lsp4j/Protocol.xtend

**Comment by SuperOok** [comment]
ok, sorry, I'm blind
