### ISSUE TITLE
LSP4J 0.5.0 in Eclipse SimRel 2018-09?

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lsp4j#207]
Hi,
Is LSP4E 0.5.0 planned to be part of Eclipse SimRel 2018-09?
Asking this to sort out whether current LSP4E master should switch to LSP4J master from now on to take advantage of the various fixes?

**Comment by jonahgraham** [comment]
I can see that 0.5.0 has been [scheduled for Sep 27](https://projects.eclipse.org/projects/technology.lsp4j/releases/0.5.0) already which is about a week after the 2018-09 release on [Sep 19](https://wiki.eclipse.org/SimRel/2018-09/Simultaneous_Release_Plan). So can we bring this date back to Sep 19 and declare intent on cross-project-issues? @svenefftinge @spoenemann ?

My vote is of course it should be :+1:

**Comment by cdietrich** [comment]
@svenefftinge @spoenemann any news on that? did no see any announcements on cross project dev list

**Comment by spoenemann** [comment]
> Is LSP4E 0.5.0 planned to be part of Eclipse SimRel 2018-09?

Yes. Why do such things have to be planned during summer vacation time? :-D

I updated the 0.5.0 release date to 2018-09-07, that gives us some time to do a bugfix release before the simultaneous release in case there's a problem.
