### ISSUE TITLE
Support for DocumentSymbol 

### ISSUE THREAD

**Issue by yaohaizh** [eclipse/lsp4j#214]
Related changelog: 
https://microsoft.github.io/language-server-protocol/specification#version_3_10_0

Related issues: 
https://github.com/redhat-developer/vscode-java/issues/586

**Comment by apupier** [comment]
@yaohaizh do you mean adding support for hierarchical document symbol? I think basic Document Symbol is available in LSp4J https://github.com/eclipse/lsp4j/blob/83ae40a1d4b2b7076a8bb8ea28a953cf1fb1ca84/org.eclipse.lsp4j/src/main/xtend-gen/org/eclipse/lsp4j/DocumentSymbolCapabilities.java#L19

**Comment by yaohaizh** [comment]
@apupier Yes, it is about hierarchical document symbol. The response for ‘textDocument/documentSymbol’ is augmented with new value: **DocumentSymbol[]** | SymbolInformation[] | null

**Comment by yaohaizh** [comment]
Add related issue: https://github.com/redhat-developer/vscode-java/issues/560

**Comment by spoenemann** [comment]
Now blocked by #226.
