### ISSUE TITLE
How to use ServerCapabilities experimental?

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lsp4j#216]
By waiting for https://github.com/eclipse/lsp4j/issues/169, I have created my own LSP4j folder classes https://github.com/angelozerr/lsp4xml/tree/master/org.eclipse.lsp4xml/src/main/java/toremove/org/eclipse/lsp4j that I'm using for my XML Language Server.

I would like to activate it and I have noticed that server capabilities has a setExperimental method.

I would like the server returns 

`foldingRangeProvider: true"` in https://github.com/angelozerr/lsp4xml/blob/master/org.eclipse.lsp4xml/src/main/java/org/eclipse/lsp4xml/XMLLanguageServer.java#L61

Have you some directive to do that? Thanks for your help.

**Comment by spoenemann** [comment]
InitializeResult has a field `capabilities` of type ServerCapabilities, so Gson uses that type for serializing the result. You could try with a subclass of InitializeResult?

**Comment by angelozerr** [comment]
Thanks @spoenemann. It's exactly that I have done https://github.com/angelozerr/lsp4xml/blob/master/org.eclipse.lsp4xml/src/main/java/org/eclipse/lsp4xml/XMLLanguageServer.java#L74

Thanks for your answer.
