### ISSUE TITLE
It is not possible to navigate the generated Java source in Eclipse

### ISSUE THREAD

**Issue by kittaakos** [eclipse/lsp4j#218]
So for instance, I cannot navigate the LSP4J code when using the Xtext language server
 - when <kbd>Ctrl/Cmd</kbd>+clicking on the types,
 - with `Open Declaration` (<kbd>F3</kbd>).

OS X 10.13.3

Eclipse SDK
Version: Oxygen.3a (4.7.3a)
Build id: M20180330-0640

Xtend IDE 2.15.0.v20180701-0209 org.eclipse.xtend.sdk.feature.group

**Comment by spoenemann** [comment]
Is this related to #103?

**Comment by kittaakos** [comment]
This is what I meant, perhaps you know it better whether it is related or not.

![screencast 2018-08-02 10-53-47](https://user-images.githubusercontent.com/1405703/43574160-bd7f2b1a-9643-11e8-9597-3021c5b78e3b.gif)

**Comment by jonahgraham** [comment]
I think this works now. If there is a case that doesn't please provide more info.

![Peek 2021-04-02 09-31](https://user-images.githubusercontent.com/679236/113419884-55df3100-9396-11eb-92e4-a8dd23e891a1.gif)
