### ISSUE TITLE
Handle `$/setTraceNotification` message

### ISSUE THREAD

**Issue by BoykoAlex** [eclipse/lsp4j#22]
I have noticed that `vs-code` sometimes sends `$/setTraceNotification` message.

I could add some kind of a handler for this message in my concrete LS, however, I noticed that ts/js based language server implementation handles this message: https://github.com/Microsoft/vscode-languageserver-node/blob/master/server/src/main.ts#L1310

This leads me to believe that `lsp4j` language server framework should do the same. (Correct?)

**Comment by svenefftinge** [comment]
Whether this should go to the LSP was discussed here https://github.com/Microsoft/language-server-protocol/issues/109

Maybe we should have an additional interface for such things that clients can optionally implement. Longterm we will need to use additional interfaces for LSP extensions anyway to avoid breaking clients.

**Comment by kdvolder** [comment]
If it is possible for a client to send notification messages not strictly defined by the protocol, the current way of handling it in lsp4j... i.e. crashing the server... is not very nice.

As mentioned in the link above by @dbaeumer:

> $ messages should/could be ignored since they depend on the implementation capabilities on the server. That is why I used the $ prefix.

We've implemented our own 'wrapper' to catch these errors, log them and ignore these. But perhaps lsp4j should just ignore these unknown messages by default?

**Comment by svenefftinge** [comment]
I think they should at least be logged with warn level.

**Comment by kdvolder** [comment]
> I think they should at least be logged with warn level.

Agreed. Especially if they are totally 'unknown' notification messages. However, if its a specific message, like say `$/setTraceNotification`, then perhaps a decision can explicitly be made that that particular type of message is not one the server should want to handle. Then, dropping it silently might be okay too.

What I mean is, unless the warning serves a purpose, like, informing someone that they need to make a decision (whether they or do not want to handle it), a warning seems right. If however the decision has already been made, then the warning is just a nuisance.

**Comment by spoenemann** [comment]
I changed the UnsupportedOperationExceptions to log warnings.

@dbaeumer wrote:
> $ messages should/could be ignored since they depend on the implementation capabilities on the server. That is why I used the $ prefix.

Should we include this behavior in LSP4J, i.e. suppress the log warnings in case the method name start with `$`?

**Comment by svenefftinge** [comment]
I would prefer to not do it.

**Comment by spoenemann** [comment]
Then we can close this issue.

In order to explicitly ignore a certain type of message, one must add a `@JsonNotification` annotated method with an empty implementation to the service class.
