### ISSUE TITLE
[question] ctor of the `VersionedTextDocumentIdentifier`

### ISSUE THREAD

**Issue by kittaakos** [eclipse/lsp4j#222]
Why isn't it possible to create an instance of the `VersionedTextDocumentIdentifier` with two arguments? Is it by design, a lack of feature or I am just blind?

`VersionedTextDocumentIdentifier ` is a subtype of `TextDocumentIdentifier`.

I can create a new `TextDocumentIdentifier` with its constructor
```
new TextDocumentIdentifier("myUri");
```

But I cannot create a new `VersionedTextDocumentIdentifier` instance with the URI and the version ID.

I would like to do something like this:
```
new VersionedTextDocumentIdentifier("myUri", yourVersion++);
```

But I have to do this instead:
```
val textDocument = new VersionedTextDocumentIdentifier(yourVersion++);
textDocument.uri = "myUri";
```

Or this:
```
val textDocument = new VersionedTextDocumentIdentifier();
textDocument.uri = "myUri";
textDocument.version = yourVersion++;
```

Thanks!

**Comment by spoenemann** [comment]
The constructors are not really consistent. We could add more on demand.
