### ISSUE TITLE
Clean way to customize behaviors when receiving/sending messages

### ISSUE THREAD

**Issue by JiahuiJiang** [eclipse/lsp4j#23]
In the old ls-api, in order to log customized log messages, I just needed to implement `MessageTracer` for `onError`, `onRead` and `onWrite`. But in the new `Launcher` class, everything is pretty tightly coupled.
Is there a clean way I can customize the behaviors when receiving/sending messages?

**Comment by svenefftinge** [comment]
Yes, incoming messages are consumed through MessageConsumer, outgoing are through MessageProducer. You need to implement a logging version of them that delegate to the real implementation and install them into the chain.
