### ISSUE TITLE
Debug Adapter Protocol: Events do not have 'event' key

### ISSUE THREAD

**Issue by fwcd** [eclipse/lsp4j#234]
A sample JSON event output from my debug adapter:

```json
{"type":"event","seq":3,"command":"initialized","body":null}
```

The specification - however - requires an `event` key, instead of a `command` key:

```typescript
interface Event extends ProtocolMessage {
  type: 'event';

  /**
   * Type of event.
   */
  event: string;

  /**
   * Event-specific information.
   */
  body?: any;
}

interface InitializedEvent extends Event {
  event: 'initialized';
}
```
See https://microsoft.github.io/debug-adapter-protocol/specification#Events_Initialized

Not sure if this is a version inconsistency related to #232

**Comment by fwcd** [comment]
I suppose this is the code snippet that needs to change:

https://github.com/eclipse/lsp4j/blob/cc1a2a7746d10f5cfe93a283e8acaf24090b7d31/org.eclipse.lsp4j.jsonrpc.debug/src/main/java/org/eclipse/lsp4j/jsonrpc/debug/adapters/DebugMessageTypeAdapter.java#L445-L462

...corresponding to:

https://github.com/eclipse/lsp4j/blob/cc1a2a7746d10f5cfe93a283e8acaf24090b7d31/org.eclipse.lsp4j.jsonrpc.debug/src/main/java/org/eclipse/lsp4j/jsonrpc/debug/adapters/DebugMessageTypeAdapter.java#L103-L106

**Comment by jonahgraham** [comment]
@fwcd fancy a pull request for this one?

**Comment by fwcd** [comment]
@jonahgraham Sure, I can create one

**Comment by fwcd** [comment]
@jonahgraham I have squashed and signed my commits, so they should be ready for merge.

**Comment by jonahgraham** [comment]
@fwcd Thanks for the fix!
