### ISSUE TITLE
NPE calling methods without parameters

### ISSUE THREAD

**Issue by drungrin** [eclipse/lsp4j#239]
Using LSP4J to access the [Java Debug Server](https://github.com/Microsoft/java-debug) causes a NPE when calling the thread method of the Debug Server Protocol.

Actual Message:

`{"type":"request","seq":11,"command":"threads","arguments":null}`

Expected Message:

`{"type":"request","seq":11,"command":"threads","arguments":{}}`

Per JSONRPC 2.0 Specification: 

> 4.2 Parameter Structures
> If present, parameters for the rpc call MUST be provided as a Structured value. Either by-position through an Array or by-name through an Object.

Pull Request https://github.com/eclipse/lsp4j/pull/238

**Comment by jonahgraham** [comment]
Hi @drungrin, It may very well be that there is an issue with DAP (Aka Debug Server Protocol) here, however, the DAP does not actually implement the JSONRPC2.0 spec at all, but is rather similar. As a result the Java Debug Server probably could be accepting this (or the DAP spec could be tightened up). 

Either way, it is not what VS Code sends in this case. VS code provides this:

```
{"type":"request","seq":11,"command":"threads"}
```

i.e. the `"arguments"` is omitted if empty.

Can you provide a PR for this? I think the correct place to make this change is in `DebugMessageTypeAdapter`'s `write` method to omit the `"arguments"` if the `getParams` returns `null`. I suspect the same thing may apply to `"body"` of notifications and responses and `"message"` of error responses, all of those within the same `write` method.

_I am about to go on holiday, if you can get the PR with the tests updated in time I can merge it ASAP_

PS Where are you getting an NPE? In LSP4J or in Java Debug Server. If the former, a stack trace would be useful too.

Jonah

**Comment by drungrin** [comment]
Updated the PR as Proposed.

The NPE is on Java Debug Server:

> Error parsing message: com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonObject but was com.google.gson.JsonNull
> Expected a com.google.gson.JsonObject but was com.google.gson.JsonNull
> com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonObject but was com.google.gson.JsonNull
> 	at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:913)
> 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
> 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
> 	at com.google.gson.Gson.fromJson(Gson.java:887)
> 	at com.google.gson.Gson.fromJson(Gson.java:852)
> 	at com.google.gson.Gson.fromJson(Gson.java:801)
> 	at com.google.gson.Gson.fromJson(Gson.java:773)
> 	at com.microsoft.java.debug.core.protocol.JsonUtils.fromJson(JsonUtils.java:26)
> 	at com.microsoft.java.debug.core.protocol.AbstractProtocolServer.processData(AbstractProtocolServer.java:217)
> 	at com.microsoft.java.debug.core.protocol.AbstractProtocolServer.run(AbstractProtocolServer.java:98)
> 	at com.microsoft.java.debug.core.adapter.ProtocolServer.run(ProtocolServer.java:54)
> 	at com.microsoft.java.debug.plugin.internal.JavaDebugServer$2.run(JavaDebugServer.java:136)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
> 	at java.base/java.lang.Thread.run(Thread.java:844)
