### ISSUE TITLE
Equals method in org.eclipse.lsp4j.jsonrpc.messages.Either doesn't handle "null" correctly

### ISSUE THREAD

**Issue by praksb** [eclipse/lsp4j#245]
The equals method in org.eclipse.lsp4j.jsonrpc.messages.Either should handle the case where left is null on both instances and right is null on both instances which case equals should be true.

It should be changed to something like 

  else if (this.left == other.left && this.right == other.right) {
     return true;
  }

**Comment by jonahgraham** [comment]
Sounds reasonable. Can you provide a Pull Request (with a test so it doesn't regress)?

**Comment by praksb** [comment]
https://github.com/eclipse/lsp4j/pull/247

**Comment by kittaakos** [comment]
Closed via https://github.com/eclipse/lsp4j/pull/247.
