### ISSUE TITLE
Support Prepare Rename Request

### ISSUE THREAD

**Issue by KamasamaK** [eclipse/lsp4j#249]
LSP v3.12.0 has added the [`textDocument/prepareRename`](https://microsoft.github.io/language-server-protocol/specification#textDocument_prepareRename) request. Along with that comes `RenameOptions`, `RenameRegistrationOptions`, and `TextDocumentClientCapabilities.rename.prepareSupport`.

**Comment by yaohaizh** [comment]
PR: https://github.com/eclipse/lsp4j/pull/277

**Comment by KamasamaK** [comment]
I've looked at PR #277 and did not see `org.eclipse.lsp4j.RenameRegistrationOptions` or modifications to `org.eclipse.lsp4j.RenameCapabilities`. Is there a reason those were left out?
