### ISSUE TITLE
Server interface implementation has no way to discover what client is making a request

### ISSUE THREAD

**Issue by robstryker** [eclipse/lsp4j#259]
When a new request comes in from a client, a server interface has no method or API to discover which client is making the request.  The stack trace looks as follows:

ThreadClientIntegrationTest$MyServerImpl.askServer(MyParam) line: 79	
NativeMethodAccessorImpl.invoke0(Method, Object, Object[]) line: not available [native method]	
NativeMethodAccessorImpl.invoke(Object, Object[]) line: 62	
DelegatingMethodAccessorImpl.invoke(Object, Object[]) line: 43	
Method.invoke(Object, Object...) line: 564	
GenericEndpoint.lambda$1(AnnotationUtil$MethodInfo, Object, Object) line: 65	
1084502906.apply(Object) line: not available	
GenericEndpoint.request(String, Object) line: 120	
RemoteEndpoint.handleRequest(RequestMessage) line: 261	
RemoteEndpoint.consume(Message) line: 190	
StreamMessageProducer.handleMessage(InputStream, StreamMessageProducer$Headers) line: 192	
StreamMessageProducer.listen(MessageConsumer) line: 94	
ConcurrentMessageProcessor<T>.run() line: 122	
Executors$RunnableAdapter<T>.call() line: 514	
FutureTask<V>.run() line: 264	

We can see that the ConcurrentMessageProcessor is essentially driving the communication between the message producer (the client) and the consumer (the server's implementation class). But this processor has no ability to directly have a reference to the client remote proxy that matches the given producer making the request. 

As an example, if we take the https://github.com/TypeFox/lsp4j-chat-app  chat-app from typefox...  and we imagine one client continues to spam the channel, the server may want to take steps to censure him, rate limit his messaging, mute him, or outright close the connection. 

However, the ChatServerImpl class  (https://github.com/TypeFox/lsp4j-chat-app/blob/master/src/main/java/io/typefox/lsp4j/chat/server/ChatServerImpl.java)   has no way to discover which client is making the request. 

As another example, if we assume a user must authenticate themselves to get a given name, the typefox example is forced to have the client send their name (or if authentication is required, name and password) with each message. If the server implementation could accurately map the given stream to a client, it wouldn't need to do this. It could prompt for the username and password only once, and simply keep the data until the stream is closed. 

What makes this more painful is that when Launcher is doing all this wiring, it clearly has enough information to provide API for this purpose. It knows the remote proxy, it knows the given streams, etc etc. It just does no mapping on its own for the user. 

I believe some solution / API to allow a server implementation to know which client is making a given request would be extremely helpful for any protocols that may be built atop LSP's lsp.jsonrpc library.

**Comment by mickaelistria** [comment]
AFAIK, at the moment, both LSP spec and LSP4J are designed to bind 1 client with 1 server. So what you're seeing here is most likely an "intentional" limitation which allowed to avoid extra-complexity early in LSP4J.
I even didn't expect LSP4J would be able to run multiple clients in parallel without failing (at generating good sequence of message id for instance). So that's good news!
Another concern is about how are notifications handled. For request/response, we can assume that only the client which throws the request is interested in the response. What about notifications? They're sent to all clients?
I think those questions need to be discussed and answers agreed with most stakeholders before going further in implementation of concurrent clients.

I'm wondering whether this proxy/dispatcher would make sense in LSP4J core or if it should be considered as an extra layer in the client (which LSP4J could provide helpers for, but not include by default). Basically, instead of passing directly a stream, this stream could be a proxy dispatching messages to this or that stream/client depending on the request/response id. So the logic wouldn't be bound to threads, but to who produces the request, which seems better to me.

**Comment by robstryker** [comment]
We may find out that the framework may wish to provide more details in the future about the request, and, since it's using reflection, has no way to provide that. Right now I'm requesting access to the remote proxy, but it's also possible we could provide other things, like the raw message received, or other context the launcher may wish to make available to extenders. 

As for being "bound to threads", when execution flows into my server interface methods, it must be on one specific thread. That thread can change from request to request, or method to method, but, for the duration of my method, only one thread is handling that call. 

It makes sense to provide context on the thread level because there's really no other to pass context in to the method call. Since one thread is handling a given message and making a given call to my interface, that thread is the one that should be provided the context. 

Even if we went with your solution of some type of proxy/dispatcher, the fact remains when that dispatcher finally calls MyServer.publicEndpoint(blah args), one specific thread is doing it. We still can't pass context (like the remote proxy) in via parameters, we still can't pass in the raw message via parameters, we can't pass in anything via parameters. If we want to provide access for the method call, it must be done via some other mechanism. 

In this case, a ThreadLocal seems to me the obvious choice. I admit I could move WHERE we provide the context into a different location... instead of at the start of the thread, we could move it to RIGHT before the code enters my server implementation method. That might be a better solution simply because we can provide more context that way. But that's a small difference, in my opinion.  

We should agree on the concept first... that if execution flows to my server implementation class, I should have a way to get "context" (remote proxy and maybe others), and that the easiest way to do that is by setting a ThreadLocal.  I genuinely cannot think of another way to store this so it's accessible to my server implementation. Maybe a Map<Thread, ContextObject> in some public model, but, again, that's basically the same as a ThreadLocal.  A model like Map<Method,ContextObject> probably wouldn't work because two threads / clients could be calling the same endpoint at the same time. 

I genuinely cannot conceive of a better method of providing access to context other than the Thread, since one request is handled by one Thread for the duration of the call to my server implementation method. 

I've cleaned up the PR quite a bit so I encourage you to look it over again.

**Comment by robstryker** [comment]
> So the logic wouldn't be bound to threads, but to who produces the request, which seems better to me.

So here's the thing... when logic enters my server method, what do I have access to? I have only my server implementation class, and the parameters passed in to my endpoint. I also know what Thread I am currently running on. 

I do NOT know who produced my request. I do NOT have access to any proxy/dispatch variables. I do NOT have access to any internal LSP models. If I needed to access a model with any of those as the key, I would be unable to even discover my key, much less the value. 

The nature of the design here is that it's all reflection and annotation based. You cannot provide me ANY context through parameters. If that road is blocked, the ONLY thing I really know that can be used as a key is what Thread I am currently running in....  or my parameters. Of course we could somehow make some ContextKey API to turn my methodName + parameter values into some type of key... but, this 1) sounds ridiculous, 2)  wouldn't solve the problem, because two clients could be making identical requests at the same time. 

We could find a way to make a unique key for each request! But then... we can't pass it in to the method call in any way so that the server impl can access it and use it.  I guess we COULD make this key available for the duration of the call via some API where it maps Thread -> CompositeKey,   and then the extender could get that CompositeKey and use it to get the ContextObject,  but,  this also makes absolutely no sense, since if we trust the Thread to hold to the CompositeKey, why not just hold the ContextObject directly? 

The point I'm trying to make here is that based on the design, there literally is no way to pass in context data to these methods except via a ThreadLocal variable. Any other solutions you may come up with are just a distortion of a ThreadLocal variable, or a map based on Thread -> Context, etc.

**Comment by spoenemann** [comment]
@robstryker what is the concrete use case / problem you would like to solve? An example chat app that was made two years ago certainly does not justify any API change.

**Comment by robstryker** [comment]
The usecase I am trying to solve is if 5 clients connect to an LSP-based protocol / server, and a request comes in to my primary interface handling all json requests, my code has no way to know which client is making the request. 

If that's not concrete enough for you, I am writing an LSP-based protocol that allows users to manage server runtimes (jboss, wildfly, eap, tomcat, felix, fuse, etc etc etc).  Some of these server runtimes may require things like credentials. When a request comes in to MyInterface.startServer(wildfly), I don't know which client is making the request. I don't know if the client has been authenticated for access to the secure storage. 

If this seems too abstract for you, then there's also the simple act of registering capabilities. If 5 clients connect to my lsp-based server, and each then call remoteProxy.registerCapabilities(MyCapabilities), and each client has different capabilities, I have no idea which client is trying to register the capabilities. I know *A* client is registering the capabilities, but I have no idea which one is.  I know 5 calls have been made to MyServerInterface.registerCapabilities(MyCapabilities), but i have no idea which client is registering which capabilities. 

If I set a breakpoint in MyServerInterface.registerCapabilities(MyCapabilities), 5 threads will all block on that call. I will have no way to know WHICH client is registering WHICH Capabilities. 

I think what I'm asking is pretty obvious:  when a request comes in to MyServerInterface.someJsonRequest(), I need to know which MyClientInterface / remoteProxy is the one making that request. I need to be able to tell who is making the request. 

The data is all there in the lsp4j.jsonrpc code. You just failed to expose it in any fashion. This is something that SHOULD be exposed. 

Finally, if you look at https://github.com/eclipse/lsp4j/pull/260/files,  I believe the only real API breakage is an additional method added to Launcher.

**Comment by spoenemann** [comment]
Fixed in #260.
