### ISSUE TITLE
[enhancement] Provide better utilities for LSP types

### ISSUE THREAD

**Issue by kittaakos** [eclipse/lsp4j#261]
- (`DocumentSymbol`) -> `iterator` using a breadth-first traversal. Maybe pre-order and post-order too.
-  (`Range`, `Range`) -> `containsRange`, `isOverlappedBy`, `isAfterRange`, `isBeforeRange`, ...
- (`Range`, `Position`) -> `containsPosition`, `isAfter`, `isBefore`, ...

**Comment by KamasamaK** [comment]
Some important ones are already covered in the opening post, but for reference, here is what the VS Code API provides for [Position](https://github.com/Microsoft/vscode/blob/a5580c3d51d083c738f7a1df952ac51cc5c006a5/src/vs/vscode.d.ts#L251) and [Range](https://github.com/Microsoft/vscode/blob/a5580c3d51d083c738f7a1df952ac51cc5c006a5/src/vs/vscode.d.ts#L370). I have found most of those methods very useful.

**Comment by kittaakos** [comment]
> here is what the VS Code API provides for [Position](https://github.com/Microsoft/vscode/blob/a5580c3d51d083c738f7a1df952ac51cc5c006a5/src/vs/vscode.d.ts#L251) and [Range](https://github.com/Microsoft/vscode/blob/a5580c3d51d083c738f7a1df952ac51cc5c006a5/src/vs/vscode.d.ts#L370).

I was looking for precisely this, did not find it. Thanks for sharing!

**Comment by KamasamaK** [comment]
Actually, implementing `java.lang.Comparable` would probably obviate the need for some comparison methods like `isBefore` and `isAfter`.
