### ISSUE TITLE
[enhancement] Generate a static `isValid` method for all `@JsonRpcData` types

### ISSUE THREAD

**Issue by kittaakos** [eclipse/lsp4j#264]
With this method, one could check if the object complies the `@NonNull` constraint before serializing it into JSON.

Something like [this](https://github.com/eclipse/xtext-core/blob/c071531b8c464c901b75103951014d0321d872a2/org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/symbol/HierarchicalDocumentSymbolService.xtend#L42-L52) but better:
```java
/**
 * {@code false} if the argument is {@code null} or any of the {@link NonNull} properties
 * are {@code null}. Otherwise, {@code true}.
 */
static def boolean isValid(DocumentSymbol symbol) {
  return symbol !== null && !DocumentSymbol.declaredFields
    .filter[annotations.exists[annotationType === NonNull]]
    .map[accessible = true; it]
    .map[get(symbol)]
    .exists[it === null];
}
```

The validation should be recursive. Preferably, we should reuse the logic from `ReflectiveMessageValidator`.

If there is already a way to validate the instances, please let me know and close this issue.

**Comment by spoenemann** [comment]
Why not use the existing `ReflectiveMessageValidator`?

**Comment by spoenemann** [comment]
We could add a generic `isValid` method to it.

**Comment by kittaakos** [comment]
> We could add a generic `isValid` method to it.

With that, yes. It is possible.
