### ISSUE TITLE
[enhancement] Simplify the generated `equals` and `hashCode` with `java.util.Objects.*` utilities

### ISSUE THREAD

**Issue by kittaakos** [eclipse/lsp4j#265]
Currently, we use the [`EqualsHashCodeProcessor `](https://github.com/eclipse/lsp4j/blob/f94535986932ebab3898a49d3e9b684832e1eb09/org.eclipse.lsp4j.generator/src/main/java/org/eclipse/lsp4j/generator/JsonRpcDataProcessor.xtend#L41) for the generation. New JDT [can simplify](https://www.eclipse.org/eclipse/news/4.9/jdt.php#java7-hashcode-equals) the generated `equals` and `hashCode` code, reducing the amount of generated code would be great.

Perhaps this is an Xtend issue and the [`EqualsHashCodeProcessor `](https://github.com/eclipse/xtext-lib/blob/e7d846106e824b3d53c0b613c54a249ba2d2cd46/org.eclipse.xtend.lib/src/org/eclipse/xtend/lib/annotations/EqualsHashCode.xtend) implementation should be changed in the [`xtext-lib`](https://github.com/eclipse/xtext-lib) repository.

**Comment by robstryker** [comment]
This is an old issue. It'd be nice if maintainers scheduled the issue or closed it as wont-fix, or maybe label it as 'help wanted' ?
