### ISSUE TITLE
Support super- and subtype hierarchies

### ISSUE THREAD

**Issue by kittaakos** [eclipse/lsp4j#272]
To support the super- and subtype hierarchies via the LSP, we need to:
 - adjust the `DocumentSymbol` API, add an [optional URI](https://github.com/Microsoft/language-server-protocol/issues/582) property,
 - reuse the `DocumentSymbol` for the [hierarchical nodes](https://github.com/Microsoft/vscode-languageserver-node/pull/346#discussion_r221659062).

**Comment by tsmaeder** [comment]
I am strictly opposed to introducing things in lsp4j that are not officially supported in LSP. It is quite easy to extend LSP with custom messages and that should be the way to go if we are not happy with the standard. LSP4J should be an implementation of LSP, nothing more, nothing less.

**Comment by KamasamaK** [comment]
@tsmaeder That is probably the reason for creating PRs for both proposals on _Microsoft/vscode-languageserver-node_, which is the de facto reference implementation and is in accordance with their [contributing guidelines](https://github.com/Microsoft/language-server-protocol/blob/master/contributing.md#how-to-contribute-to-the-language-server-protocol). 

The maintainer did not seem opposed to the concept of the proposal in the previous PR, but just had some criticisms, so we'll just have to see what feedback there is.

**Comment by spoenemann** [comment]
> I am strictly opposed to introducing things in lsp4j that are not officially supported in LSP.

LSP is evolving very quickly and so is its support in the languages and clients. We have seen quite a lot of requests from various sides for implementing proposed, but not yet officially approved extensions of the protocol in LSP4J. I think it's fine to add them to the Java API as long as we mark them with `@Beta` and add a note to their Javadoc.

**Comment by olafurpg** [comment]
Can non-LSP approved features maybe be published as a separate module `lsp4j-beta`?

**Comment by spoenemann** [comment]
> Can non-LSP approved features maybe be published as a separate module lsp4j-beta?

That's not always possible since such features might be additional fields of a non-beta class, so we'd have a dependency from the main module to the beta module.
