### ISSUE TITLE
Does Release 0.5.0 exist?

### ISSUE THREAD

**Issue by tsmaeder** [eclipse/lsp4j#275]
There seems to be a 0.5.0 release when I look at the maven central repository, however, there is no entry when I check the "releases" section in github (only 0.5.0.M1). What's the deal?

**Comment by dhuebner** [comment]
@tsmaeder 
0.5.0 was released 2018-09-07  see https://projects.eclipse.org/projects/technology.lsp4j

We just forgot to track it in github

**Comment by jabby** [comment]
Ahd about maven central, I can found 0.5.0 release here : https://search.maven.org/search?q=g:org.eclipse.lsp4j

**Comment by tsmaeder** [comment]
I think it would make sense to add the tag to the source the release was built from. Repeatable builds, etc.

**Comment by dhuebner** [comment]
@spoenemann created a tag now.
See  https://github.com/eclipse/lsp4j/releases/tag/v0.5.0
