### ISSUE TITLE
LSP4J initial 0.1.0 release

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lsp4j#28]
As LSP4E targets to get in Oxygen (and to be included in the snapshot builds soon), it would be nice if LSP4E could consume a "release-quality" milestone build that could be included in SimRel

**Comment by mickaelistria** [comment]
I imagine issue #19 can be a blocker.

**Comment by dhuebner** [comment]
@mickaelistria Why that?

**Comment by mickaelistria** [comment]
IIRC, a requirement of SimRel is to make sure 3rd party libs are in Orbit.

**Comment by spoenemann** [comment]
See https://projects.eclipse.org/projects/technology.lsp4j/governance. I just announced our Oxygen participation.

**Comment by dhuebner** [comment]
@mickaelistria We added gson to orbit

**Comment by mickaelistria** [comment]
Awesome, thanks.
