### ISSUE TITLE
Does WorkspaceEdit in version 0.5 support resourcechanges?

### ISSUE THREAD

**Issue by praksb** [eclipse/lsp4j#280]
I see that in version 0.5 resourceChanges field has a @Beta attribute. When I set resourceChanges on workspaceEdit I don't see the changes reflected on the client side. Does it not work at all in version 0.5?

    @Beta
    private List<Either<ResourceChange, TextDocumentEdit>> resourceChanges;

**Comment by spoenemann** [comment]
That property is now deprecated because LSP has a new syntax for it since version 3.13.0, see #277.

**Comment by praksb** [comment]
Thanks for your answer. Any idea when the next release of lsp4j with #277 is expected?

**Comment by spoenemann** [comment]
See here:
https://projects.eclipse.org/projects/technology.lsp4j
