### ISSUE TITLE
Update to DAP 1.32

### ISSUE THREAD

**Issue by KamasamaK** [eclipse/lsp4j#281]
I think the only [change](https://microsoft.github.io/debug-adapter-protocol/changelog) might just be adding optional `restart` to `TerminateArguments` and `DisconnectArguments`.

**Comment by jonahgraham** [comment]
Would you like to provide a Pull Request, only https://github.com/eclipse/lsp4j/blob/master/org.eclipse.lsp4j.debug/src/main/java/org/eclipse/lsp4j/debug/DebugProtocol.xtend and the version strings in https://github.com/eclipse/lsp4j/tree/master/org.eclipse.lsp4j.debug/src/main/java/org/eclipse/lsp4j/debug/services need updating, along with the regenerated xtend?

**Comment by KamasamaK** [comment]
This is resolved by #351
