### ISSUE TITLE
How to declare workspaceClientCapability.workspaceEditCapabilities.resourceOperations ?

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lsp4j#282]
I'm trying to adopt the Resource Operation in Eclipse LSP4E.
I'm not understanding how one is supposed to declare the workspaceClientCapability have support for resource operations.

If I try something like
```java
workspaceEditCapabilities.setResourceOperations(Arrays.asList(new ResourceOperationKind[] {
	ResourceOperationKind.Create, ResourceOperationKind.Rename, ResourceOperationKind.Delete }));
```
then typing is incorrect. If I change the List/Array type to String, another type issue emerges.
Is there a proper way of doing it? It's a blocker for adoption in LSP4E.

cc @yaohaizh

**Comment by yaohaizh** [comment]
Oops, this should be implementation issue. I'll make a fix.

**Comment by yaohaizh** [comment]
https://github.com/eclipse/lsp4j/pull/283
