### ISSUE TITLE
Adding Syntax Highlighting Support through lsp4j

### ISSUE THREAD

**Issue by SharkJ** [eclipse/lsp4j#289]
Hi,
I have created a DSL using Xtext that I'm using to implement as a sidecar in Eclipse Che. Everything works fine except for syntax highlighting. Since lsp4j does not support syntax highlighting, the che editor must be configured to do so, which does not have clear explanations on as of yet.
Is it possible to implement syntax highlighting through lsp4j? If so, Could anyone kindly let me know how to implement that? I would be really grateful.
Thank You!

**Comment by spoenemann** [comment]
See https://github.com/Microsoft/language-server-protocol/issues/33#issuecomment-231883169

You should ask the Che community on how to implement that in Che. If you're using the Theia IDE, you'll find some documentation here: https://www.theia-ide.org/doc/TextMate.html

**Comment by SharkJ** [comment]
Thank you @spoenemann ! I will try to find the solution within the che community. Closing the issue.
