### ISSUE TITLE
Why LanguageClient/LanguageServer do not have all the LSP methods?

### ISSUE THREAD

**Issue by lialan** [eclipse/lsp4j#29]
Just curious about how LSPLauncher actually works.

Assume in a scenario I want to do something like what has described in:
https://github.com/eclipse/lsp4j/blob/master/org.eclipse.lsp4j/src/test/java/org/eclipse/lsp4j/launcher/LauncherTest.java

I want to create a client and some server so they can talk to each other. I have to invoke LSPLauncher.createClientLauncher to create a client launcher to talk to the language server, and I have to supply the first argument with an implementation of a LanguageClient interface.

But the LanguageClient and LanguageServer interface seem to be incomplete, and it seems that I am limited to those few listed messages if I am not adding new methods to those interfaces.

Am I missing something or I am completely wrong with how LSPLauncher should work?

**Comment by spoenemann** [comment]
If you want to add support for more messages, just create methods with the `@JsonNotification` or `@JsonRequest` annotations in your subinterface or implementation class.

What messages are you missing in LanguageClient and LanguageServer?
