### ISSUE TITLE
Move Snapshot builds of LSP4J to Eclipse's Jenkins instance to add signed jars

### ISSUE THREAD

**Issue by martinlippert** [eclipse/lsp4j#290]
Since we are consuming snapshot builds of lsp4j in various places (like lsp4e, spring tools), it would be great if we could get properly signed artifacts on the snapshot build p2 repository. I don't have a strong opinion on whether it should be an official Eclipse certificate or a different one (looks like the snapshot builds are still running and being hosted on TypeFox servers), but have them signed would be really nice.

**Comment by jonahgraham** [comment]
Any objections to moving the snapshot builds to eclipse's Jenkins?

**Comment by spoenemann** [comment]
No objections.

**Comment by cdietrich** [comment]
will the artifacts still be available via sonatype oss?

**Comment by jonahgraham** [comment]
> will the artifacts still be available via sonatype oss?

Yes.

I propose that we move to eclipse JIPP and have >= to what we have now. I'll update title to reflect.

**Comment by spoenemann** [comment]
We will need to clarify which Sonatype user to use for publishing on the Eclipse Jenkins. We could ask webmaster to create a new user. For requesting access to the org.eclipse.lsp4j group see https://issues.sonatype.org/browse/OSSRH-26079

**Comment by jonahgraham** [comment]
Thanks @spoenemann I am submitting request to Eclipse Foundation. Can you remind me the URL for Typefox's jenkins? I can't remember or find it.

**Comment by jonahgraham** [comment]
See [Bug 542624](https://bugs.eclipse.org/bugs/show_bug.cgi?id=542624) for request for Sonatype user.

**Comment by spoenemann** [comment]
> Can you remind me the URL for Typefox's jenkins?

https://services.typefox.io/open-source/jenkins/job/lsp4j/

**Comment by cdietrich** [comment]
any news on this?

**Comment by jonahgraham** [comment]
This has slipped down my priority list because I am in the process of
relocating with my family to Canada. Sorry about that. The
permissions/accounts have been created to do the publishing on the JIPP.

**Comment by jonahgraham** [comment]
This was completed for 0.9.0, but it the issue wasn't closed.
