### ISSUE TITLE
Question: xtend template for `final static` 

### ISSUE THREAD

**Issue by yaohaizh** [eclipse/lsp4j#292]
OS: Ubuntu 18.04
OpenJDK 1.8.0_191

So I enlisted a clean lsp4j git repo. And by default,  I run `./gradlew build ` on the terminal. After the command finished, the git status will show some file changes. Mainly, the static value from xtend file is change from `final static` to `static final`. There are dozens of files contain this kind of change and make the git branch unclean even I didn't make any modification yet. 

So my question is how can I setup  Xtend or eclipse appropriately to avoid this issue? Thanks.

**Comment by cdietrich** [comment]
If you use the latest xtend version in both Gradle and Eclipse you will get static final everywhere

**Comment by yaohaizh** [comment]
Thanks, so can I configure the order of xtend to avoid the changes?

**Comment by cdietrich** [comment]
No
