### ISSUE TITLE
What is the Latest LSP version supported by LSP4J v0.6.0

### ISSUE THREAD

**Issue by nadeeshaan** [eclipse/lsp4j#294]
What is the supported LSP version by lsp4j 0.6.0? It would be great this info could be included in the repo README as well.

**Comment by yaohaizh** [comment]
It is included in the changelog: https://github.com/eclipse/lsp4j/blob/master/CHANGELOG.md

**Comment by nadeeshaan** [comment]
Thanks @yaohaizh
