### ISSUE TITLE
Documentation on how to create a LanguageClient

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lsp4j#3]
Documentation currently shows `...` where the LanguageClient should be instantiated. It would be helpful to have details about how to actually get/create an instance as it doesn't seem obvious.
Actually, a whole example or utility method of how to start a language client from the server input/output stream would be great.

**Comment by svenefftinge** [comment]
The API is fully symmetric. I.e. the code shown in 
https://github.com/eclipse/lsp4j/tree/master/documentation

Works for the client side as well. Of course you would use LSPLauncher#createClientLauncher instead of createServerLauncher

**Comment by svenefftinge** [comment]
Maybe I didn't understand your question. 
LSP4J will provide you with an instance of LanguageServer, that internally sends messages to the given input/output stream. How the client side is implemented and created is up to you.

**Comment by mickaelistria** [comment]
Ok, so one has to create a custom instance of LanguageClient locally instead of using listeners, and then pass it to Launcher.createServerLauncher. I'll close the issue once I managed to get it working.
