### ISSUE TITLE
Update ParameterInformation to additionally support label offsets instead of label string

### ISSUE THREAD

**Issue by olafurpg** [eclipse/lsp4j#300]
LSP 3.14.0 changed the type signature of `ParameterInformation.label`

```diff
interface ParameterInformation {

	/**
	 * The label of this parameter information.
	 *
	 * Either a string or an inclusive start and exclusive end offsets within its containing
	 * signature label. (see SignatureInformation.label). The offsets are based on a UTF-16
	 * string representation as `Position` and `Range` does.
	 *
	 * *Note*: a label of type string should be a substring of its containing signature label.
	 * Its intended use case is to highlight the parameter label part in the `SignatureInformation.label`.
	 */
-	label: string;
+	label: string | [number, number];
```

Context:
- https://github.com/Microsoft/language-server-protocol/issues/611
- https://github.com/Microsoft/vscode/issues/56337

If I understand correctly, this  new feature makes it possible for language servers to provide which range in the active signature label should be highlighted for a given active parameter label. The default heuristic in VS Code is not always accurate.

![screenshot 2019-01-31 at 11 17 01-expected](https://user-images.githubusercontent.com/1408093/52049596-83c65200-254e-11e9-8c2e-0ad2654f017d.png)

**Comment by olafurpg** [comment]
@spoenemann Thanks a lot for the fix!

**Comment by spoenemann** [comment]
Here's the corresponding LSP4J definition:

https://github.com/eclipse/lsp4j/blob/944470cef05e84dea613c6c28e150af83574a3dc/org.eclipse.lsp4j/src/main/java/org/eclipse/lsp4j/Protocol.xtend#L2680-L2681
