### ISSUE TITLE
Will Lsp4j Participate in 2019-03

### ISSUE THREAD

**Issue by cdietrich** [eclipse/lsp4j#301]
Will Lsp4j Participate in 2019-03 ? the aggrcon file was not touched so far?
https://www.eclipse.org/lists/cross-project-issues-dev/msg16380.html

**Comment by cdietrich** [comment]
@kittaakos do you know anything?

**Comment by kittaakos** [comment]
There is a planned release for February: https://projects.eclipse.org/projects/technology.lsp4j/releases/0.7.0

We would like to include the `textDocument/callHierarchy` and `textDocument/typeHierarchy` language features as `@Beta`.

**Comment by cdietrich** [comment]
@spoenemann can you help out here?

**Comment by spoenemann** [comment]
No idea. Is it documented somewhere?

**Comment by cdietrich** [comment]
see message on cross project issues mailing list from above
other projects did do touch commits as well e.g. 
https://git.eclipse.org/r/plugins/gitiles/simrel/org.eclipse.simrel.build/+/98d0afd55bd4de3a32a57bef2cbe62ed912ea68a

**Comment by dhuebner** [comment]
@cdietrich 
Here is a the dummy change:

https://git.eclipse.org/c/simrel/org.eclipse.simrel.build.git/commit/?id=e4f0e49f0ac019160de3d0b152f72d29a817db53

**Comment by cdietrich** [comment]
thx @dhuebner
