### ISSUE TITLE
LSP4J seems to be locking on current thread

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lsp4j#302]
While trying to optimize LSP4E, it seems to me that LSP4J locks on the current thread/future of the request to be complete before processing further.
For example, something like
```java
server.completion(completionParams).thenRun(() -> Thread.sleep(3000));
server.completion(completionParams).thenRun(() -> System.err.println("hello"));;
```
will make that the second query won't receive it's response (and "hello" will not be printed) before the 1st future completes (after 3000 milliseconds).
A good solution is to use thenRunAsync(...) and similar async future methods, but that has the disavantage of being more expensive as it usually creates more threads.

It seems to me that the thread shouldn't be used as a lock here for better performance.

**Comment by svenefftinge** [comment]
Not sure I fully understood but the LSP is sequential so I think it is important to keep the sequential order for clients of this library. They can then spawn any number of threads and make sure the incoming events are processed in the right order.

**Comment by mickaelistria** [comment]
I'm fine with request and response being delivered sequentially.
The issue here is that when I chain the result future and the result was already received (in case `Thread.sleep` in the example), then the other threads that make requests are stuck. I would expect that the "lock" would be released as soon as the response object is built so other requests can proceed.

**Comment by mickaelistria** [comment]
Actually, I don't think it's that bad as it allows to ensure sequential requests/responses when we need it. So I don't think it's worth changing it, but maybe it'd be nice if it were made a bit more explicit (I don't know where nor how) that unless we need sequential processing, using `then...Async()` futures is recommended as regular `then...()` futures will lock one another.

**Comment by spoenemann** [comment]
There is only a single thread that handles messages from the remote side. If you want parallelism, you need to define yourself when and how.

**Comment by henryju** [comment]
My use case is the following one: I'm implementing a server, and when receiving a notification (for example didOpen), I would like to query the client for configuration (LanguageClient::configuration). This is currently not possible, because the response from the client is stuck, waiting for the didOpen notification to be processed.
```
  -> didOpen
        client.configuration(xxxx).join(); // Stuck
```

Is this use case not supported? To me it makes use of the configuration request pretty difficult (response have to be handled asynchronously).

**Comment by spoenemann** [comment]
@henryju this is a case where it makes sense to process the notification asynchronously. You can do that with an ExecutorService.

LSP4J does not enforce how to do the asynchronous processing because that may be handled differently by language servers. For example, in Xtext we have a dedicated class for it:
https://github.com/eclipse/xtext-core/blob/master/org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/concurrent/RequestManager.xtend

**Comment by henryju** [comment]
That's not always a notification. For example what happen if I need to lazily get client configuration the first time the client is asking for code actions? The codeAction request can't be handled asynchronously, since we have to return the list of code actions.

**Comment by henryju** [comment]
Another example: during the `initialized` notification, I think it make sense to allow the server to do synchronous client request (to get configuration, or to ask user for a confirmation using showMessageRequest). IMHO the point of `initialized` notification is that the server has the guarantee no other request/notification are sent from the client until it has completed. If we can't do synchronous request (and receive the response of course), then it is pretty useless.

I understand the point of having all client -> server notifications processed in order. But IMHO server -> client request's response should be handled in a separate queue.

```
-> initialized
       <- showMessageRequest request
       -> showMessageRequest response
       <- configuration request
       -> configuration response
<- initialized done
-> codeAction
   ...
```

**Comment by spoenemann** [comment]
> The codeAction request can't be handled asynchronously, since we have to return the list of code actions.

You return a `CompletableFuture<List<Either<Command, CodeAction>>>`, which can be completed asynchronously.
