### ISSUE TITLE
Provide a Hello World code sample

### ISSUE THREAD

**Issue by ahelwer** [eclipse/lsp4j#307]
It would be of great help if there were code samples showing how to set up a very simple server and a very simple client, then have them interact.

**Comment by spoenemann** [comment]
You could have a look at LauncherTest:

https://github.com/eclipse/lsp4j/blob/513a1dd2236c6495e600f644182c16b3cf19dbb2/org.eclipse.lsp4j/src/test/java/org/eclipse/lsp4j/test/launch/LauncherTest.java#L145-L164

**Comment by ahelwer** [comment]
Thanks, I'll take a look! It would be helpful to link this in the top-level README.

**Comment by jonahgraham** [comment]
Thanks @apupier.
