### ISSUE TITLE
Planned Release Date for Version 0.8.0

### ISSUE THREAD

**Issue by cdietrich** [eclipse/lsp4j#316]
Hi, is there already a planned release date for Version 0.8.0
https://projects.eclipse.org/projects/technology.lsp4j
has no entry.
we plan to release Xtext 2.18 at June 4th

**Comment by spoenemann** [comment]
There's no plan yet. The LSP specification has not changed since last year, so for now I'd propose to reuse version 0.7.0 in Eclipse 2019-06.

**Comment by kittaakos** [comment]
> The LSP specification has not changed since last year

This is true. However, the proposal of the [`textDocument/callHierarchy` language feature](https://github.com/microsoft/vscode-languageserver-node/pull/420) has been accepted and it is different from the LSP4J implementation. Wouldn't it make sense to have a `0.7.2` with the call hierarchy adjustments? [JDT-LS wants to use](https://github.com/eclipse/eclipse.jdt.ls/pull/925) it.

**Comment by spoenemann** [comment]
Sure. Would you like to implement those changes?

**Comment by kittaakos** [comment]
> Would you like to implement those changes?

Sure, I can take care of the [required code changes](https://github.com/eclipse/lsp4j/issues/317).

**Comment by cdietrich** [comment]
@kittaakos @spoenemann any timeline for `0.7.2`

**Comment by spoenemann** [comment]
I can prepare that this week so it goes into [RC1](https://wiki.eclipse.org/SimRel/2019-06/Simultaneous_Release_Plan).

**Comment by cdietrich** [comment]
is there changes needed in Xtext. if yes who can prepare?

**Comment by spoenemann** [comment]
@kittaakos are we using `textDocument/callHierarchy` in Xtext?

**Comment by cdietrich** [comment]
no we dont

**Comment by spoenemann** [comment]
Then there's no need to change anything in Xtext.

**Comment by cdietrich** [comment]
well we should at least align the versions if 0.7.2 goes into 2019-06

**Comment by spoenemann** [comment]
Cannot publish to Maven Central at the moment:
https://issues.sonatype.org/browse/MVNCENTRAL-4883

**Comment by akaroml** [comment]
@spoenemann do we know when 0.8.0 will be released? We plan to implement the new SelectionRange protocol.

**Comment by spoenemann** [comment]
https://projects.eclipse.org/projects/technology.lsp4j
