### ISSUE TITLE
Duplicate RPC method initialized

### ISSUE THREAD

**Issue by Huxpro** [eclipse/lsp4j#321]
How can I have duplicate method `initialized`?
Isn't `initialized` a default method in the `LanguageServer` interface?

```scala
  def startServer(in: InputStream, out: OutputStream) = {
    val server = new TestLanguageServer
    val launcher = LSPLauncher.createServerLauncher(server, in, out)
    val client = launcher.getRemoteProxy()
    server.connect(client)
    launcher.startListening()
  }
```
```
[error] (run-main-4) java.lang.IllegalStateException: Duplicate RPC method initialized.
[error] java.lang.IllegalStateException: Duplicate RPC method initialized.
[error] 	at org.eclipse.lsp4j.jsonrpc.services.ServiceEndpoints.lambda$getSupportedMethods$0(ServiceEndpoints.java:113)
[error] 	at org.eclipse.lsp4j.jsonrpc.services.AnnotationUtil.findRpcMethods(AnnotationUtil.java:66)
[error] 	at org.eclipse.lsp4j.jsonrpc.services.ServiceEndpoints.getSupportedMethods(ServiceEndpoints.java:90)
[error] 	at org.eclipse.lsp4j.jsonrpc.services.ServiceEndpoints.getSupportedMethods(ServiceEndpoints.java:82)
[error] 	at org.eclipse.lsp4j.jsonrpc.Launcher$Builder.getSupportedMethods(Launcher.java:365)
[error] 	at org.eclipse.lsp4j.jsonrpc.Launcher$Builder.createJsonHandler(Launcher.java:376)
[error] 	at org.eclipse.lsp4j.jsonrpc.Launcher$Builder.create(Launcher.java:307)
[error] 	at org.eclipse.lsp4j.launch.LSPLauncher.createServerLauncher(LSPLauncher.java:46)
[error] 	at test.languageserver.Main$.startServer(Main.scala:50)
[error] 	at test.languageserver.Main$.$anonfun$main$1(Main.scala:24)
[error] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
[error] 	at scala.Console$.withOut(Console.scala:167)
[error] 	at test.languageserver.Main$.main(Main.scala:24)
[error] 	at test.languageserver.Main.main(Main.scala)
```

**Comment by jonahgraham** [comment]
Check the annotations that you haven't marked your class with JsonNotification annotation, the code IIRC inherits the annotation so if it sees it a second time you will get this error. HTH.

**Comment by olafurpg** [comment]
I believe this is a Scala-specific issue that can be fixed by writing the `@JsonNotification("initialized")` annotations manually instead of extending the `LanguageServer` interface.

**Comment by Huxpro** [comment]
@jonahgraham I didn't annotate any thing yet. it's probably because Scalac duplicate some code that break the interop.

@olafurpg Thx will try. I do find that Metal wasn't extending the `LanguageServer` interface. But Dotty seems extends both `LanguageServer` and `LanguageClient`. Probably after bootstrapping they have already fixed the underlying bugs?

**Comment by Huxpro** [comment]
Similar to #313 , closed

**Comment by olafurpg** [comment]
@Huxpro I think the annotations are duplicated by the Scala 2.12 compiler, I wasn't able to reproduce in 2.11 or Dotty. Either way, I personally prefer the flat structure of

```scala
@JsonAnnotation("textDocument/definition") def textDocumentDefinition(...) = ???
@JsonAnnotation("workspace/symbol") def workspaceSymbol(...) = ???
```
over using the delegating classes so it didn't bother me much.

**Comment by Huxpro** [comment]
Other way to possibly (haven't testes) to workaround the problem, see #127

**Comment by Sciss** [comment]
Another work-around is to make sure _every_ interface method is overridden (just calling `super` if you don't want to implement them)

**Comment by jonahgraham** [comment]
Can one of the Scala devs summarize the issues for the next person and add that help to https://github.com/eclipse/lsp4j/blob/master/documentation/README.md#extending-the-protocol section of the help? That would be great.
