### ISSUE TITLE
Support for the LSP Inspector debug page

### ISSUE THREAD

**Issue by matthewmichihara** [eclipse/lsp4j#328]
I've found https://microsoft.github.io/language-server-protocol/inspector/ to be a helpful debugging tool for viewing messages sent between language client and language server.

The tool parses log files that follow a format similar to:
```
[Trace - 11:08:48 AM] Sending request 'textDocument/hover - (34)'.
Params: {
    "textDocument": {
        "uri": "file:///Code/foo.yaml"
    },
    "position": {
        "line": 18,
        "character": 15
    }
}


[Trace - 11:08:48 AM] Received response 'textDocument/hover - (34)' in 3ms.
Result: {
    "contents": [
        "this is a hover"
    ],
    "range": {
        "start": {
            "line": 18,
            "character": 10
        },
        "end": {
            "line": 18,
            "character": 23
        }
    }
}
```

I was hoping to create logs in this format by passing `LspLauncher#createClientLauncher` a custom `Function<MessageConsumer, MessageConsumer> wrapper`, but I'm having trouble knowing in the `wrapper` whether the particular message I'm seeing is one of the 6 message types that the inspector supports:

- Notification: Client -> Server
- Notification: Server -> Client
- Request: Client -> Server
- Response: Server -> Client
- Request: Server -> Client
- Response: Client -> Server

Any guidance about how I might approach this?

**Comment by spoenemann** [comment]
You could inspect the MessageConsumer you get as input of the custom function.

 * If it's a StreamMessageConsumer, you're seeing outgoing messages (Client -> Server in case of `createClientLauncher`)
 * If it's a RemoteEndpoint, you're seeing incoming messages (Server -> Client in case of `createClientLauncher`)

**Comment by spoenemann** [comment]
We could change the behavior of the `trace` argument of the Launcher factory methods to support the Inspector format. @matthewmichihara would you share your code when you get it working?

**Comment by matthewmichihara** [comment]
Great, let me try that out! Will share results if I get something working.
