### ISSUE TITLE
java.lang.IllegalStateException: Duplicate RPC method a

### ISSUE THREAD

**Issue by pwntester** [eclipse/lsp4j#335]
Hi,

Im using proguard to ofuscate my classes and therefore, I end up having multiple classes and methods with same name, but different signature (parameters and return type). I was wondering if it could be possible to account for these when deciding that an RPC method is duplicated at:
https://github.com/eclipse/lsp4j/blob/ad99a3d77139351dbc00c2dacd388fe749652309/org.eclipse.lsp4j.jsonrpc/src/main/java/org/eclipse/lsp4j/jsonrpc/services/ServiceEndpoints.java#L112

Thanks,
A

**Comment by jonahgraham** [comment]
Hello @pwntester,

I think you can achieve what you want by explicitly defining the RPC name for each method using the annotation's value, see [JsonRequest#value](https://github.com/eclipse/lsp4j/blob/2004f41565f97d591bbefd6f814073d49ca3f929/org.eclipse.lsp4j.jsonrpc/src/main/java/org/eclipse/lsp4j/jsonrpc/services/JsonRequest.java#L28) and [JsonNotification#value](https://github.com/eclipse/lsp4j/blob/2004f41565f97d591bbefd6f814073d49ca3f929/org.eclipse.lsp4j.jsonrpc/src/main/java/org/eclipse/lsp4j/jsonrpc/services/JsonNotification.java#L27) and an example in the [LanguageClient](https://github.com/eclipse/lsp4j/blob/e141b10619e1ab6da3d057fea42de2eb90d9feef/org.eclipse.lsp4j/src/main/java/org/eclipse/lsp4j/services/LanguageClient.java#L37)

If you had been hoping to use LanguageClient/Server directly, I think you are out of luck, you'll have to manually add `value`s to all of the methods that rely on the default names.

HTH,
Jonah

**Comment by pwntester** [comment]
ok, thanks Jonah!
