### ISSUE TITLE
Which Command is right ？ 

### ISSUE THREAD

**Issue by gengu** [eclipse/lsp4j#350]
I found that in lsp4j , Class Command 

```java
org.eclipse.lsp4j.Command

@NonNull
  private String title;
  
  /**
   * The identifier of the actual command handler.
   */
  @NonNull
  private String command;
  
  /**
   * Arguments that the command handler should be invoked with.
   */
  private List<Object> arguments;
```

but in monaco 

https://github.com/Microsoft/monaco-editor/blob/master/monaco.d.ts#L5451

```js
 export interface Command {
        id: string;
        title: string;
        tooltip?: string;
        arguments?: any[];
    }
```

They don't match，which is right？

**Comment by Eskibear** [comment]
From https://microsoft.github.io/language-server-protocol/specification
```ts
interface Command {
	/**
	 * Title of the command, like `save`.
	 */
	title: string;
	/**
	 * The identifier of the actual command handler.
	 */
	command: string;
	/**
	 * Arguments that the command handler should be
	 * invoked with.
	 */
	arguments?: any[];
}
```

**Comment by gengu** [comment]
So I have to ask the monaco.editor the same question , thanks !

https://github.com/Microsoft/monaco-editor/blob/master/monaco.d.ts#L5451

**Comment by gengu** [comment]
How to customize this package and then push it to the private repository？ 

Is there a document? I am not familiar with gradle

**Comment by jonahgraham** [comment]
Have a look at [contribution guide](https://github.com/eclipse/lsp4j/blob/master/Contributing.md)

**Comment by cdietrich** [comment]
for the conversion between id and command look at https://github.com/TypeFox/monaco-languageclient/blob/0788d5f8b51e68e1ea8601fa7ac1c78ef0f5e596/src/monaco-commands.ts

**Comment by gengu** [comment]
@cdietrich @jonahgraham @Eskibear Thank you very much !
