### ISSUE TITLE
SimRel 2019-09 Participation

### ISSUE THREAD

**Issue by cdietrich** [eclipse/lsp4j#352]
Hi,
It looks like the project has Not indicated the participation in 2019-09 simrel yet. Is that intended? 
https://projects.eclipse.org/releases/2019-09

https://www.eclipse.org/lists/cross-project-issues-dev/msg16899.html

**Comment by jonahgraham** [comment]
@dhuebner has now [touched](https://git.eclipse.org/c/simrel/org.eclipse.simrel.build.git/commit/lsp4j.aggrcon?id=3d2fb144cf2913931ffe7a804011851713c12694) the file and I also replied to Wayne on cross project.
