### ISSUE TITLE
Progress support in LSP

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lsp4j#370]
LSP seems supporting progress support in LSP: 

* https://github.com/microsoft/language-server-protocol/issues/786
* https://github.com/Microsoft/vscode-languageserver-node/blob/master/protocol/src/protocol.progress.proposed.ts#L1

It should be fantastic if LSP4J could support it. Thank's!

**Comment by mschaefer88** [comment]
I started adding progress support and will add the pr in a couple of days to make it available for discussion.

**Comment by martinlippert** [comment]
Any progress on the progress? :-)
Looks like the 0.9.0 release missed the progress support, any news on this?

**Comment by nixel2007** [comment]
Looks like @mschaefer88 didn't push related changes to his fork.

**Comment by AObuchow** [comment]
Any new update on this :)? Would be awesome to have @mschaefer88

**Comment by martinlippert** [comment]
Not a lot of activity from @mschaefer88 here unfortunately, so is there any plan to support the progress piece of the LSP in lsp4j without that contribution?

**Comment by Dufgui** [comment]
Hello, i will try it.
