### ISSUE TITLE
Handle close PipedInputStream

### ISSUE THREAD

**Issue by zulus** [eclipse/lsp4j#373]
Looks like JsonRpcException doesn't correctly handle exceptions from closed PipedInputStream/PipedOutputStream.

See also: https://bugs.eclipse.org/bugs/show_bug.cgi?id=545005

**Comment by mdaloia** [comment]
@jonahgraham I think this issue could be closed now as it was handled on this commit https://github.com/eclipse/lsp4j/commit/b8e5158b6520c6fcde0bb2eb3ab8415f01a3a537 to fix this other issue: https://github.com/eclipse/lsp4j/issues/432

**Comment by jonahgraham** [comment]
Thanks @mdaloia for pointing that out.
