### ISSUE TITLE
How are the composite update sites maintained

### ISSUE THREAD

**Issue by cdietrich** [eclipse/lsp4j#382]
how is http://download.eclipse.org/lsp4j/updates/releases/compositeContent.jar/compositeArtifacts.jar created/maintained. why is it a xml.
do we want to maintain these in future or drop composite update site support

options would be to switch to xml and
- maintain it from the deploy job
- maintain the composite xmls somewhere in git manually and create a job to update
(we did both of these in Xtext)

This is a follow up of https://github.com/eclipse/lsp4j/pull/378/files

**Comment by jonahgraham** [comment]
The 0.9.0 release is done - but the composites are not updated. They were not updated for 0.8.1 either. 

I vote for removing them and if I don't hear back soon I will do that.

**Comment by NiklasRentzCAU** [comment]
There are already some projects out there depending on the composite update site and that one not being updated now caused some confusion on our side. I would suggest to either keep the composite update site include the newer releases or to remove the support for that composite altogether.

**Comment by jonahgraham** [comment]
Thanks @NiklasRentzCAU for the feedback. The composite has now been removed.

**Comment by jonahgraham** [comment]
I also updated the meta-data on PMI: https://projects.eclipse.org/projects/technology.lsp4j/downloads

**Comment by jonahgraham** [comment]
Nothing left to do here.
