### ISSUE TITLE
Who has publish permission?

### ISSUE THREAD

**Issue by jonahgraham** [eclipse/lsp4j#383]
Who has publish permission (release from sonatype staging area)? The lsp4j-bot has publishing permission from ci.eclipse.org/lsp4j and can now do that with work done in #379. 

Following history in https://issues.sonatype.org/browse/OSSRH-26079 it seems @dhuebner has such permission too along with "typefox" build server. 

Can other committers (such as me) get such permission?

**Comment by cdietrich** [comment]
@jonahgraham can you create a bugzilla and ask the foundation staffers?

similar to https://bugs.eclipse.org/bugs/show_bug.cgi?id=550541 (for the bot user)
you should be able to ask what needs to be done to promote there too

**Comment by cdietrich** [comment]
i assume the foundation lsp4j-bot user can request permissions for you (do you have a sonatype account yet?)

**Comment by jonahgraham** [comment]
I do have sonatype account and publish permission for other projects.

Bug raised: [553546](https://bugs.eclipse.org/bugs/show_bug.cgi?id=553546)

**Comment by jonahgraham** [comment]
> Bug raised: [553546](https://bugs.eclipse.org/bugs/show_bug.cgi?id=553546)

Answer from webmaster is to use lsp4j-bot account. More details in bug.

**Comment by jonahgraham** [comment]
Superseded by #402 and #403
