### ISSUE TITLE
Method overload not allowed with 2 interfaces that share a method name

### ISSUE THREAD

**Issue by trancexpress** [eclipse/lsp4j#393]
I see the following exception when using LSP4J:

```
org.eclipse.lsp4j.jsonrpc.services.EndpointProxy.lambda$new$0(EndpointProxy.java:66),
org.eclipse.lsp4j.jsonrpc.services.AnnotationUtil.findRpcMethods(AnnotationUtil.java:66),
org.eclipse.lsp4j.jsonrpc.services.EndpointProxy.<init>(EndpointProxy.java:64),
org.eclipse.lsp4j.jsonrpc.services.ServiceEndpoints.toServiceObject(ServiceEndpoints.java:53),
org.eclipse.lsp4j.jsonrpc.Launcher$Builder.create(Launcher.java:313),
```

`java.lang.IllegalStateException: Method overload not allowed : public abstract java.util.concurrent.CompletableFuture sandbox.INatives2Sandbox.booleanVoid()`

The remote interfaces which I feed to LSP4J are:

```
package sandbox;
public interface INatives1Sandbox {
	@org.eclipse.lsp4j.jsonrpc.services.JsonRequest
	public java.util.concurrent.CompletableFuture<Boolean> booleanVoid();
	public static class Natives1Sandbox implements INatives1Sandbox {
		private final sandbox.Natives1 implementationInstance = new sandbox.Natives1();
		@Override
		public java.util.concurrent.CompletableFuture<Boolean> booleanVoid() {
			return java.util.concurrent.CompletableFuture.supplyAsync(() -> implementationInstance.booleanVoid());
		}
	}
}
```

```
package sandbox;
public interface INatives2Sandbox {
	@org.eclipse.lsp4j.jsonrpc.services.JsonRequest
	public java.util.concurrent.CompletableFuture<Boolean> booleanVoid();
	public static class Natives2Sandbox implements INatives2Sandbox {
		private final sandbox.Natives2 implementationInstance = new sandbox.Natives2();
		@Override
		public java.util.concurrent.CompletableFuture<Boolean> booleanVoid() {
			return java.util.concurrent.CompletableFuture.supplyAsync(() -> implementationInstance.booleanVoid());
		}
	}
}
```

I'm writing a test, so the interface names and method names are generic. Obviously I'll adjust the method names so that they are different. But it seems odd to me that two different interfaces cannot each have a method with a common name.

This is not method overloading, unless I'm missing some knowledge or restriction that the LSP4J framework has?

**Comment by jonahgraham** [comment]
> This is not method overloading, unless I'm missing some knowledge or restriction that the LSP4J framework has?

That is correct, it isn't really overloading as annotating overridden methods leads to the same error, e.g:

```
public interface Other extends LanguageServer{
	@JsonRequest
	CompletableFuture<InitializeResult> initialize(InitializeParams params);
}
```

The restriction in LSP4J is that in a class hierarchy only one method of the same name is allowed to have `@JsonRequest` annotation. In the case of using multiple interfaces, the proxy class that implements them all has the same restriction.

In the other direction, the error message is simply `Duplicate RPC method` - it probably should be that here too.

The reality the overloaded methods is what is really not allowed. Overridden methods could be supported, just some work in the code would need to be done to detect that the duplicate method name in the class hierarchy was just overridden, not overloaded. I don't know how much work this would be.

Would the  `Duplicate RPC method` error message have helped?

**Comment by trancexpress** [comment]
Having the source code, I think the error is not too difficult to understand; without the source code it would be harder. Probably indicating that two methods with the same names is not supported would have been enough to understand the error without browsing code.

As for the actual problem, I think its not that much of an issue; the methods can be renamed. I did forget that one class implements all remote interfaces. That probably makes the fix not trivial.

**Comment by jonahgraham** [comment]
> That probably makes the fix not trivial.

I think so - not sure how deep into reflection you have to get to identify that two method declarations will run the same code.

I have improved the error message and I am closing this issue now.
