### ISSUE TITLE
Hover class has no constructor for single MarkedString as contents

### ISSUE THREAD

**Issue by Cnly** [eclipse/lsp4j#396]
It seems this is because the type of the `contents` field in `Hover` was changed from `Either<T, List<T>>` to `List<T>` in https://github.com/eclipse/lsp4j/commit/6ff370566cc40af6aeaaffe8f9c79ac00e8641a3, but this also removed the constructor. Perhaps this should be added back for spec compliance?

**Comment by spoenemann** [comment]
Fixed in #437.
