### ISSUE TITLE
Missing `onPublishDiagnostic()` ?

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lsp4j#4]
i couldn't find a method to listen to published diagnostics. Was it temporarily removed or is had moved to something new?

**Comment by svenefftinge** [comment]
The LanguageServer interface no longer has callbacks for the client side messages, but instead there is a [LanguageClient](https://github.com/eclipse/lsp4j/blob/master/org.eclipse.lsp4j/src/main/java/org/eclipse/lsp4j/services/LanguageClient.java) interface.

**Comment by mickaelistria** [comment]
Ok, I think I understand how to use the new API. I leave it open until I managed to get diagnostic working.
