### ISSUE TITLE
How does the LSP implements the Syntax Highlight?

### ISSUE THREAD

**Issue by German-Development** [eclipse/lsp4j#40]
How does the LSP implements the Syntax Highlight? where are the Highlight rules defined?  say you want to define : BEGIN as a keyword and you want the keywords to be RED.

Is there any document explaining how to create a LSP implementation for a new language?

**Comment by cdietrich** [comment]
In LSP syntax highlighting is a client side thing so far. There is https://github.com/Microsoft/language-server-protocol/pull/124 to change this
