### ISSUE TITLE
Turn on publishing to Maven snapshots from 

### ISSUE THREAD

**Issue by jonahgraham** [eclipse/lsp4j#402]
At the moment LSP4J's build on https://ci.eclipse.org/lsp4j is not deploying to Maven Snapshot repositories.

https://github.com/eclipse/lsp4j/blob/21c94d0b9536a9f8a31892c4134c7ab072999dc1/releng/deploy-build.sh#L31-L33

See [Nexus](https://oss.sonatype.org/#nexus-search;gav~org.eclipse.lsp4j~org.eclipse.lsp4j~~~~kw,versionexpand) for the published snapshot artefacts.

**Comment by jonahgraham** [comment]
@spoenemann do you know where this is being published from, and can you turn it off so that https://ci.eclipse.org/lsp4j can do it?

It doesn't seem to be coming from typefox's public CI: http://services.typefox.io/open-source/jenkins/job/lsp4j/

**Comment by jonahgraham** [comment]
Turns out things are worse than I realized - the artifacts being published are not even up to date. Despite being published daily, the code it is building from is from Oct 2019.

The current version has a SNAPSHOT version of 0.9.0-20200130.034510-157, but the content was last modified on 14 Oct.

**Comment by cdietrich** [comment]
https://ci.eclipse.org/lsp4j/job/lsp4j-multi-build/job/master/15/console does that doesnt it?

**Comment by jonahgraham** [comment]
No, the deploy was disabled because of this. I have now enabled it and build [16](https://ci.eclipse.org/lsp4j/job/lsp4j-multi-build/job/master/16/console) shows it deploying and it is indeed on [maven](https://oss.sonatype.org/#nexus-search;gav~org.eclipse.lsp4j~org.eclipse.lsp4j~~~~kw,versionexpand)

My concern is that someone else will just trample it again tomorrow, unless I am just misunderstanding how something works.

**Comment by cdietrich** [comment]
is it possible the problem is the repo list here
pointing to old places: https://github.com/TypeFox/publishing/blob/master/build.gradle
maybe you can fork that and add some println so we see what jenkins url is used.
as i dont see a ` -PJENKINS_URL ` as i see it here https://ci.eclipse.org/xtext/job/releng/job/sign-and-deploy/405/consoleFull

**Comment by cdietrich** [comment]
@jonahgraham the build is invoked in the jenkins config
![Bildschirmfoto vom 2020-01-30 20-32-28](https://user-images.githubusercontent.com/238736/73483456-be500e00-439f-11ea-813f-7a33eb4a3e5c.png)

**Comment by jonahgraham** [comment]
@cdietrich I disabled and added a comment on the job - but it hasn't run in > 1 year https://ci.eclipse.org/lsp4j/job/lsp4j-snapshots/

**Comment by cdietrich** [comment]
and the thing that one publishes is up to date:
https://ci.eclipse.org/lsp4j/job/lsp4j-multi-build/job/master/16/consoleFull

**Comment by jonahgraham** [comment]
> and the thing that one publishes is up to date:
> https://ci.eclipse.org/lsp4j/job/lsp4j-multi-build/job/master/16/consoleFull

This is what I just turned on in build 16 - so it is publishing the correct stuff until it is next overwritten by the zombie deploy.

I sent an email to @spoenemann for extra insight.

**Comment by spoenemann** [comment]
I disabled the snapshots, it was on a non-public Jenkins.

**Comment by jonahgraham** [comment]
Thanks @spoenemann 

@cdietrich I see you kicked off an extra build on Eclipse to make sure current snapshot is correct version - thanks for that. (I kicked off yet another one before I realized you had already, so the snapshot will be updated again momentarily)

This is now resolved.
