### ISSUE TITLE
Turn on publishing to Maven releases from Eclipse infra

### ISSUE THREAD

**Issue by jonahgraham** [eclipse/lsp4j#403]
The current scripts that do the deployment to maven central only supports snapshots. As part of the release we need to deploy the artefacts to the release repository.

See some hints on how using the lsp4j-bot account on [Bug 553546](https://bugs.eclipse.org/bugs/show_bug.cgi?id=553546)

**Comment by jonahgraham** [comment]
I have [deployed](https://ci.eclipse.org/lsp4j/job/lsp4j-release-eclipse-jonah/2/console) a release to Maven Central - but I cannot figure out how to close the release from the command line (aka from the CI machine). So I have [requested](https://issues.sonatype.org/browse/OSSRH-26079) permission to do so. 

Once I have such permission I will close the release which will make it public.

In the meantime, for 0.9.0M3 the workaround is to temporarily add a repository pointing at download.eclipse.org. e.g.:

```
<repositories>
  <repository>
    <id>LSP4J-0.9.0M2</id>
    <url>https://download.eclipse.org/lsp4j/updates/milestones/S202002202238/maven-repository/</url>
  </repository>
</repositories>

...

    <dependency>
      <groupId>org.eclipse.lsp4j</groupId>
      <artifactId>org.eclipse.lsp4j</artifactId>
      <version>0.9.0.M3</version>
    </dependency>
```

**Comment by cdietrich** [comment]
@spoenemann could you or the typefox account approve the request ( in case sonatype wants it, in a timely manner)

**Comment by cdietrich** [comment]
> @spoenemann could you or the typefox account approve the [request](https://issues.sonatype.org/browse/OSSRH-26079) ( in case sonatype wants it, in a timely manner)

**Comment by spoenemann** [comment]
I've published the milestone on oss.sonatype.org

**Comment by jonahgraham** [comment]
Thanks @spoenemann. Were you able to release what CI had deployed, or did you need to redo the deploy too?

**Comment by spoenemann** [comment]
No, the staging artifacts were fine.

**Comment by jonahgraham** [comment]
This appears to be working fine, 0.9.0 was released successfully.
