### ISSUE TITLE
Comprehensive request params

### ISSUE THREAD

**Issue by KamasamaK** [eclipse/lsp4j#410]
As part of LSP 3.15, all requests now have explicitly defined request params. The motivation behind this was for supporting the new progress features, which are not yet implemented for LSP4J, but I was thinking it might be good to get this out of the way sooner than later. One reason for this is to prevent future compatibility breaks like what happened with `signatureHelp` in #397. This would unfortunately result in several compatibility breaks now, but it is my opinion that it's better to get it done all at once and prior to 1.0. I've compiled the following request params that would need to be created and used instead of the current `TextDocumentPositionParams`:

- HoverParams
- DeclarationParams
- DefinitionParams
- TypeDefinitionParams
- ImplementationParams
- DocumentHighlightParams

For now, they would just extend `TextDocumentPositionParams` with no additional fields.

I can create the PR for this if we're in agreement to go forward.

**Comment by jonahgraham** [comment]
+1 on making the change in the 0.9.0 version. As it breaks API this needs to be fed into LSP4E carefully for SimRel. The next LSP4J contribution is supposed to be tomorrow with the final release [next Thursday](https://projects.eclipse.org/projects/technology.lsp4j/releases/0.9.0).

Is this something achievable by tomorrow?

**Comment by cdietrich** [comment]
i would also prefer to have this already in M3 so that downstream consumers like Xtext & LSP4E can adopt

**Comment by KamasamaK** [comment]
@jonahgraham This is simple enough that I can probably have it done today. It looks like it will break `testIssue152`, so I will just need to see what is involved with fixing that.

**Comment by cdietrich** [comment]
@KamasamaK just calling a different constructor should do the trick

**Comment by cdietrich** [comment]
looks like they forgot one
https://github.com/microsoft/language-server-protocol/issues/931

**Comment by KamasamaK** [comment]
@cdietrich Good catch. I'll add `PrepareRenameParams` too.

**Comment by cdietrich** [comment]
@KamasamaK  @jonahgraham it looks like the params type were to intrpoduced to be comprehensive but to aggregate WorkDoneProgressParams with TextDocumentPositionParams

this change does not reflect this yet.

**Comment by KamasamaK** [comment]
@cdietrich That's the answer I expected, but the reasoning you provided in that issue is why I added it for LSP4J anyway.

**Comment by cdietrich** [comment]
:+1: thanks to json it wont harm.
are there plans to introduce the WorkDoneProgressParams or will we do this later / in 0.10.0?

**Comment by KamasamaK** [comment]
@cdietrich I'm thinking Progress will be later. It was mentioned in #370 that @mschaefer88 was working on it, but I guess it's taking longer than expected.

**Comment by KamasamaK** [comment]
I guess you were convincing. Now `PrepareRenameParams` is part of the spec with [31151b9](https://github.com/microsoft/language-server-protocol/commit/31151b960a65a2b8f3fff0d749390ef5844abc5c).
