### ISSUE TITLE
The spec allows the Diagnostic code to be a string or a number.

### ISSUE THREAD

**Issue by jonahgraham** [eclipse/lsp4j#413]
PR#388 says "The spec allows the Diagnostic code to be a string or a number." Unfortunately the submitter cannot contribute code to LSP4J due to an inability to sign the contributor agreement.

**Comment by jonahgraham** [comment]
@KamasamaK Any chance you can look at this location where the spec and LSP4J differ and recommend whether to fix it/change it? As this is likely yet another API change, it seems getting it in before 0.9.0 would be good.

**Comment by KamasamaK** [comment]
I would recommend fixing since:

1. We should be spec-compliant wherever possible.
2. Wouldn't leaving it break clients using LSP4J if the server sends a numeric code?

**Comment by cdietrich** [comment]
Will this be done or not? Is there a rebased branch available I can test with

**Comment by jonahgraham** [comment]
Someone needs to fix this code to meet spec. I will do it later today if no one else has by then. Unfortunately, despite a submission in pr#388, the contributor can't/won't sign eca.

**Comment by jonahgraham** [comment]
I'm doing this now
