### ISSUE TITLE
Protocol classes' properties not accessible in xtend clients

### ISSUE THREAD

**Issue by vladdu** [eclipse/lsp4j#42]
If I try to use protocol classes in an xtend class, the properties and accessors are not available. 

It looks like an xtend problem, but I'm not sure. My guess is that the xtend compiler doesn't see the generated code.

**Comment by spoenemann** [comment]
We need to include the `*._trace` files in the source jars.

**Comment by spoenemann** [comment]
Please reopen if this issue is still present with the next snapshot version.

**Comment by vladdu** [comment]
Thanks! It looks better, but there is still a problem: "go to definition" on a protocol element opens the right xtend file, but at the top: it doesn't locate and select the definition. Is it the same issue or a different one?

**Comment by spoenemann** [comment]
Strange, I don't know about this. @svenefftinge do you have an idea?

**Comment by vladdu** [comment]
If I have the lsp4j project open in the workspace, it works fine, but not when it is only in the target platform.
