### ISSUE TITLE
Update DAP to 1.42.x

### ISSUE THREAD

**Issue by ishche** [eclipse/lsp4j#428]
Hello!

Are there any plans to update DAP to 1.41?

**Comment by jonahgraham** [comment]
I am working on this now, so it is coming very soon in the code base. 

@ishche Would you be able to test the change before release?

**Comment by ishche** [comment]
> @ishche Would you be able to test the change before release?
Well, currently I'm interested in progress* from 1.40. I can play with it. Not sure if I can test everything else.

**Comment by cdietrich** [comment]
as we are already in the middle of rc1 week isnt it a bit late to schedule and do a new release?

**Comment by jonahgraham** [comment]
I am not proposing releasing anything new. I can see how my earlier message may have implied that though - sorry for confusion.

The 0.10.0 release of LSP4J is currently unscheduled. I would expect it to be in the 2020-06 timeframe unless we want to release earlier, but definitely *not* part of 2020-03!

**Comment by jonahgraham** [comment]
> > @ishche Would you be able to test the change before release?
> Well, currently I'm interested in progress* from 1.40. I can play with it. Not sure if I can test everything else.

Great! I'll let you know when it is in so you can try it out and we can be confident that it is correct before LSP4J next releases.

**Comment by cdietrich** [comment]
you mean 2020-09 correct?

**Comment by jonahgraham** [comment]
> you mean 2020-09 correct?

:-0 Yes!
