### ISSUE TITLE
Support for semantic tokens from LSP 3.16

### ISSUE THREAD

**Issue by ericdallo** [eclipse/lsp4j#430]
New Semantic tokens feature: https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/#version_3_16_0

More info on protocol here: https://github.com/microsoft/vscode-languageserver-node/blob/master/protocol/src/common/protocol.semanticTokens.proposed.ts

**Comment by kdbeall** [comment]
@ericdallo Any updates on this? Excited to see in language server protocol!

**Comment by ericdallo** [comment]
@kdbeall Actually I opened this issue to track this feature, but I don't know if someone will implement it as LSP 3.16 is not released yet

**Comment by kdbeall** [comment]
Ah, okay! I might be able to try and explore adding support for this at some point.
But, I cannot make a promise ;)

**Comment by kdbeall** [comment]
@spoenemann @svenefftinge Have there been any efforts on your end for semantic tokens?

**Comment by spoenemann** [comment]
No, not yet. Contributions are welcome!
