### ISSUE TITLE
Question: How to send Notification 

### ISSUE THREAD

**Issue by SeeBasTStick** [eclipse/lsp4j#434]
Hello, it may seem odd but I couldn´t find any way to do this.

I have the following problem. Currently, my application runs on typescript and serves a typescript client. The server will send messages like:
```typescript
let error : string = ""
connection.sendNotification("bla", "there are things wrong with blabla " + error)
```
The client, however, will receive the message and will do stuff with it, in fact showing the result in a special output channle:
```typescript
client.onReady().then(() => {
	let bla = window.createOutputChannel("internal_error")
	client.onNotification("bla", (message:string) => {
		bla.appendLine(message)
		bla.show()
	});
```

Now I want to migrate my server to java, and everything is good so far, except the fact that I can´t figure out how to send notifications.

So far my (kotlin) code looks:
```kotlin
fun startServer(inputStream: InputStream, outputStream: OutputStream){
    val server = Server()
    val launcher : Launcher<LanguageClient> = LSPLauncher.createServerLauncher(server, inputStream, outputStream)
    val startListing : Future<*> = launcher.startListening()

    server.setRemoteProxy(launcher.remoteProxy)
    startListing.get()
}
```

But with the resulting LanguageClient I am (of course) not able to achieve this because it has no method to send notifications. I have read in the files of this repository that there is something like a notification, but I am not aware of how to use it nor I am aware where to find any guide to learn what I want. 

What can I do to send simple notifications from the server? Snippets or Ressources would be great. I am thankful for every sort of help.

**Comment by cdietrich** [comment]
`org.eclipse.lsp4j.services.LanguageClient.showMessage(MessageParams)`
does not work?
you should get the client be set from outside in
`org.eclipse.lsp4j.services.LanguageClientAware.connect(LanguageClient)`
(ususally implememted by the server)

**Comment by SeeBasTStick** [comment]
> `org.eclipse.lsp4j.services.LanguageClient.showMessage(MessageParams)`
> does not work?
> you should get the client be set from outside in
> `org.eclipse.lsp4j.services.LanguageClientAware.connect(LanguageClient)`
> (ususally implememted by the server)

It works but not as I want to. `showMessage(MessageParams)` will create a Message I can´t catch on the vscode/typescipt site of the extension. It will create a popup in the right bottom. For my purpose (Debug Messages) I want a notification that I can catch on the client site and do stuff with before showing in a separate channel.

**Comment by cdietrich** [comment]
so maybe `org.eclipse.lsp4j.services.LanguageClient.logMessage(MessageParams)`
is what you are looking for?

**Comment by SeeBasTStick** [comment]
> so maybe `org.eclipse.lsp4j.services.LanguageClient.logMessage(MessageParams)`
> is what you are looking for?

That does what I want to do. I have searched for hours! Thank you so much. 

Just for documenting purpose:

On server site
```kotlin
        server.languageClient.logMessage(MessageParams(MessageType.Error, "hello - error "))
```

No need fo client actions, it will display automaticly (in vscode clients)

**Comment by tjpalmer** [comment]
The original request here was for arbitrary notifications to the client, which can be handled by the client in custom code. I don't see how either `logMessage` or `showMessage` achieves that, even if that's what @SeeBasTStick wanted in the end. Lsp4j [can receive arbitrary requests and notifications](https://github.com/eclipse/lsp4j/blob/main/documentation/jsonrpc.md#naming-of-json-rpc-request-and-notifications), but can it also send them?

**Comment by tjpalmer** [comment]
Looks like I can use `telemetryEvent` at the server and `onTelemetry` at the vscode client, but this feels hacky when `sendNotification` and `sendRequest` are more appropriate for non-telemetry purposes. (Meanwhile, I do appreciate all the work on lsp4j.)

**Comment by cdietrich** [comment]
cant you simly use client subclass with a custom jsonnontification annotated method and call this one from server?

**Comment by tjpalmer** [comment]
Thanks for the tip! I think I haven't studied well enough how the fancy auto-routing works. I'll try that out.

**Comment by tjpalmer** [comment]
I receive the client instance on `connect`. How do I make a subclass of it?
