### ISSUE TITLE
Is didChangeConfiguration supported?

### ISSUE THREAD

**Issue by anandsork** [eclipse/lsp4j#436]
How to get CongurationChange Notification (didChangeConfiguration) in Server?

The Server Capabilities are set as shown in the code below.
I could not found any method to set the capability for changeConfiguration. I searched even for setting for  DynamicRegistrationCapabilities (as its base class), but did not get any documentation (or sample code) for that as well.

I have written a VSCode extension which invokes this Server.
When I change the settings, I do not get didChangeConfiguration notification in my server. I checked that LanguageServerForJava in vsCode is getting it (I had enabled verbose logging which prints request & response).
When I checked the communication between VSCode-LanguageClient & Server, I found that only '$/setTraceNotification' is sent to server (which is unhandled)

```
// Initialize the InitializeResult for this LS.
 final InitializeResult initializeResult = new InitializeResult(new ServerCapabilities());
WorkspaceFoldersOptions wfo = new WorkspaceFoldersOptions();
 wfo.setSupported(true);
 wfo.setChangeNotifications(true);
 WorkspaceServerCapabilities wkspCap = new WorkspaceServerCapabilities(wfo);
        
 // Set the capabilities of the LS to inform the client.
 initializeResult.getCapabilities().setTextDocumentSync(TextDocumentSyncKind.Full);
 initializeResult.getCapabilities().setWorkspace(wkspCap);
 CompletionOptions completionOptions = new CompletionOptions();
 initializeResult.getCapabilities().setCompletionProvider(completionOptions);
 
return CompletableFuture.supplyAsync(()->initializeResult);
```

**Comment by cdietrich** [comment]
Xtext does it https://github.com/eclipse/xtext-core/blob/cd63d806c350d9de8bbfde5a02cca7855a806ffb/org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/LanguageServerImpl.java#L457
https://github.com/eclipse/xtext-core/blob/cd63d806c350d9de8bbfde5a02cca7855a806ffb/org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/LanguageServerImpl.java#L304

**Comment by anandsork** [comment]
Thanks. I have done in a similar way. The method, didChangeConfiguration is in different class.  Still I do not see the invocation of this method.. I see that VSCode is not sending the notification as well (so my server won't get it anyway).
I suspected, as Server is not saying it is capable of handling changeConfiguration, VSCode is not sending it (It is sending to different Java LanguageServer).
That is why I was looking for how to set this capability. 
With the code I had shown, I see that VSCode gets the response as below for the initialization request. 
```
{
    "capabilities": {
        "textDocumentSync": 1,
        "completionProvider": {},
        "workspace": {
            "workspaceFolders": {
                "supported": true,
                "changeNotifications": true
            }
        }
    }
}
```

**Comment by cdietrich** [comment]
then this might be a vscode issue. did you investigate client side?

**Comment by anandsork** [comment]
Yes.. I thought so as I saw your message.
The Issue is resolved. Thank you for your help.
(Closing the issue for now)

---
For anybody who has this issue with VSCode. 
While setting Client Options, one need to set _synchronize_ key with specifying which _configurationSection_ they need to sync. 
In this way, when any setting is changed in that particular section, the notification is sent to the Server.

Below is sample _clientOptions_ for VSCode. Remember for this issue, _synchronize_ section is important. Rest is just placeholder.
The _configurationSection_ value should match with the _configuration_ mentioned in the extension's _package.json_
```
let clientOptions: LanguageClientOptions = {
			documentSelector: [
				{ scheme: 'file', language: 'java' },
				{ scheme: 'file', language: 'cpp' }],
			diagnosticCollectionName: 'MyLangServer',
			synchronize: {
				configurationSection: 'MySettingSection'
			},
			initializationOptions: () => {
				return {
					productKey: 'vscodeExt',
					productName: 'Some Name',
					productVersion: '1.1.1',
					ideVersion: vscode.version
				};
			},
			outputChannel: someChannelVarSetEarlier,
    		revealOutputChannelOn: RevealOutputChannelOn.Error
		};
```

``` 
--package.json snippet --
"contributes": {
		"commands": [
			{
				"command": "extension.helloWorld",
				"title": "Hello World"
			}
		],
		"configuration": {
			"title": "MySettingSection",
			"properties": {
			  "MySettings.testFlag": {
				"type": "boolean",
				"default": false,
				"description": "Test Flag"
			  },
			  "MySetting.testStringSetting": {
				"type": ["string", "null"],
				"default": null,
				"description": "Specifies some String settings."
			  }
			}
		  }
	}
```

**Comment by SeeBasTStick** [comment]
I had the same problem as the poster and just wanted to add for everybody who has the same issue: The push solution (client -> server) posted is considered deprecated. Instead, vscode recommends using the server's abilities to pull the changes from the server site. I do it like:

```kotlin
    fun getDocumentSettings(uri : String) : CompletableFuture<Settings> {
        Communicator.sendDebugMessage("received configuration Data of the document $uri", MessageType.Info)
        return if(!configurationAbility){
            val returnValue = CompletableFuture<Settings>()
            returnValue.complete(globalSettings)

            returnValue
        }else{
            val configurationItem = ConfigurationItem()
            configurationItem.scopeUri = uri
            configurationItem.section = "languageServer"
            val requestedConfig = languageClient.configuration(ConfigurationParams(listOf(configurationItem)))
            documentSettings[uri] = CompletableFuture.allOf(requestedConfig).thenApply{ castJsonToSetting(requestedConfig.get().first() as JsonObject) }
            documentSettings[uri]!!
        }
    }
```

At the moment I don´t know if it will affect performance badly, because I request the configs every time something happens. What I have seen so far there is not that much of a drawback other than this solution seem a bit more 'dirty'
