### ISSUE TITLE
Build fails due mixed xtend.lib versions

### ISSUE THREAD

**Issue by cdietrich** [eclipse/lsp4j#439]
in the build config we have 

https://github.com/eclipse/lsp4j/blob/b8e5158b6520c6fcde0bb2eb3ab8415f01a3a537/gradle/xtend-compiler-settings.gradle#L13

and

https://github.com/eclipse/lsp4j/blob/b8e5158b6520c6fcde0bb2eb3ab8415f01a3a537/gradle/versions.gradle#L16

which dont play together which breaks the current build.

"[${versions.xtend_lib},3)"  seems to pull the newest one and not 2.19

**Comment by jonahgraham** [comment]
I think that this in effect backtracks by a version of xtext. IIRC the "public" in generated interfaces was recently removed. So it may be worth upgading xtend_lib and xtext to newer versions at some point. For that we probably need to advertise (README.md?) which versions of xtend we run with.

**Comment by cdietrich** [comment]
yes we would have to generally update, but newer version also have other changes.
