### ISSUE TITLE
[Bug 509535] New: java.lang.NoClassDefFoundError: com/google/gson/annotations/JsonAdapter

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lsp4j#44]
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=509535

**Comment by svenefftinge** [comment]
@spoenemann could you check is the generated manifest contains proper imports for the mentioned package?

**Comment by spoenemann** [comment]
The generated manifest does not have an import for `com.google.gson.annotations` because we don't use it directly. It's used indirectly by Gson. How can the Gson code be denied access to its own classes?

See the top of the stack:
```
java.lang.NoClassDefFoundError: com/google/gson/annotations/JsonAdapter
	at com.google.gson.internal.bind.JsonAdapterAnnotationTypeAdapterFactory.create(JsonAdapterAnnotationTypeAdapterFactory.java:45)
	at com.google.gson.Gson.getAdapter(Gson.java:423)
	at com.google.gson.Gson.toJson(Gson.java:661)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapterFactory$Adapter.write(MessageTypeAdapterFactory.java:203)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapterFactory$Adapter.write(MessageTypeAdapterFactory.java:54)
```

**Comment by spoenemann** [comment]
The Gson code where the exception occurs is this:
```
rawType.getAnnotation(JsonAdapter.class)
```
Could it be that `Class.getAnnotation(..)` throws NoClassDefFoundError because the given annotation type is not found by the classloader of the receiver class?

**Comment by svenefftinge** [comment]
Ok, so than. It seems to be an issue in the manifest of latest gson in orbit.

**Comment by spoenemann** [comment]
Should we add a package import of `com.google.gson.annotations` to work around it?

**Comment by mickaelistria** [comment]
Maybe the issue isn't caused by GSon per se, but by having multiple versions of GSon in the OSGi runtime (and maybe different involved bundles loading different version of the class).
cc @mniewrzal : do you get this issue when only gson 2.7 is present or only when 2 versions are avialable?

**Comment by mniewrzal** [comment]
Maybe to clarify. Problem is visible **ONLY** when LSP4E is installed on the top of Oxygen when two version of gson are available:
- com.google.gson_2.2.4.v201311231704.jar
- com.google.gson_2.7.0.v20161205-1708.jar

When older version (2.2.4) is removed manually then LSP4E also works ok.

With Neon.2 everything works fine.

**Comment by mickaelistria** [comment]
Ok, so maybe this highlights that gson should be marked as a singleton?

**Comment by spoenemann** [comment]
The manifest of [Gson 2.7 from Orbit](http://download.eclipse.org/tools/orbit/downloads/drops2/S20170120205402/repository/plugins/com.google.gson_2.7.0.v20161205-1708.jar) says
```
Import-Package: com.google.gson.annotations
```
I think this is a bug.

**Comment by dhuebner** [comment]
@spoenemann http://felix.apache.org/documentation/tutorials-examples-and-presentations/apache-felix-osgi-faq.html#should-a-bundle-import-its-own-exported-packages

**Comment by mickaelistria** [comment]
I think it is indeed the bug. Either the package should not be imported, or it should be imported with a version constraint.

**Comment by dhuebner** [comment]
@mickaelistria Than we should report it in gson issue tracker and see what they say.
@spoenemann I hope your workaround will work. If not, try to add `uses com.google.gson.annotations` directive to the corresponding jsp4j package. That is what helped to get rid of mixed versioned package imports in xbase lib.

**Comment by mickaelistria** [comment]
I opened https://github.com/google/gson/issues/1001 to GSon

**Comment by spoenemann** [comment]
> Then we should report it in gson issue tracker and see what they say.

But the manifest is generated by Orbit, not by Gson?

**Comment by dhuebner** [comment]
But the meta information provided is copied from http://repo1.maven.org/maven2/com/google/code/gson/gson/2.6.2/

**Comment by dhuebner** [comment]
I just found an issue for 2.8 https://github.com/google/gson/issues/957 
:-/

**Comment by dhuebner** [comment]
@mickaelistria I will provide a patch for orbit gson. I tend to remove the import rather than add a version constraint. It seems to be common to import own packages in BND, but it not really common to do it in equinox.

**Comment by dhuebner** [comment]
@mickaelistria FYI https://git.eclipse.org/r/#/c/89494/1

**Comment by dhuebner** [comment]
Fix will be part of Oxygen M6
Currently available test version:
https://hudson.eclipse.org/orbit/job/orbit-recipes/135/artifact/releng/repository/target/repository/
