### ISSUE TITLE
Add progress to Call Hierarchy

### ISSUE THREAD

**Issue by Dufgui** [eclipse/lsp4j#447]
New Call hierarchy feature: https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/#textDocument_prepareCallHierarchy

More info on protocol here: https://github.com/microsoft/vscode-languageserver-node/blob/master/protocol/src/common/protocol.callHierarchy.ts

**Comment by KamasamaK** [comment]
The call hierarchy additions have been implemented for some time. However, they're incomplete as they were overlooked in #442 so progress support for them is missing.

**Comment by Dufgui** [comment]
#449
