### ISSUE TITLE
Support for Monikers

### ISSUE THREAD

**Issue by Dufgui** [eclipse/lsp4j#448]
New Monikers feature: https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/#textDocument_moniker

More info on protocol here: https://github.com/microsoft/vscode-languageserver-node/blob/master/protocol/src/common/protocol.moniker.proposed.ts

**Comment by Dufgui** [comment]
Hello, i start on it. For MonikerKind and UniquenessLevel enum, do you prefere string constant or a real enum with an adapter ?

**Comment by spoenemann** [comment]
We have used Java enums only when the values are encoded as integers in the protocol (e.g. DiagnosticSeverity). So here String constants would be better.
