### ISSUE TITLE
Removing Semantic Highlighting

### ISSUE THREAD

**Issue by KamasamaK** [eclipse/lsp4j#457]
> Given [this](https://github.com/Microsoft/vscode-languageserver-node/pull/367), should we remove or deprecate semantic highlights as semantic tokens replace it?

_Originally posted by @ericdallo in https://github.com/eclipse/lsp4j/pull/446#issuecomment-683374512_

This question was never addressed, so I'm creating a separate issue for it. Now that Semantic Tokens are officially in the LSP 3.16 proposal and implemented in LSP4J, the Semantic Highlighting operations should be removed or deprecated. What is the view on beta/experimental features? Should they just be removed or should they be deprecated first even though they were never finalized?

**Comment by spoenemann** [comment]
The `@Beta` annotation says something like "use at your own risk, this might change or be removed". Nonetheless it would make sense to add `@Deprecated` to the affected parts of the API before our 0.10.0 release and remove them after the release.

**Comment by KamasamaK** [comment]
I've added `@Deprecated` to the Semantic Highlighting API. I will remove that API some time after 0.10.0 release.

**Comment by KamasamaK** [comment]
@kittaakos As the one who created the semantic highlighting API, how do you feel about the timeline of its removal?

**Comment by kittaakos** [comment]
@KamasamaK, thank you for keeping an eye on this. :+1: Please, feel free to remove the unused APIs. I do not have any obejctions.
