### ISSUE TITLE
Support for `textDocument/onTypeRename`

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lsp4j#469]
LSP 3.16 provides a new `onTypeRename` support https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/#textDocument_onTypeRename that we would like to consume in our XML Language Server to manage mirror cursor capability (when you update a start tag element, it will update the end tag element).

It should be really nice that lsp4j provides this support. Thanks!

**Comment by KamasamaK** [comment]
This has been renamed `textDocument/linkedEditingRange`
