### ISSUE TITLE
Retention policy on your update site

### ISSUE THREAD

**Issue by othomann** [eclipse/lsp4j#47]
JDT-LS project consumes lsp4j. Till now, it was done by using an inner jar. I'd like to move to consume lsp4j from your update site. Right now the update site seems to be flushed every time you have a new build. Could it be possible to get at least a one-week retention so that our builds don't break as soon as you have a new drop available?
How can we get this setup so that we can consume directly from your update site without being broken?

**Comment by spoenemann** [comment]
Which update site do you mean?

**Comment by othomann** [comment]
Ok, I think I didn't choose the right update site. I have:
http://services.typefox.io/open-source/jenkins/job/lsp4j/job/master/lastSuccessfulBuild/artifact/build/p2-repository/
I would need an update site with weekly builds so that we can consume your work on a weekly basis.

Feel free to close this issue.

**Comment by kittaakos** [comment]
@othomann, you could try to use the [0.0.1.M4] update site. But I assume, you were already aware of its existence.

[0.0.1.M4]: http://services.typefox.io/open-source/jenkins/job/lsp4j/job/milestone_0.1.0.M4/lastSuccessfulBuild/artifact/build/p2-repository/

**Comment by othomann** [comment]
Yes, but this one is too old :-). We used to include in our bundle inner jars for lsp4j. I wanted to move to real dependencies using required bundles instead of inner jars. But I didn't choose the right update site and it broke our target after each of your build. Not sure what the best way is at this point for us to consume your bundles using bundle dependencies instead of inner jars and not be broken when you run newer builds.

**Comment by kittaakos** [comment]
> Yes, but this one is too old :-)

Meanwhile, maybe you can try [this p2 site].

[this p2 site]: http://services.typefox.io/open-source/jenkins/job/lsp4j/job/release_0.1.0/2/artifact/build/p2-repository/

**Comment by spoenemann** [comment]
We would like to add a job that publishes our continuously built update site to http://download.eclipse.org/lsp4j/updates/ on a nightly basis (with signed jars). Would that work for you, @othomann, or do you really need weekly updates?

**Comment by othomann** [comment]
Ideally we would need a p2 site that we can refresh weekly. We are working against Oxygen I-builds. We refresh our target platform every week. It would be nice if we could have a site where we could grab a "stable" version of LSP4J that we can refresh weekly so that we can keep tracks of your changes. Is this feasible?

**Comment by othomann** [comment]
What is the refresh rate of http://services.typefox.io/open-source/jenkins/job/lsp4j/job/release_0.1.0/2/artifact/build/p2-repository/ ?
If the builds stay there for at least a week, this might be good enough.

**Comment by spoenemann** [comment]
That build has no trigger, it won't be updated. We will discuss the publishing schedule when we get to set up the deployment job to http://download.eclipse.org/lsp4j/updates/.

**Comment by mickaelistria** [comment]
Release 0.1.0 is available at a stable URL ( http://download.eclipse.org/lsp4j/updates/releases/0.1.0/ ) and the pattern seems sustainable. Can we consider this issue fixed?
