### ISSUE TITLE
Upgrade websocket utilities to Jakarta

### ISSUE THREAD

**Issue by apupier** [eclipse/lsp4j#471]
it will allow to be compatible with eclipse-ee4j Tyrus 2.0.0 https://github.com/eclipse-ee4j/tyrus

From what I understood, it will require an API break unless it will be possible to provide for both version in parallel.

example of issue https://github.com/eclipse-ee4j/tyrus/issues/724 when trying to use Tyrus 2.0.0 with org.eclipse.lsp4j.websocket.WebSocketEndpoint<LanguageClient>

**Comment by jonahgraham** [comment]
Do you have a proposed patch that handles this? Is there any actual API change other than the package renaming? I think it is reasonable and a good idea to update to the jakarta version. However I don't know what impact it may have on others. 

I will add a comment on #203 where the websocket was first added to give people a reasonable opportunity to comment.

**Comment by apupier** [comment]
> Do you have a proposed patch that handles this? Is there any actual API change other than the package renaming?

unfortunately, no and I don't know. I just discovered it while trying to upgrade my Language Server. I know very little on websocket. I thought that it is important to report it. I do no think that it is something urgent to deal with but it seems important to tackle for the future and have it on the radar.

**Comment by jonahgraham** [comment]
Thanks @apupier - not sure who will take this up, if you come back to it I can see how I can support you in fixing it when you need it.

**Comment by apupier** [comment]
I think there is the need to open a CQ (to be done by acommitter of lsp4j) for jakarta.websocket to update the target file: https://github.com/eclipse/lsp4j/blob/5cc2304f3fde9b1e82bf9e76eb6e6be4bf8fb28c/releng/releng-target/lsp4j.target.target#L11-L12

**Comment by jonahgraham** [comment]
> I think there is the need to open a CQ (to be done by acommitter of lsp4j) for jakarta.websocket to update the target file:

Jakarta is under the Eclipse Foundation, so no need for CQs. 

Much of Jakarta is not published in a way that can be easily consumed by p2, therefore some. Jakarta bundles have been added to orbit to simplify their reuse.

**Comment by apupier** [comment]
> > I think there is the need to open a CQ (to be done by acommitter of lsp4j) for jakarta.websocket to update the target file:
> 
> Jakarta is under the Eclipse Foundation, so no need for CQs.

good point

> 
> Much of Jakarta is not published in a way that can be easily consumed by p2, therefore some. Jakarta bundles have been added to orbit to simplify their reuse.

I see only 3 jakarta bundles on orbit https://download.eclipse.org/tools/orbit/downloads/drops/R20201130205003/ (and not the websocket one)

**Comment by jonahgraham** [comment]
So far I, and others, have only added ones we needed.

See https://wiki.eclipse.org/Orbit/Adding_Bundles_To_Orbit_In_5_Minutes for instructions and use placeholder CQ 22020 as the other Jakarta ones did.

**Comment by apupier** [comment]
> So far I, and others, have only added ones we needed.
> 
> See https://wiki.eclipse.org/Orbit/Adding_Bundles_To_Orbit_In_5_Minutes for instructions and use placeholder CQ 22020 as the other Jakarta ones did.

here is the gerrit merge request for Jakarta: https://git.eclipse.org/r/c/orbit/orbit-recipes/+/174146
(not tested yet the generated bundle)

**Comment by jonahgraham** [comment]
@apupier Thanks for completing this.

If there are any further issues with the migration they should be raised in new issues now.
