### ISSUE TITLE
Not worked as expected but eclipse has no waning and working

### ISSUE THREAD

**Issue by glandon** [eclipse/lsp4j#475]
```python
var a = np.arange(12).reshape(3,4)
a[0,1]= 1
a.dump
var b=a[1]
```

{
	"resource": "/Users/simbaba/eclipse-workspace/scripts/Test.jpy",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "org.eclipse.xtext.xbase.validation.IssueCodes.incompatible_types",
	"severity": 8,
	"message": "Type mismatch: cannot convert from int to JpyIndexImpl",
	"startLineNumber": 13,
	"startColumn": 9,
	"endLineNumber": 13,
	"endColumn": 10
}

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$2 (file:/Users/simbaba/.vscode/extensions/simbaba.jpy-vscode-plugin-0.0.28/src/jpy/lib/guice-3.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by jonahgraham** [comment]
Can you please provide some more details? What isn't working?

**Comment by glandon** [comment]
VSCode check strict than eclipse runtime workspace. 
I want to know the type mismatched warning coming from where and i do more check .

```
JpyIndex returns XExpression:
	{JpyIndex}
	'[' indexes+=JpyRange (',' indexes+=JpyRange)* ']'
;

JpyRange returns XExpression:
	{JpyPrefixOperation} feature=[types::JvmIdentifiableElement|':'] operand=XAdditiveExpression 
	| {JpyPrefixOperation} feature=[types::JvmIdentifiableElement|':'] 
	| XAdditiveExpression (
		=>({XPostfixOperation.operand=current} feature=[types::JvmIdentifiableElement|':'])? 
	   |=>({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|':'] rightOperand=XAdditiveExpression)
	)
;

```

The followings code only reslove a[1:], a[:], a[:1], but a[1] still not worked.


**eclipse ignore return type and no error**
``` java
@Pure
@Inline(value="($1 : $2)", constantExpression=true)
public static int[] operator_range(int from, int to) {
     return new int[] {from, to};
}
```

but VSCode extesion also check return type

```
@Pure
@Inline(value="($1 : $2)", constantExpression=true)
public static JpyIndexImpl operator_range(int from, int to) {
	return null;
}

public static JpyIndexImpl operator_range(int to) {
	return null;
}
```

**Comment by jonahgraham** [comment]
I don't think that this is an Lsp4j question or issue. I imagine lsp4j is in the mix. However it looks like you are working on something xtext? Perhaps this is an xtext issue or question?

I'll leave this open for a bit in case there is more information showing how it is lsp4j related or perhaps someone else can provide some insight.

**Comment by glandon** [comment]
Thanks， I think vscode worked different with eclipse, now i resolved my problem.
Update withExpection to withoutExpection can avoid this problem.
The root cause, i think is my souce code, but the work different shocked me

**Comment by jonahgraham** [comment]
Ok. Thanks for reporting back.
