### ISSUE TITLE
Remove/deprecate 'member' semantic token, add 'method'

### ISSUE THREAD

**Issue by 0dinD** [eclipse/lsp4j#476]
The semantic token type `member` was deprecated in favor of `method` before the final release of LSP 3.16, see microsoft/language-server-protocol#1087 and [the change in the spec](https://github.com/microsoft/language-server-protocol/commit/575c23a724cbbc0aed773f9ed5d2ea0b4b1e0a6d). It seems like lsp4j [hasn't updated the semantic token types](https://github.com/eclipse/lsp4j/blob/bad217a0ea2e6475c7af4fd0380c152716424174/org.eclipse.lsp4j/src/main/java/org/eclipse/lsp4j/SemanticTokenTypes.java#L50), so I thought I'd inform you about it in case you were unaware of the change. If `member` has already made it into a release, I suggest marking it as deprecated in favor of `method`, otherwise maybe it can just be replaced entirely.

**Comment by KamasamaK** [comment]
Deprecation of `member` is handled in #472. `member` had already made it into LSP4J v0.10.0.

**Comment by 0dinD** [comment]
Ah, I didn't see that. Deprecation makes sense then.
