### ISSUE TITLE
Question: Implement a non-editor client with lsp4j

### ISSUE THREAD

**Issue by Symbolk** [eclipse/lsp4j#477]
Hi there,

I am trying to develop a tool that supports light-weight static analysis for multiple languages. The core function I expect is to infer the symbol reference relationship between program elements, which leads me to LSP for its `Go to definition` and `Find references` endpoints and a variety of language server implementations.

I know that LSP is originally designed to provide jumping and hovering functions for IDEs, so the traditional client is IDE plugins. But I expect to write an independent client in plain Java to communicate with language servers, which leads me to lsp4j.

However, after reading the test example code, I still do not quite understand how to do it or is it even possible with lsp4j? Previously, I tried to talk through plain socket but it seems too trivial (https://github.com/eclipse/eclipse.jdt.ls/issues/1129).

**Comment by jonahgraham** [comment]
Hi @Symbolk,

> Previously, I tried to talk through plain socket but it seems too trivial

I didn't understand everything in the link, but I am not sure why plain socket is too trivial. You may find test ProtocolTest.java useful as it provides a simple example of calling a simple method in a language server https://github.com/eclipse/lsp4j/blob/a5adb491cc67ab6046ada3c842e84d273df00b9d/org.eclipse.lsp4j/src/test/java/org/eclipse/lsp4j/test/services/ProtocolTest.java#L38
