### ISSUE TITLE
Inconsistencies in *RegistrationOptions

### ISSUE THREAD

**Issue by pisv** [eclipse/lsp4j#481]
Some of the `*RegistrationOptions` classes need to be made consistent with the current LSP specification.

Full list of classes to update:

- [ ] `CallHierarchyRegistrationOptions` - does not extend `StaticRegistrationOptions`
- [ ] `DeclarationRegistrationOptions` - does not extend `StaticRegistrationOptions`
- [ ] `DocumentSymbolRegistrationOptions` - missing `label`?: `string`
- [ ] `ImplementationRegistrationOptions` - does not extend `StaticRegistrationOptions`
- [ ] `SemanticTokensWithRegistrationOptions` - does not extend `StaticRegistrationOptions`
- [ ] `SignatureHelpRegistrationOptions` - missing `retriggerCharacters`?: `string[]`
- [ ] `TypeDefinitionRegistrationOptions` - does not extend `StaticRegistrationOptions`

**Comment by jonahgraham** [comment]
Are there items from the list not addressed by the associated PR #483 ? I have converted the list to a check-list so that items can be checked off that are done.

**Comment by pisv** [comment]
Thanks Jonah. Looking at the current master, none of the items have been addressed yet.
