### ISSUE TITLE
p2 repo for LSP4J 0.1.0

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lsp4j#49]
I didn't manage to find out what the URL of the 0.1.0 release of LSP4J. Is this already available? Is it document somewhere?

**Comment by kittaakos** [comment]
I found [this p2 site] in the [Hudson log]. I hope, this helps.

[this p2 site]: http://services.typefox.io/open-source/jenkins/job/lsp4j/job/release_0.1.0/lastStableBuild/artifact/build/p2-repository/
[Hudson log]: https://ci.eclipse.org/lsp4j/job/lsp4j-release/3/console

**Comment by spoenemann** [comment]
We're going to publish the 0.1.0 release to http://download.eclipse.org/lsp4j/updates/, but that's not done yet. I'll write here when it's available.

**Comment by mickaelistria** [comment]
Thanks

**Comment by spoenemann** [comment]
Now we have a composite release update site:
http://download.eclipse.org/lsp4j/updates/releases/
