### ISSUE TITLE
Remove dependency on xtext's @Pure and ToStringBuilder

### ISSUE THREAD

**Issue by lemmy** [eclipse/lsp4j#494]
`lsp4j.debug` depends on xtext base at runtime, because the generated POJOs [import](https://github.com/eclipse/lsp4j/blob/9ae5b3c05eecdd75ec6d3154d17f871fcd124fa5/org.eclipse.lsp4j.generator/src/main/java/org/eclipse/lsp4j/generator/JsonRpcDataProcessor.xtend#L151-L161) `org.eclipse.xtext.xbase.lib.Pure` and `org.eclipse.xtext.xbase.lib.util.ToStringBuilder`.  Neither `@Pure` nor `ToStringBuilder` are required by `lsp4j.debug`'s functionality. Please consider removing the xtext dependency to shrink the set of `lsp4j.debug`'s dependencies.

Related: https://twitter.com/lemmster/status/1346543929299140610

**Comment by jonahgraham** [comment]
@spoenemann any thoughts on removing use of `@Pure`. It will be easier to do this dep removal of we do the same for LSP as DAP.

Thanks for your insights.

**Comment by spoenemann** [comment]
I think this can be changed in the JsonRpcDataProcessor, that is what generates the getters and setters as well as toString.

**Comment by jonahgraham** [comment]
@lemmy I think we have as much approval as we need for this. Would you like to provide a PR?

**Comment by lemmy** [comment]
I can do that.  To confirm, though, we have an agreement to remove *all* `@Pure` annotations in POJOs, not just `@Pure` on `toString` methods?

**Comment by cdietrich** [comment]
these other pures are generated by
org.eclipse.lsp4j.generator.JsonRpcDataProcessor.generateImplMembers(MutableClassDeclaration, JsonRpcDataTransformationContext)
delegating to 
org.eclipse.xtend.lib.annotations.AccessorsProcessor.Util

**Comment by lemmy** [comment]
Thanks, I guess adding `@Pure` is a side-effect of `JsonRpcDataProcessor.generateImplMembers` then. ;-)

**Comment by jonahgraham** [comment]
> I can do that. To confirm, though, we have an agreement to remove _all_ `@Pure` annotations in POJOs, not just `@Pure` on `toString` methods?

Yes! removing all use of `@Pure` and `ToStringBuilder` in LSP4J. 

I hope that removes all dependencies on xbase (I believe it will for DAP side, it may not for LSP).

**Comment by lemmy** [comment]
Any suggestions how to remove `@Pure` without rewriting `AccessorProcessor` and `EqualsHashCodeProcessor`?  `@Pure` is hard-wired in `AccessorProcessor's` [getter generator](https://github.com/eclipse/xtext-lib/blob/d7c8e9dcbfba97cafb04a267bcf1380b4fb58185/org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/annotations/AccessorsProcessor.java#L203) and `EqualsHashCodeProcessors's` [addHashcode](https://github.com/eclipse/xtext-lib/blob/d7c8e9dcbfba97cafb04a267bcf1380b4fb58185/org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/annotations/EqualsHashCodeProcessor.java#L116)/[addEquals](https://github.com/eclipse/xtext-lib/blob/d7c8e9dcbfba97cafb04a267bcf1380b4fb58185/org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/annotations/EqualsHashCodeProcessor.java#L394).

**Comment by jonahgraham** [comment]
I don't know. There are a few xtend/xtext experts in lsp4j, but you may get better answers from their specific channels?

**Comment by cdietrich** [comment]
The simplest is to copy&paste the original code.
You may also check if calling removeAnnotation on MutableField and MethodDeclaration works

**Comment by lemmy** [comment]
I appreciate your time but this PR has gone beyond my time budget (I will simply create dummies for `@Pure` and `ToStringBuilder` in my client jar).  My fork of lsp4j contains my incomplete attempt in case someone familiar with xtext wants to take a shot.

Thanks again!

**Comment by jonahgraham** [comment]
Thanks for having a look. Please let us know if you have other ideas for improvement.

**Comment by jonahgraham** [comment]
I think the correct code that @lemmy started in 

https://github.com/lemmy/lsp4j/blob/1bf4a5b49539d046bd9f28d3dd06e1bfd18e1063/org.eclipse.lsp4j.generator/src/main/java/org/eclipse/lsp4j/generator/JsonRpcDataProcessor.xtend#L44-L54

should be

```java
		impl.getDeclaredMethods.forEach [ method | 
			val purified = method.findAnnotation(Pure.findTypeGlobally)
			if (purified !== null) {
				method.removeAnnotation(purified)
			}
		]
```

In addition, a new implementation of `toString` needs to be provided. `ToStringBuilder` does quite a bit, but it should be easy enough to add a `toString` that is sufficient but not the same content.

I leave the above in case someone wants to pick up the work.

**Comment by jonahgraham** [comment]
I think that @cdietrich changes in #529 will fix this.
