### ISSUE TITLE
NPE in org.eclipse.lsp4e.DocumentContentSynchronizer.documentSaved(long)

### ISSUE THREAD

**Issue by laeubi** [eclipse/lsp4j#495]
if the server does not provide the TextDocumentSyncKind a NPE is thrown.

java.lang.NullPointerException
	at org.eclipse.lsp4e.DocumentContentSynchronizer.documentSaved(DocumentContentSynchronizer.java:162)
	at org.eclipse.lsp4e.LanguageServerWrapper$1.dirtyStateChanged(LanguageServerWrapper.java:142)

**Comment by jonahgraham** [comment]
Hi @laeubi - the stack trace you have provided is in LSP4E (the Eclipse integration of LSP) not LSP4J. If this is still an issue can you [raise a bug there](https://bugs.eclipse.org/bugs/enter_bug.cgi?product=LSP4E)

FWIW I can see the null access at https://git.eclipse.org/r/plugins/gitiles/lsp4e/lsp4e/+/refs/heads/master//org.eclipse.lsp4e/src/org/eclipse/lsp4e/DocumentContentSynchronizer.java#162 if `textDocumentSync` is `null`.
