### ISSUE TITLE
Error when creating LanguageClient on Android

### ISSUE THREAD

**Issue by MozarellaMan** [eclipse/lsp4j#496]
I have a language server running remotely, connected to another device via WebSockets. I can receive and send messages to it - but I wanted to use this library to get access to all the LSP messages.

When I create a launcher that listens to messages from the WebSocket, I get this exception:
```java
Process: com.example.lsp_client, PID: 20779
    java.lang.NoClassDefFoundError: org.eclipse.lsp4j.jsonrpc.services.-$$Lambda$ServiceEndpoints$eKMG28mxVS2rcQINSfNNvWiJqVc
        at org.eclipse.lsp4j.jsonrpc.services.ServiceEndpoints.getSupportedMethods(ServiceEndpoints.java:90)
        at org.eclipse.lsp4j.jsonrpc.services.ServiceEndpoints.getSupportedMethods(ServiceEndpoints.java:82)
        at org.eclipse.lsp4j.jsonrpc.Launcher$Builder.getSupportedMethods(Launcher.java:404)
        at org.eclipse.lsp4j.jsonrpc.Launcher$Builder.createJsonHandler(Launcher.java:335)
        at org.eclipse.lsp4j.jsonrpc.Launcher$Builder.create(Launcher.java:319)
        at org.eclipse.lsp4j.launch.LSPLauncher.createClientLauncher(LSPLauncher.java:106)
```

I'm not sure what I'm doing wrong, this is what my class looks like
```kotlin
class LanguageServerSocket(
    private val address: String,
) : LanguageClient {

     private lateinit var socketSession: DefaultClientWebSocketSession
     private var inputStream: InputStream = "".byteInputStream()
     private var outputStream: OutputStream = ByteArrayOutputStream()


     suspend fun startSession() {
         val launcher = LSPLauncher.createClientLauncher(this, inputStream, outputStream) // exception here
         // ...socket code
     }

    // ...overrided `LanguageClient` methods
}
```

**Comment by MozarellaMan** [comment]
Update: After some investigation, it seems the issue is coming from it running on Android Version 21. Newer versions do not throw this exception. Will have to investigate further into why specifically Android 21 is giving warnings like:

```java
Rejecting re-init on previously-failed class java.lang.Class<org.eclipse.lsp4j.jsonrpc.MessageTracer>
```

**Comment by jonahgraham** [comment]
Hi @MozarellaMan Thanks for the report. It sounds like this issue is outside of LSP4J itself. Please reopen it if you are able to get new information that may impact LSP4J. 

Also, as you are a user of WebSockets, I couldn't tell if you are using the lsp4j websocket plug-in? If you are please note that in LSP4J 0.11.0 the websockets have been updated to Jakarta version. See #471 and #487 for details.

**Comment by MozarellaMan** [comment]
Thanks. My solution, or workaround, for anybody that might experience this issue, is to use the classes from lsp4j and then serialise/deserialise manually using the serialisation framework of your choice - as using methods like toString() or the built in adapters will crash the app.
