### ISSUE TITLE
An interface-based approach to modeling data

### ISSUE THREAD

**Issue by pisv** [eclipse/lsp4j#505]
The LSP specification often uses multiple inheritance when describing its data structures. For example:
```typescript
export interface CallHierarchyRegistrationOptions extends
	TextDocumentRegistrationOptions, CallHierarchyOptions,
	StaticRegistrationOptions {
}
```
This is in constrast to the approach currently used in LSP4J, where `CallHierarchyRegistrationOptions` is a class, so multiple inheritance cannot be used, resulting in the following mapping:
```java
public class CallHierarchyRegistrationOptions extends AbstractTextDocumentRegistrationAndWorkDoneProgressOptions
```
Currently, `CallHierarchyRegistrationOptions` does not extend `StaticRegistrationOptions` (#481).

This can be (kind of) fixed by adding the necessary properties (`id` in this case) directly to the `CallHierarchyRegistrationOptions` class, similarly to how this is done in `ColorProviderOptions`, `FoldingRangeProviderOptions`, etc.

However, such mapping would lose an important bit of information: that `CallHierarchyRegistrationOptions` really *is a* `StaticRegistrationOptions`.

It may seem not significant for this simple example, but the underlying gap in approaches does seem quite fundamental and significant.

Leaving compatibility issues aside, it seems that an approach based on using interfaces for modeling data structures (similar to the one used by EMF) would be "a better fit" for LSP4J.

Since LSP4J is still in the 0.x version range, I thought that perhaps it would not be too late to at least start a discussion about it.

**Comment by pisv** [comment]
To make it a bit more concrete, could not an Xtend declaration such as:
```java
@JsonRpcData
interface CallHierarchyRegistrationOptions extends
	TextDocumentRegistrationOptions, CallHierarchyOptions,
	StaticRegistrationOptions {
}
```
generate both a Java-interface:
```java
public interface CallHierarchyRegistrationOptions extends
	TextDocumentRegistrationOptions, CallHierarchyOptions,
	StaticRegistrationOptions {
}
```
and the corresponding implementation class:
```java
public class CallHierarchyRegistrationOptionsImpl implements
	CallHierarchyRegistrationOptions {
	// appropriate implementation: getters/setters, equals/hashCode, toString
	...
}
```
This assumes that the implementation class will be used only for instantiation. The data structure is always accessed/manipulated via the interface.

**Comment by jonahgraham** [comment]
@pisv This all sounds fairly reasonable. @spoenemann or @KamasamaK can either of you comment, this needs some input/response from some LSP committers/experts.

**Comment by spoenemann** [comment]
Yes that would bring the data structures a bit closer to how they're defined in the protocol spec. But even then it will not be possible to match 100% of the spec because it was written for TypeScript, and Java's type system is not flexible enough to cover all of that.

Such a step would likely force all adopters of LSP4J to rewrite lots of their code. Having a 0 in our major version is not enough justification for such a step. But we can leave this open and see how problematic the inheritance mismatch is in practice. If any adopter would like this to happen, please contribute to this conversation.

**Comment by pisv** [comment]
Thinking more about it based on @spoenemann comments, I've come to understand that this was probably not a good idea, especially when considering compatibility issues.

Actually, the need for more polymorphism can be satisfied by introducing interfaces on a case-by-case basis when/if necessary, either in advance (as in the case of `WorkDoneProgressParams`, for example) or post factum (e.g. a common interface for all `StaticRegistrationOptions` could be introduced without breaking the API -- the only problem would be to find a good name for such an interface).

I'm going to close this issue. Please reopen if you feel a need to revitalize the discussion. Thanks.

**Comment by nixel2007** [comment]
> the only problem would be to find a good name for such an interface)

you could use I-prefix approach - `IStaticRegistrationOptions`
