### ISSUE TITLE
Migrate LSP4J to new Eclipse Foundation Build Infra

### ISSUE THREAD

**Issue by jonahgraham** [eclipse/lsp4j#508]
The EF is in the process of moving LSP4J to new Build Infra. See https://bugs.eclipse.org/bugs/show_bug.cgi?id=570632

**Comment by jonahgraham** [comment]
The migration step 1 is done, we have a new build machine https://ci-staging.eclipse.org/lsp4j/ - before moving that to the https://ci.eclipse.org/lsp4j/ URL I need to make sure it looks like it works properly.

I have disabled builds on the old CI to prevent double builds. I have kicked off a master build and a PR build (for #507) so that I can make sure the new CI works.

**Comment by jonahgraham** [comment]
All builds on ci-staging failing at this point:
```
Task :org.eclipse.lsp4j.jsonrpc:test
```

**Comment by cdietrich** [comment]
i assume we need a specific node like
https://github.com/eclipse/Xpect/blob/0e5186a5fd96d4c82536fcff9acfa6ffada9fff8/Jenkinsfile#L13

**Comment by jonahgraham** [comment]
> i assume we need a specific node like
> https://github.com/eclipse/Xpect/blob/0e5186a5fd96d4c82536fcff9acfa6ffada9fff8/Jenkinsfile#L13

I hope not - I am using the standard as documented [here](https://wiki.eclipse.org/Jenkins#How_do_I_run_a_Java.2FMaven_build_on_the_new_infra.3F) which does not request a specific node. I may need to add specific tools though.

**Comment by cdietrich** [comment]
we had to change the xpect build to the centos recently

**Comment by jonahgraham** [comment]
I'll try it on there instead of `basic` to see if that "just works". If it does work, it means I will have to convert the PR job over to a Jenkinsfile as it implicitly runs on `basic` now as a freestyle job,

**Comment by jonahgraham** [comment]
I saw you are doing some tests - thank you. Please let me know what you discover. I have to sign off now until later today (or tomorrow).

**Comment by cdietrich** [comment]
maybe we also need some explicit memory settings for the build.
the old one used JAVA_TOOL_OPTIONS with Xmx2G
am not sure if this need to be configured on Jenkins side.
will try to set this from Jenkinsfile

**Comment by cdietrich** [comment]
wonder which Jenkins file is picked. the build does not pick my changes on my branch

**Comment by cdietrich** [comment]
does not seem to help. next would be java 8 vs java 11.

**Comment by cdietrich** [comment]
nope. none of that helps. guess someone needs to setup the container locally and connect via ssh to be able to run jstack.
am not sure if the guys at eclipse can help or have an idea

**Comment by cdietrich** [comment]
maybe the messages here make sense to you
https://ci-staging.eclipse.org/lsp4j/job/lsp4j-multi-build/job/cd_JustASecondTest/7/console

**Comment by cdietrich** [comment]
ok with ignored testVersatilityin both test it now fails at maven

**Comment by cdietrich** [comment]
ok when i run the 2 bad tests locally with `-XX:ActiveProcessorCount=1` then the test shows the same problem and also is stuck => can we configure requirements to the node to have 2 cpus?

**Comment by cdietrich** [comment]
@spoenemann @KamasamaK do you have an idea if the test could be reworked?

**Comment by jonahgraham** [comment]
> ok with ignored testVersatility in both test it now fails at maven

Thanks for all the investigation.

**Comment by jonahgraham** [comment]
> @spoenemann @KamasamaK do you have an idea if the test could be reworked?

I raised #510 for reworking the test.

**Comment by jonahgraham** [comment]
The reason that the CI test was hanging rather than failing is, AFAICT, because of a Future.get with no timeout. Most of the tests have timeouts on the gets.

**Comment by jonahgraham** [comment]
At the moment the migration works, except for pgp&deploy to OSSRH. For me this is enough to change ci-staging to ci URL, especially as we don't have a release imminent.

**Comment by jonahgraham** [comment]
> i assume we need a specific node like
> https://github.com/eclipse/Xpect/blob/0e5186a5fd96d4c82536fcff9acfa6ffada9fff8/Jenkinsfile#L13

In the end I did use centos because I didn't want to handle the change to gpg > 2.0 yet.

Anyway the deployment to OSSRH snapshots is working fine now.

**Comment by jonahgraham** [comment]
I have updated the release scripts, but until I have an actual release to run I won't debug them. 

JIRO migration complete. Back to Bugzilla https://bugs.eclipse.org/bugs/show_bug.cgi?id=570632 where I will request Fred/Webmaster complete the migration.
