### ISSUE TITLE
Quick Fix Code Action title not showing properly in VS Code

### ISSUE THREAD

**Issue by DiogoTheCoder** [eclipse/lsp4j#516]
I've tried to implement the `codeAction` method within `TextDocumentService`, and setting the title for the Code Action, however, it seems to appear incorrectly in VS Code, seems to try to print out the `Either` class instead of the title I have set

![image](https://user-images.githubusercontent.com/31896387/108631822-bc9e3000-7463-11eb-8a8f-47f683fe9d48.png)

```java
        CodeAction refactorCodeAction = new CodeAction();
        refactorCodeAction.setTitle(title);
        refactorCodeAction.setKind("quickfix");
        
        Either<Command, CodeAction> commandOrCodeAction = Either.forRight(refactorCodeAction);
        List<Either<Command, CodeAction>> eitherList = new ArrayList<>();
        eitherList.add(commandOrCodeAction);

        return CompletableFuture.supplyAsync(() -> eitherList);
```

**Comment by szarnekow** [comment]
What's the title you are setting? It surprises me that the text shown in the screenshot has Either.left assigned whereas the code you posted uses Either.forRight.

**Comment by DiogoTheCoder** [comment]
> What's the title you are setting? It surprises me that the text shown in the screenshot has Either.left assigned whereas the code you posted uses Either.forRight.

Ooops, forgot to include that:
```java
        String title = String.format("Refactor to %s", diagnostic.getCode());
```

**Comment by DiogoTheCoder** [comment]
Found the issue I think, `getCode` returns an `Either`

**Comment by DiogoTheCoder** [comment]
![image](https://user-images.githubusercontent.com/31896387/108632201-9c6f7080-7465-11eb-8dae-adc5a371df68.png)
![image](https://user-images.githubusercontent.com/31896387/108632207-a1342480-7465-11eb-983c-2aad4e60a2fe.png)

All working, thanks @szarnekow for point that out, made me realise what I was doing wrong. Cheers.
