### ISSUE TITLE
Documentation: Explain how to use protocol extensions

### ISSUE THREAD

**Issue by vladdu** [eclipse/lsp4j#54]
The LSP has already extensions that aren't (yet) mainstream, see for example https://github.com/sourcegraph/language-server-protocol. If I want to use those with lsp4j, do I need to edit ProtocolExtensions (or create my own) and build a private release? Do you have a plan for making it easier to handle in the future (like for example registering a jar containing just the extensions)?

**Comment by svenefftinge** [comment]
Could you point me to the mentioned extensions specifically? You just pointed to an LSP fork.

To add extension methods to the LSP using LSP4J you only need to create a service interface (see https://github.com/eclipse/lsp4j/blob/master/documentation/jsonrpc.md#service-objects) and register it.

It would probably make sense to have more documentation about it.

**Comment by vladdu** [comment]
Sorry. There are a couple of extra files alongside protocol.md, for example https://github.com/sourcegraph/language-server-protocol/blob/master/extension-files.md

**Comment by mickaelistria** [comment]
FYI, LSP4E supports reading custom message simply by wrapping the consumer during startup, and by interacting with the JSON-RPC layer.

**Comment by tsmaeder** [comment]
I have noticed that the methods in Launcher.java only take a single interface that the remote service implements. Would it make sense to pass multiple interfaces like so? 
```
LanguageServer s= Launcher.createLauncher(myLs, LanguageServer.class, new Class[] {MyExtension.class}, ...);
...
if (s instanceof MyExtension) {
  MyExtension ext= (MyExtension)s;
...
```

**Comment by mickaelistria** [comment]
@tsmaeder what is the issue with crating your LanguageServerWithExtension.class (which implements LanguageServer) and then casting `s` to such class?
The way extensions are designed in LSP4J at the moment are fully by inheritance. Allowing compostion would probably be nicer, but are there already use-cases that would make it worth being a top-priority development?

**Comment by tsmaeder** [comment]
@mickaelistria Let's say I have two interface ExtA and ExtB. 
as a LanguageServer host I would have to define:
* ExtAType extends LanguageServer, ExtA
* ExtBType extends LanguageServer, ExtB
* ExtABType extends LanguageServer, ExtA, ExtB
The combinations explode with more extension interfaces added.

**Comment by spoenemann** [comment]
I extended the documentation a bit. The issue with multiple interfaces is tracked in #143.
