### ISSUE TITLE
Question/documentation issue: How to send errors

### ISSUE THREAD

**Issue by fredg1** [eclipse/lsp4j#560]
I'm not finding any information, in the documentation, about how to send, as a Server, the errors mentioned in the LSP.

The LSP mentions several situations during which an "error" must be sent in a message, as a response to a request, as opposed to a "result".
For example, an `InitializeError` during an `Initialize`.

`InitializeError` is indeed a class in `org.eclipse.lsp4j.InitializeError`, however, it's just a class on its own (doesn't extend anything, doesn't implement anything), and isn't referenced anywhere in the code (besides in `InitializeErrorCode`, in a comment).

----

Doing some digging, I ended up finding that there is indeed a way to throw/make errors.

`org.eclipse.lsp4j.jsonrpc.RemoteEndpoint`
```java
	protected void handleRequest(RequestMessage requestMessage) {
		CompletableFuture<?> future;
		try {
			// Forward the request to the local endpoint
			future = localEndpoint.request(requestMessage.getMethod(), requestMessage.getParams());
		} catch (Throwable throwable) {
			// The local endpoint has failed handling the request - reply with an error response
			ResponseError errorObject = exceptionHandler.apply(throwable);
			if (errorObject == null) {
				errorObject = fallbackResponseError("Internal error. Exception handler provided no error object", throwable);
			}
			out.consume(createErrorResponseMessage(requestMessage, errorObject));
			if (throwable instanceof Error)
				throw (Error) throwable;
			else
				return;
		}

		[...]
	}
```

Where `exceptionHandler` is (at least by default):
```java
	public static final Function<Throwable, ResponseError> DEFAULT_EXCEPTION_HANDLER = (throwable) -> {
		if (throwable instanceof ResponseErrorException) {
			return ((ResponseErrorException) throwable).getResponseError();
		} else if ((throwable instanceof CompletionException || throwable instanceof InvocationTargetException)
				&& throwable.getCause() instanceof ResponseErrorException) {
			return ((ResponseErrorException) throwable.getCause()).getResponseError();
		} else {
			return fallbackResponseError("Internal error", throwable);
		}
	};
```

and `ResponseErrorException` simply being a wrapper for `ResponseError` that extends `RuntimeException`.

So at least now I know how to "send errors", even though it took some digging.

**Issue n°1, this really ought to be noted/documented somewhere**

---

However, this really didn't bring me any closer to `InitializeError`.

`ResponseError` has 3 fields:
`int code;`
`String message;`
`Object data;`

**Question n°1, is the `InitializeError` supposed to go in the `data` field??**
**Issue n°2, if so, maybe lsp4j's various `Error`s should all implement some common blank interface. Something like `ResponseErrorData`? It doesn't need to do anything, just pointing readers to documentation about where they are meant to go.**

**Comment by pisv** [comment]
> Question n°1, is the `InitializeError` supposed to go in the `data` field??

Yes, as per the [spec](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#initialize):

* **error.data**:

```typescript
interface InitializeError {
	/**
	 * Indicates whether the client execute the following retry logic:
	 * (1) show the message provided by the ResponseError to the user
	 * (2) user selects retry or cancel
	 * (3) if user selected retry the initialize method is sent again.
	 */
	retry: boolean;
}
```

**Comment by pisv** [comment]
> **Issue n°1, this really ought to be noted/documented somewhere**

I agree. When trying to answer this question for myself, I also discovered it in the same way, by inspecting the code.

Do you have a specific proposal? (PR is welcome)

**Comment by pisv** [comment]
> Issue n°2, if so, maybe lsp4j's various `Error`s should all implement some common blank interface. Something like `ResponseErrorData`? It doesn't need to do anything, just pointing readers to documentation about where they are meant to go.

Not sure about that. AFAICT, the spec points the reader already.

**Comment by fredg1** [comment]
> 
> 
> > **Issue n°1, this really ought to be noted/documented somewhere**
> 
> I agree. When trying to answer this question for myself, I also discovered it in the same way, by inspecting the code.
> 
> Do you have a specific proposal? (PR is welcome)

https://github.com/eclipse/lsp4j/pull/561#issue-683166413
