### ISSUE TITLE
Migrate default branch name from `master` to `main`

### ISSUE THREAD

**Issue by apupier** [eclipse/lsp4j#567]
It would be nice to migrate default branch name from `master` to `main`

see https://github.com/github/renaming#renaming-the-default-branch-from-master

**Comment by jonahgraham** [comment]
Thanks @apupier for raising this. The main branch name is an Eclipse Foundation (webmaster) controlled item, so I have raised https://bugs.eclipse.org/bugs/show_bug.cgi?id=576037 asking for the change. There will certainly need to be some cleanup done on LSP4J side once things are renamed.

**Comment by jonahgraham** [comment]
I think this is done now - please let me know, or open a PR if you see any remaining issues or leftover refences to LSP4J's former main branch.

**Comment by apupier** [comment]
That was increasingly faster than what I imagined. Thank you very much!

The [search](https://github.com/eclipse/lsp4j/search?q=master) for 'master' name give a [single reference](https://github.com/eclipse/lsp4j/blob/5605ca82252833777dbef82ca13a403dbfb9d906/org.eclipse.lsp4j.jsonrpc.debug/src/main/java/org/eclipse/lsp4j/jsonrpc/debug/adapters/DebugMessageTypeAdapter.java#L50) to another repository branch, so I think you handled everything.
Just for information, the [search](https://github.com/search?q=https%3A%2F%2Fgithub.com%2Feclipse%2Flsp4j%2Fblob%2Fmaster&type=code) in other repositories that were referencing the master branch gives a bunch of results but they are redirected anyway.

**Comment by nixel2007** [comment]
Looks like vscode-debugadapter-node maintainers renamed branch to main also https://github.com/Microsoft/vscode-debugadapter-node/blob/main/debugProtocol.json

so you can update this ref

**Comment by apupier** [comment]
@nixel2007 good point

created https://github.com/eclipse/lsp4j/pull/569
