### ISSUE TITLE
JSON-RPC Exceptions are not propagated correctly with the default exception handler

### ISSUE THREAD

**Issue by frankbenoit** [eclipse/lsp4j#576]
Hi,

I am new to the JSON-RPC, so I might miss a relevant point...

In the doc, it is written, how to publish request errors. However, when I did exactly this, on the remote side I receive an Exception with "internal error". My error code, message are not contained.

After investigation, I found that there is a mismatch between `RemoteEndpoint.DEFAULT_EXCEPTION_HANDLER` and `GenericEndpoint.recursiveFindRpcMethods (77)`.
In the later, an InvocationTargetException is wrapped into a RuntimeException. But the DEFAULT_EXCEPTION_HANDLER does not handle this case and falls back to the internal error.

As a workaround, I configure a custom exception handler:

````java
            this.launcher = new Launcher.Builder<T>()
                    ....
                    .setExceptionHandler(this::exceptionHandler)
                    .create();

    private ResponseError exceptionHandler(final Throwable t) {
        final var defaultExceptionHandler = RemoteEndpoint.DEFAULT_EXCEPTION_HANDLER;
        if ((t instanceof RuntimeException) && (t.getCause() instanceof InvocationTargetException)) {
            final var ite = (InvocationTargetException) t.getCause();
            if (ite.getTargetException() instanceof ResponseErrorException) {
                return defaultExceptionHandler.apply(ite.getTargetException());
            }
        }
        return defaultExceptionHandler.apply(t);
    }

````

I guess, this case should be inserted in the default behavior.

Frank

**Comment by pisv** [comment]
Hi Frank,

Thank you for reporting the issue.

It seems that the current documentation on response errors does not match the actual behavior.

I guess, the existing default behavior assumes that a request method completes exceptionally the returned future rather than throws the exception directly.

The current implementation of `GenericEndpont` seems to treat any exception thrown directly from the invoked method as 'unexpected', i.e. as a kind of 'internal error'.

I think the current behavior makes sense and it is a bug in the documentation that needs to be fixed. I'm going to provide a PR.

**Comment by ivy-cst** [comment]
Hi @pisv 

I think this is not very user friendly. The exception could also be not on top level, then this handling is needed in every json request method (@JsonRequest). As you can see here even the eclpse-gslp project does it not correctly:
https://github.com/eclipse-glsp/glsp-server/blob/2bb9e0b545f9f2657b26c8526f16a40ef5d2228e/plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/protocol/DefaultGLSPServer.java#L77

**Comment by jonahgraham** [comment]
@ivy-cst Can you pull this question out into a new [issue](https://github.com/eclipse-lsp4j/lsp4j/issues/new) or [discussion](https://github.com/eclipse-lsp4j/lsp4j/discussions/new/choose). It seems important but I don't want it to be lost in an old and closed issue.
