### ISSUE TITLE
Question: create client and connect to lsp server

### ISSUE THREAD

**Issue by nojaf** [eclipse/lsp4j#579]
Hello, 

This is more of a question on how to use the lsp4j instead of an actual bug report.
If there is an alternative way of asking questions, please let me know.

I wish to create a client that can connect to an LSP server that runs in a .NET process.
I've implemented this [server in F#](https://github.com/fsprojects/fantomas/blob/4.6/src/Fantomas.CoreGlobalTool/Daemon.fs#L41-L42) and I now want to connect to it and call these RPC functions.
So, I imagine I need to start the process, capture stdin and stdout and then somehow send JSON messages to this.

I'm not really sure what I'm after, although the `EndpointProxy` looks like what I'm looking for.
The code sample in the docs looks like this:
```
Endpoint endpoint = ...
MyService proxy = ServiceEndpoints.toProxy(endpoint, MyService.class);
```
but I'm not sure how to create an endpoint from the stdio streams.

Could someone provide me with a pointer on how to set this up?

Many thanks,

Florian

**Comment by cdietrich** [comment]
hi, did you check the helpers in 
https://github.com/eclipse/lsp4j/blob/5605ca82252833777dbef82ca13a403dbfb9d906/org.eclipse.lsp4j.jsonrpc/src/main/java/org/eclipse/lsp4j/jsonrpc/Launcher.java

**Comment by nojaf** [comment]
Hey, that looks indeed like what I'm after.
When seeing
```fsharp
		return new Builder<T>()
				.setLocalService(localService)
				.setRemoteInterface(remoteInterface)
```

What should my local service be exactly?
Same for remote interface?

My `T` currently is
```fsharp
interface FantomasDaemon {
    @JsonRequest("fantomas/version", useSegment = false)
    fun version() : String
}
```

which matches what my server is implementing.

**Comment by cdietrich** [comment]
see https://github.com/eclipse/lsp4j/blob/5605ca82252833777dbef82ca13a403dbfb9d906/org.eclipse.lsp4j/src/main/java/org/eclipse/lsp4j/launch/LSPLauncher.java#L100

**Comment by nojaf** [comment]
Figured it out, wonderful! Thanks for the pointers @cdietrich!

**Comment by nojaf** [comment]
@cdietrich small follow-up question, what if I'm done with my client and I want to garbage collect it?
Can I just kill the process and assume everything will be cleaned up from there on?

**Comment by cdietrich** [comment]
no idea. can you check the example i linked. you also may check https://github.com/eclipse/lsp4e
