### ISSUE TITLE
Getting lots of org.eclipse.lsp4j.jsonrpc.ResponseErrorException

### ISSUE THREAD

**Issue by Phillipus** [eclipse/lsp4j#580]
Sorry, no particular steps to reproduce. I'm working normally in Eclipse 4.22 but the error log shows lots of these exceptions:

```
java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Internal error.
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
	at org.eclipse.lsp4e.LanguageServerWrapper.lambda$13(LanguageServerWrapper.java:425)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Internal error.
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at org.eclipse.lsp4e.LanguageServerWrapper.lambda$4(LanguageServerWrapper.java:260)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

eclipse.buildId=4.22.0.I20211124-1800
java.version=11.0.13
org.eclipse.lsp4j_0.12.0.v20210402-1305
org.eclipse.lsp4j.jsonrpc_0.12.0.v20210402-1305
org.eclipse.lsp4e_0.13.8.202111241523

**Comment by cdietrich** [comment]
nothing else in error log of the remote site?

**Comment by Phillipus** [comment]
> nothing else in error log of the remote site? which file types are you working with?

No, nothing. I'll try and see what might trigger it. I think it may be related to editing an Eclipse `*.target` file.

**Comment by cdietrich** [comment]
then i guess this is a bug in the language server for target files. dont know if that one will write logs to disk somewhere

**Comment by cdietrich** [comment]
@laeubi @mickaelistria do you have an idea which ls is used for target files?

**Comment by mickaelistria** [comment]
.target are XML files, so it's lemminx.

**Comment by cdietrich** [comment]
@mickaelistria i see the same logged locally. is there a way to see server side log or enabling it?

**Comment by Phillipus** [comment]
> No, nothing. I'll try and see what might trigger it. I think it may be related to editing an Eclipse `*.target` file.

I was also editing a `pom.xml` file in the `m2e` editor. I need to try and trigger this again...

**Comment by mickaelistria** [comment]
> I don't think this is true in general as Target files seem to have some special folding / coloring and code-actions so maybe there is something in between.

The Language Server are enabled upon document creation; even if the editor is not the Generic Editor.

>  i see the same logged locally. is there a way to see server side log or enabling it?

You can get the messages log (between client and server) in Preferences > Language Servers > Logs. This allows to see the message, and -potentially- to indentify a message that LSP4J cannot process (this can happen when there are "breaking changes" in LSP4J so a message sent from a server using an older LSP4J cannot be read by client using newer one).
For server-side logs, there is no user switch, you'll have to take the code of Wild Web Developer and configure the necessary logging options in the piece of code that starts LemMinX process. However you can set the `org.eclipse.wildwebdeveloper.xml.internal.debugPort` system property (see https://github.com/eclipse/wildwebdeveloper/blob/master/org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/XMLLanguageServer.java#L75 ) and then attach a debugger to the LS directly.

As mentioned, I think it can be an incompatible message (LemMinX uses LSP4J 0.11.0) https://github.com/eclipse/lemminx/blob/0.18.1/pom.xml#L11

**Comment by cdietrich** [comment]
```
[t=1639055919081] LSP4E to org.eclipse.wildwebdeveloper.xml:
{"jsonrpc":"2.0","id":"7","method":"shutdown","params":null}
[t=1639055919081] org.eclipse.wildwebdeveloper.xml to LSP4E:
{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///Users/cdietrich/xtext-master/git/xtext-eclipse/org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target","diagnostics":[]}}
[t=1639055919089] org.eclipse.wildwebdeveloper.xml to LSP4E:
{"jsonrpc":"2.0","id":"7","error":{"code":-32603,"message":"Internal error.","data":"java.lang.RuntimeException: java.lang.reflect.InvocationTargetException\n\tat org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)\n\tat org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)\n\tat org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)\n\tat org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)\n\tat org.eclipse.lemminx.commons.ParentProcessWatcher.lambda$apply$0(ParentProcessWatcher.java:143)\n\tat org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)\n\tat org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)\n\tat org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:829)\nCaused by: java.lang.reflect.InvocationTargetException\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:566)\n\tat org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)\n\t... 12 more\nCaused by: java.lang.NullPointerException\n\tat org.eclipse.lemminx.XMLLanguageServer.shutdown(XMLLanguageServer.java:230)\n\t... 17 more\n"}}
[t=1639055919092] LSP4E to org.eclipse.wildwebdeveloper.xml:
Content-Length: 47
```

**Comment by pisv** [comment]
Looks like https://github.com/eclipse/lemminx/issues/1132.

**Comment by cdietrich** [comment]
yes

**Comment by cdietrich** [comment]
wonder if its intentional not to log everything on lsp4j side

**Comment by Phillipus** [comment]
Also getting lots of `java.util.concurrent.TimeoutException` and `java.net.URISyntaxException: Illegal character in path at index 33: file:/Users/username/dev/Eclipse 4.22.app/Contents/Eclipse/configuration/org.eclipse.osgi/414/0/.cp/cache/www.w3.org/2001/xml.xsd`

1. Open `*.target` file
2. Switch to "Source" tab
3. Start editing

Log attached
[errorlog.txt](https://github.com/eclipse/lsp4j/files/7685461/errorlog.txt)

**Comment by Phillipus** [comment]
> As far as I can see, lsp4j is not even present in stack traces in the error log. Could you please report these issues to the affected projects: WildWebDeveloper or LSP4E? Thanks!

Yes, I thought it was connected.

https://github.com/eclipse/wildwebdeveloper/issues/752

**Comment by pisv** [comment]
Closing as unrelated to lsp4j. The main issue described by the author is a known bug in lemminx.

> wonder if its intentional not to log everything on lsp4j side

I don't know the answer, but would a separate issue be a better place to discuss it?

**Comment by Phillipus** [comment]
> Closing as unrelated to lsp4j. The main issue described by the author is a known bug in lemminx.

OK. Can you tell me which plug-in in my Eclipse installation lemminx is used that causes this? I can see this plug-in - `org.eclipse.m2e.editor.lemminx_1.18.3.20211116-0804`

**Comment by pisv** [comment]
It looks like any plug-in that uses lemminx is potentially affected, until the error is fixed in a new version of lemminx. Unfortunately, I don't know exactly which Eclipse plug-ins use lemminx. Just looking at the name, it may be `org.eclipse.m2e.editor.lemminx`, but probably there are others too.

**Comment by Phillipus** [comment]
> It looks like any plug-in that uses lemminx is potentially affected, until the error is fixed in a new version of lemminx. Unfortunately, I don't know exactly which Eclipse plug-ins use lemminx. Just looking at the name, it may be `org.eclipse.m2e.editor.lemminx`, but probably there are others too.

Thanks for the info. :-)

**Comment by pisv** [comment]
Thanks for reporting the issue!
