### ISSUE TITLE
ReflectiveMessageValidator should skip validation of generic JsonObject

### ISSUE THREAD

**Issue by akosyakov** [eclipse/lsp4j#59]
Otherwise it fails since `JsonObject` has such methods as `getAsInt`.

**Comment by akosyakov** [comment]
This one actually is follow-up of https://github.com/eclipse/lsp4j/issues/60

**Comment by cdietrich** [comment]
will there be a 1.x fix for this as well?

**Comment by svenefftinge** [comment]
We need to cherry-pick on the 0.1.x maintenance branch. @cdietrich if you could provide a PR (including the version bump) that would be most welcome

**Comment by cdietrich** [comment]
What about the other changes?

**Comment by cdietrich** [comment]
pull request was merged. thus i think we can close this one.

**Comment by akosyakov** [comment]
@cdietrich thx!
