### ISSUE TITLE
java.lang.IllegalStateException: Missing header Content-Length in input "GET / HTTP/1.1

### ISSUE THREAD

**Issue by yoobi** [eclipse/lsp4j#592]
Hello, I'm getting the same error as robstryker in #210 , I've seen a couple of issue pinged around #6 of jsonrpc, #189 , #406 . I couldn't find a solution among all of this. I've somewhat understood that the package `org.eclipse.lsp4j.websocket` has been created to fix this. Do you have an example of an implementation ? So far using LSP v0.12.0, I got this:
kotlin
```
import com.application.impl.MyLanguageServer
import org.eclipse.lsp4j.services.LanguageClient
import org.eclipse.lsp4j.websocket.WebSocketLauncherBuilder
import java.lang.System.`in`
import java.lang.System.out
import java.net.ServerSocket
import java.util.concurrent.Future

val myLanguageServer = MyLanguageServer()
val launcher = WebSocketLauncherBuilder<LanguageClient>()
        .setSession() // Do not know what to put here
        .setLocalService(deepScriptLanguageServer)
        .setRemoteInterface(LanguageClient::class.java)
        .setInput(`in`)
        .setOutput(out)
        .create()
    val client = launcher.remoteProxy
    myLanguageServer.connect(client)
    val startListening: Future<*> = launcher.startListening()
    startListening.get()
```
But I don't know what to put in `setSession()` can someone please explain or provide an example? I'm trying to connect https://github.com/TypeFox/monaco-languageclient/blob/master/example/src/client.ts with my LSP4J implementation.

**Comment by cdietrich** [comment]
no idea why you want to use that directly. the websocket session should come from the websocket you open. you may search the web for usages of `org.eclipse.lsp4j.websocket.WebSocketEndpoint`

**Comment by yoobi** [comment]
Maybe I'm going in the wrong direction, before trying to use `websocketLauncherBuilder` I had this code
```kotlin
val serverSocket = AsynchronousServerSocketChannel.open().bind(InetSocketAddress("localhost", 3008))
val threadPool = Executors.newCachedThreadPool()
while (true) {
    val socketChannel = serverSocket.accept().get()
    threadPool.execute {
        val inputStream = Channels.newInputStream(socketChannel)
        val outputStream = Channels.newOutputStream(socketChannel)

        try {
            val server = DeepScriptLanguageServer()
            val launcher =
                Launcher.createLauncher(server, LanguageClient::class.java, inputStream, outputStream)
            server.connect(launcher.remoteProxy)
            launcher.startListening()
        } catch (e: Exception) {
            socketChannel.close()
            e.printStackTrace(System.err)
        }
    }
}
```

**Comment by cdietrich** [comment]
a websocket and a java io socket are not the same

**Comment by yoobi** [comment]
I have checked the difference and indeed they are not the same. Unfortunately I didn't find a solution for
```
Jan 18, 2022 3:21:34 PM org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer fireError
SEVERE: Missing header Content-Length in input "GET / HTTP/1.1
Host: localhost:3008
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
Upgrade: websocket
Origin: http://localhost:3000
Sec-WebSocket-Version: 13
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
Cookie: G_AUTHUSER_H=2; Idea-5ba51e2b=15f1e836-cde6-4d70-919b-35404eb7143d; token=expired; Webstorm-c4dfaef2=02e5aac2-7181-426d-9f55-ccaf23699eb8
Sec-WebSocket-Key: lBtIi5IVVgueE8zvHWuSCg==
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits

```

**Comment by cdietrich** [comment]
does your request sent it or not?

**Comment by yoobi** [comment]
Yes it is monaco-languageclient that send this request
<img width="831" alt="Screenshot 2022-01-18 at 15 55 03" src="https://user-images.githubusercontent.com/17434735/149961070-a714012a-da9f-431b-a01a-fea47da6064a.png">

**Comment by cdietrich** [comment]
no i mean the json content.

**Comment by yoobi** [comment]
I can't find the json content so maybe it didn't sent any ?

**Comment by cdietrich** [comment]
at the java.lang.IllegalStateException you should see what is sent by the client. you should also be able to see it in browser

**Comment by yoobi** [comment]
I start the server as such:
```kotlin
val languageServer = MyLanguageServer()
val serverSocket = ServerSocket(3008)
val socket = serverSocket.accept()
val launcher = LSPLauncher.createServerLauncher(languageServer, socket.getInputStream(), socket.getOutputStream())
val client = launcher.remoteProxy
deepScriptLanguageServer.connect(client)
val startListening: Future<*> = launcher.startListening()
startListening.get()
```

**Comment by cdietrich** [comment]
Java socket is not websocket.
java socket expect jsonrpc headers, websocket client does  not send them

**Comment by cdietrich** [comment]
did you check https://github.com/itemis/xtext-languageserver-example/blob/cd_websocket_2020_221/org.xtext.example.mydsl.websockets/src/org/xtext/example/mydsl/websockets/ServerLauncher.xtend

**Comment by yoobi** [comment]
You mean i need a real server like Jetty to run this ? 
Thanks again for your time with my issue.

**Comment by cdietrich** [comment]
you need some code that opens a websocket. i use jetty to also serve the html with monaco. 
https://github.com/search?q=org.eclipse.lsp4j.websocket.WebSocketEndpoint&type=code
