### ISSUE TITLE
A method to know whether server is still accessible

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lsp4j#6]
It would be pretty useful to have a method to know whether a connection with a server is still valid. Previously, asking for the state of the `Reader` on an endpoint allowed to know whether things were still working (and to detect cases such as server killed externally). Is there a way to get this with the new API? What about a method such as `Launcher.checkConnection()` to verify the state and be able to handle such issues.

**Comment by svenefftinge** [comment]
`Launcher.startListening` returns a future on which you can check (`isDone`) whether the message reading is still running. Also you can stop the listening by calling future.cancel(true).

**Comment by mickaelistria** [comment]
Thanks, that works!
