### ISSUE TITLE
Provide support of the latest protocol version

### ISSUE THREAD

**Issue by akosyakov** [eclipse/lsp4j#60]
https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md

**Comment by akosyakov** [comment]
Should we introduce extension interfaces or just change existing?

**Comment by cdietrich** [comment]
I thought version 0.1.x is for version 2 of LSP
And version 0.2.x is for version 3 of lsp

**Comment by akosyakov** [comment]
@cdietrich yes i think you are right, I've renamed the issue

**Comment by spoenemann** [comment]
See #15, #37, #41.

**Comment by akosyakov** [comment]
@spoenemann they look like dups of this one :)

**Comment by spoenemann** [comment]
They're just more specific :-P

**Comment by akosyakov** [comment]
PR for it: https://github.com/eclipse/lsp4j/pull/61

**Comment by akosyakov** [comment]
Resolved with https://github.com/eclipse/lsp4j/commit/3c309e0fe63056bb8146c104774c0ebb2112cb58.
