### ISSUE TITLE
SemanticTokensCapabilities cannot be deserialized due to lack of no-args constructor

### ISSUE THREAD

**Issue by pieterbos** [eclipse/lsp4j#601]
SemanticTokensCapabilities has no default constructor. So if a client sends these capabilities to a server implemented with lsp4j, it will result in an exception from GSON, making connecting to the language server from a recent vscode version fail.

This happened when connecting a vscode-languageclient version 7.0.0 to version 0.12.0 of lsp4j.

The fix could likely be to add a no-args constructor for SemanticTokensCapabilities.

A workaround to make this work for now is to register an InstanceCreator for SemanticTokensCapabilities to GSON. For example, replace `LSPLauncher.createServerLauncher(server, in, out) with:

```java
 Launcher<LanguageClient> launcher =  new LSPLauncher.Builder<LanguageClient>()
                .setLocalService(server)
                .setRemoteInterface(LanguageClient.class)
                .setInput(in)
                .setOutput(out)
                .configureGson(gsonBuilder -> {
                    gsonBuilder.registerTypeAdapter(
                            SemanticTokensCapabilities.class,
                            new InstanceCreator<SemanticTokensCapabilities>() {

                                @Override
                                public SemanticTokensCapabilities createInstance(Type type) {
                                    return new SemanticTokensCapabilities(null);
                                }
                            }
                    );
                })
                .create();
```

**Comment by cdietrich** [comment]
in other cases we have a default constructor despite the use of 
`@NonNull` on fields

@jonahgraham @KamasamaK  what is the general concept here?

**Comment by pieterbos** [comment]
For GSON you need some way of creating an object with many fields still null. This is because by default it always first creates an empty object using either the no-args constructor, or a registered instance creator, then it sets the fields after that. 
The only ways around it that I know are a custom instance creator that uses a (package) private constructor, to hide it from other classes, or a custom deserializer. This project does not seem to use either of those constructions. That suggests adding a no-argument constructor should be the way to go.

**Comment by KamasamaK** [comment]
No-args constructors added in #613. See if this fixes your issue.
