### ISSUE TITLE
Allow more versions of gson?

### ISSUE THREAD

**Issue by frankbenoit** [eclipse/lsp4j#611]
Currently only exactly gson 2.8.9 is allowed.
Would it be possible to allow a wider range? 
if the semantic versioning is valid, even [2.8.9,3.0) should be ok.
This would simplify the coexistence with other bundles that have dependencies to gson.

**Comment by jonahgraham** [comment]
Hi @frankbenoit, that sounds reasonable. Please can you provide a patch?

**Comment by cdietrich** [comment]
https://github.com/eclipse/lsp4j/blob/32ad52691b2fcaef7011ffc6461641f1164dc1f2/gradle/versions.gradle#L19
isnt this one used for manifest too?

**Comment by cdietrich** [comment]
and were there some breaking changes or do they do sem. versioning?

**Comment by frankbenoit** [comment]
The minimum supported Java version changes from 6 to 7.
https://github.com/google/gson/releases/tag/gson-parent-2.9.0

**Comment by nixel2007** [comment]
> and were there some breaking changes or do they do sem. versioning?

Google? semver and no breaking changes? Ha! They can break backward compatibility in patch release.

**Comment by cdietrich** [comment]
we will go with [2.9.0,2.10) for now
