### ISSUE TITLE
Compatibility period

### ISSUE THREAD

**Issue by KamasamaK** [eclipse/lsp4j#629]
How far back are we looking to support older protocol versions?

For example, `TextDocumentPositionParams.uri`, `DidChangeTextDocumentParams.uri`, and `DidOpenTextDocumentParams.text` are all not specified for LSP 3.x and we have them as `@Deprecated` to support 1.0 requests.

**Comment by nixel2007** [comment]
I think lsp4j should drop support of deprecated elements accordingly to LSP itself. So if it was dropped in 3.x and lsp4j targets to 3.x, lsp4j could drop it as well.
