### ISSUE TITLE
lsp4j 0.2.0 breaks vscode-java/jls

### ISSUE THREAD

**Issue by fbricon** [eclipse/lsp4j#64]
Because the 0.1.0-SNAPSHOT builds are no longer available (relates to discussion on #47) I moved JLS to consume 0.2.0-SNAPSHOT. While JLS builds fine, when vscode-java connects to it, the server fails to initialize with:

`java.lang.IllegalArgumentException: Only one of the Either types can be a json object or StringMap`

Activating verbose logging from vscode, this is what's exchanged between vscode and the server:

```
[Trace - 18:08:16] Sending request 'initialize - (0)'.
Params: {
    "processId": 23006,
    "rootPath": "/home/fbricon/Dev/souk/test",
    "capabilities": {},
    "trace": "verbose"
}


[Trace - 18:08:16] Received notification 'window/logMessage'.
Params: {
    "type": 3,
    "message": "2017-02-02 18:08:16 >> initialize"
}


[Info  - 18:08:16] 2017-02-02 18:08:16 >> initialize
[Trace - 18:08:16] Received response 'initialize - (0)' in 648ms. Request failed: java.lang.IllegalArgumentException: Only one of the Either types can be a json object or StringMap. (-32603).
[Error - 18:08:16] Server initialization failed.
  Message: java.lang.IllegalArgumentException: Only one of the Either types can be a json object or StringMap.
  Code: -32603 
[Trace - 18:08:16] Sending request 'shutdown - (1)'.
[Trace - 18:08:16] Received notification 'window/logMessage'.
Params: {
    "type": 3,
    "message": "2017-02-02 18:08:16 >> shutdown"
}


[Info  - 18:08:16] 2017-02-02 18:08:16 >> shutdown
[Trace - 18:08:16] Received response 'shutdown - (1)' in 2ms.
Result: {}


[Trace - 18:08:16] Sending notification 'exit'.
No parameters provided.

```

I am a bit clueless right now. 

This is our server implementation: https://github.com/gorkem/java-language-server/blob/master/org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/handlers/JDTLanguageServer.java

**Comment by fbricon** [comment]
The only place related to the Either type seems to be the TextDocumentSync on ServerCapabilities, which is actually set in https://github.com/gorkem/java-language-server/blob/master/org.jboss.tools.vscode.java/src/org/jboss/tools/vscode/java/internal/handlers/InitHandler.java#L62

**Comment by akosyakov** [comment]
@fbricon it was fixed yesterday, please wait for the nightly build or try with the local version

**Comment by fbricon** [comment]
Updated snapshot fixes the issue. Thanks @akosyakov
