### ISSUE TITLE
Notebook support

### ISSUE THREAD

**Issue by Cyrik** [eclipse/lsp4j#640]
I'd love to start using 3.17s Notebook features. Is there a plan to start supporting them?

**Comment by Cyrik** [comment]
I'm not a Java dev, but I can try to help if needed. We're using lsp4j under the hood in lsp4clj. I'd like to get notebook support into vscode/clava based on clojure-lsp.

**Comment by Cyrik** [comment]
Really quick work @KamasamaK, thank you! I will try to test it this week.

**Comment by KamasamaK** [comment]
@Cyrik Please let me know how the testing goes.

**Comment by Cyrik** [comment]
got sick so I didn't get to it yet. hopefully, I'll get to it in the next few days
