### ISSUE TITLE
import org.eclipse.lsp4j.CodeAction cannot be resolved

### ISSUE THREAD

**Issue by ghost** [eclipse/lsp4j#643]
Using v0.14.0 through jar is ok.
But when I used the source code from the latest released the following package and some classes are missing
``` java
import org.eclipse.lsp4j.CodeAction
```
isn't in the actual source code
[See this](https://github.com/eclipse/lsp4j/tree/main/org.eclipse.lsp4j/src/main/java/org/eclipse/lsp4j)

**Comment by KamasamaK** [comment]
You would normally use the JAR. This project uses Xtend which will generate the Java source code. For more information on how to do that, see our [Contribution Guide](https://github.com/eclipse/lsp4j/blob/main/CONTRIBUTING.md).
