### ISSUE TITLE
Can't execute commands

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lsp4j#67]
Using LSP4J 0.2.0-SNAPSHOT, I'm trying to execute a "quick fix" command from the CSS language server in VSCode.
For example
```css
a {
  col: blah;
}
```
shows me a warning on `col` and suggests 2 quick-fixes/code-actions/commands to fix it (rename `col` to `color` or `all`).

So I'm running the command with
```java
CompletableFuture<Object> response = this.ls.getWorkspaceService().executeCommand(
					new ExecuteCommandParams(this.command.getCommand(), this.command.getArguments()));
```

I can see the request is properly sent, but I get as response from LSP4J `Unhandled method workspace/executeCommand`.
I imagine I'm missing something. Do you have an example of how LSP4J is supposed to be used together with commands?

**Comment by akosyakov** [comment]
The css server does not support any server side commands, look at its capabilities: https://github.com/Microsoft/vscode/blob/3358b269680fc7b72bdab6ec2c8259f4d5969360/extensions/css/server/src/cssServerMain.ts#L48

It is responsibility of the client to handle css server commands, look at vscode: https://github.com/Microsoft/vscode/blob/3358b269680fc7b72bdab6ec2c8259f4d5969360/extensions/css/client/src/cssMain.ts#L73

**Comment by akosyakov** [comment]
In my understanding only when `executeCommandProvider` is registered then the server is able to execute commands and only commands which are listed in `ExecuteCommandOptions`. Otherwise it is responsibility of the client. @dbaeumer could you confirm please? Maybe it is worth to clarify for `workspace/executeCommand` request.

**Comment by akosyakov** [comment]
btw `Unhandled method workspace/executeCommand` it is a response for the css server, not from lsp4j.

**Comment by mickaelistria** [comment]
Ok, I was confused by the various versions of the protocol. Server commands are introduced in version 3 (which is not yet releaed). So in my case, it's indeed client-side commands.
Thanks @akosyakov
