### ISSUE TITLE
Switch from osgi to bnd makes projects that don't work in IDE from source

### ISSUE THREAD

**Issue by jonahgraham** [eclipse/lsp4j#678]
The steps in [CONTRIBUTING.md#eclipse](https://github.com/eclipse/lsp4j/blob/main/CONTRIBUTING.md#eclipse) no longer create proper OSGi plug-ins in Eclipse anymore since 6a75250. While the steps do create LSP4J projects that can be built and tested in Eclipse, they no longer have their `META-INF/MANIFEST.MF` updated with all the OSGi headers so that Eclipse PDE recognizes it as a proper bundle.

What this means is I can't import both LSP4J and LSP4E as source and do anything as LSP4E can't see LSP4J.

@cdietrich I missed this when testing the gradle upgrade. Any ideas before I debug this more?

**Comment by cdietrich** [comment]
No I don’t

**Comment by jonahgraham** [comment]
OK - I will have a look at some point - my urgency has gone off to resolve it quickly because the issue I was looking at wasn't actually LSP4J related after all, so I didn't need LSP4J source to resolve this issue:

- https://github.com/eclipse/lsp4e/issues/262

cc: @sebthom FYI for you since you are actively working in this area, you may trip over it too if you want source of LSP4J editable.
