### ISSUE TITLE
Either<T, List<T>>

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lsp4j#68]
I noticed the introduction of Either in 0.2.0. While it's quite helpful in cases of different types (string|markedstring for example) , I have the impression that cases of `Either<T, List<T>>` are not making the API better nor providing much help. I understand this maps properly the protocol specification, but both from client and server perspective it simply makes the code harder to write and maintain.
I would suggest to replace all `Either<T, ListT>>` by simple `List<T>` in the public API.

**Comment by spoenemann** [comment]
👍 our [CollectionTypeAdapterFactory](https://github.com/eclipse/lsp4j/blob/master/org.eclipse.lsp4j.jsonrpc/src/main/java/org/eclipse/lsp4j/jsonrpc/json/adapters/CollectionTypeAdapterFactory.java) should already be able to convert a single element into a list.
