### ISSUE TITLE
Question: How to declare additional request Types

### ISSUE THREAD

**Issue by gquerret** [eclipse/lsp4j#686]
My language server has several extension points, declared in an interface:
```java
@JsonSegment("proparse")
public interface ProparseExtension {
  @JsonRequest
  CompletableFuture<String> assembly(com.google.gson.JsonObject object);
  // Other methods here
}
```

No issue so far, request is handled correctly, VSCode sends this kind of request:
```json
{"jsonrpc":"2.0","id":13,"method":"proparse/assembly","params":{"project":"c:\\Users\\gquerret\\projects\\XYZ"}}
```

I would like to switch from `JsonObject` to `AssemblyRequestParams`, so I've created a new class:
```java
public class AssemblyRequestParams {
  private String project;
  public AssemblyRequestParams() { }
  public AssemblyRequestParams (String project) { this.project = project; }
  public String getProject() { return project; }
  public void setProject(String project) { this.project = project; }
}
```

and changed the method signature to:
```java
CompletableFuture<String> assembly(AssemblyRequestParams object);
```

I'm now getting this exception when LSP4J tries to read the message:
```
java.lang.IllegalArgumentException: argument type mismatch
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.TracingMessageConsumer.consume(TracingMessageConsumer.java:114)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

I assume LSP4J is not able to create the AssemblyRequestParams object from the parameter value, but can't find what has to be done. Any hint ?

Using LSP4J 0.19, Java 11

**Comment by nixel2007** [comment]
Hm... I've got the same setup and have no issues. 

https://github.com/1c-syntax/bsl-language-server/blob/develop/src/main/java/com/github/_1c_syntax/bsl/languageserver/jsonrpc/ProtocolExtension.java
https://github.com/1c-syntax/bsl-language-server/blob/develop/src/main/java/com/github/_1c_syntax/bsl/languageserver/jsonrpc/DiagnosticParams.java
https://github.com/1c-syntax/bsl-language-server/blob/develop/src/main/java/com/github/_1c_syntax/bsl/languageserver/BSLLanguageServer.java#L152-L160

**Comment by gquerret** [comment]
> Hm... I've got the same setup and have no issues.

Right, the setup seems identical in my case. Though there must be something different ...

**Comment by cdietrich** [comment]
can you provide a reproducing unit test?

**Comment by pisv** [comment]
@gquerret Can you set a breakpoint at https://github.com/eclipse/lsp4j/blob/b17a5f1c6f2f0a05901fcfc47f11f98d2b303f5f/org.eclipse.lsp4j.jsonrpc/src/main/java/org/eclipse/lsp4j/jsonrpc/services/GenericEndpoint.java#L65 and check the values for `arguments`, `method`, and `current`?

**Comment by gquerret** [comment]
@cdietrich I'll try to debug first, especially as it may come from my environment

@pisv Here are the details:

Message is: (using the trace functionality of LSP4J)
```
Params: {
  "project": "c:\\Users\\GillesQUERRET\\projets\\sonaroe-test-project"
}
```

Argument is an array with 1 JsonObject. Key = "project", value is a JsonPrimitive "c:\\Users\\GillesQUERRET\\projets\\sonaroe-test-project"

MethodInfo object looks like it found the right method. At least the methodInfo.method points to `public abstract java.util.concurrent.CompletableFuture eu.rssw.openedge.ls.proparse.ProparseExtension.rebuildProject(eu.rssw.openedge.ls.proparse.ProjectParams)`. The method name is different from the initial comment as I'm at the office this afternoon with a slightly different environment (but with the same error).

`current` object is the TextDocumentService that is instantiated in my main block.

I'll try to see how the `argument` object is created.

**Comment by gquerret** [comment]
I've compared the execution of a standard `hover` message and my custom message. At this [line number](https://github.com/eclipse/lsp4j/blob/b17a5f1c6f2f0a05901fcfc47f11f98d2b303f5f/org.eclipse.lsp4j.jsonrpc/src/main/java/org/eclipse/lsp4j/jsonrpc/json/MessageJsonHandler.java#L119), gson returns a `HoverParams` for the `hover` request, and a `JsonObject` for my custom request.

**Comment by pisv** [comment]
@gquerret Thanks for the detailed info. That's weird. Can you please try to debug this method then and see what's going on with message deserialization?
https://github.com/eclipse/lsp4j/blob/b17a5f1c6f2f0a05901fcfc47f11f98d2b303f5f/org.eclipse.lsp4j.jsonrpc/src/main/java/org/eclipse/lsp4j/jsonrpc/json/adapters/MessageTypeAdapter.java#L241

**Comment by gquerret** [comment]
Maybe something interesting from the debugger. At this line: https://github.com/eclipse/lsp4j/blob/b17a5f1c6f2f0a05901fcfc47f11f98d2b303f5f/org.eclipse.lsp4j.jsonrpc/src/main/java/org/eclipse/lsp4j/jsonrpc/json/MessageJsonHandler.java#L96

The supportedMethods map seems to contains a JsonRpcMethod for each request name. This is not the case for my `proparse/rebuildProject` request (or any other requests). However it contains the `proparse/message` name, which is a notification from the server to the client. Maybe the common `proparse/` prefix could be the problem. I'll try that.

**Comment by pisv** [comment]
For the record, if `MessageJsonHandler.getJsonRpcMethod` returns `null`, then `MessageTypeAdapter.getParameterTypes` returns `EMPTY_TYPE_ARRAY`, and `MessageTypeAdapter.parseParams(JsonReader in, String method)` returns `rawParams` here https://github.com/eclipse/lsp4j/blob/b17a5f1c6f2f0a05901fcfc47f11f98d2b303f5f/org.eclipse.lsp4j.jsonrpc/src/main/java/org/eclipse/lsp4j/jsonrpc/json/adapters/MessageTypeAdapter.java#L268

**Comment by gquerret** [comment]
By debugging the initialization of MessageJsonHandler, I've found the reason why the methods are not there. The implementation of ProparseExtension is done in the same class as TextDocumentService:
```java
public class ProparseTextDocumentService implements TextDocumentService, ProparseExtension {
```

The extra delegate segment is not detected in this case (by `org.eclipse.lsp4j.jsonrpc.services.AnnotationUtil#findDelegateSegments`). I had to add this method in my main language server class:
```java
public class ProparseLanguageServer implements LanguageServer, LanguageClientAware {
  @JsonDelegate
  public ProparseExtension getProparseExtension() {
    return (ProparseExtension) textService;
  }
}
```

**Comment by gquerret** [comment]
I'll close the issue. While the behavior is a bit disturbing, there's probably no need to change anything.

**Comment by pisv** [comment]
> While the behavior is a bit disturbing, there's probably no need to change anything.

I just wonder whether failing fast if `jsonRpcMethod` is `null` at https://github.com/eclipse/lsp4j/blob/b17a5f1c6f2f0a05901fcfc47f11f98d2b303f5f/org.eclipse.lsp4j.jsonrpc/src/main/java/org/eclipse/lsp4j/jsonrpc/json/adapters/MessageTypeAdapter.java#L356 would make things less mysterious next time...

**Comment by pisv** [comment]
I'd like to revisit this in #688, since there seems to be a certain asymmetry in how `@JsonDelegate` annotations are processed, which I think is the root of this issue.
