### ISSUE TITLE
Support for `workspace/applyEdit`

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lsp4j#69]
The quick-fix/code-actions commands typically sends some `workspace/applyEdit` notifications to client in order to perform the changes. LSP4J currently seems to miss a way to be notified of such message.
I have the impression that a `handleApplyEdit` operation would make sense as an addition to `LanguageClient` interface.

**Comment by akosyakov** [comment]
@mickaelistria overlooked it, thx!
