### ISSUE TITLE
Does it support LSP over TCP?

### ISSUE THREAD

**Issue by tn1997tn** [eclipse/lsp4j#696]
I don't know where to ask so I posted the question here. Please pardon me if I posted in the wrong place. Thank you.

**Comment by jonahgraham** [comment]
The transport part is not implemented by core LSP4J, the interface to LSP4J is input and output streams you can connect to whatever you like, including a socket stream.

In addition, in the past people have contributed additional modules to provide a websocket connect in https://github.com/eclipse/lsp4j/tree/main/org.eclipse.lsp4j.websocket (or [jakarta](https://github.com/eclipse/lsp4j/tree/main/org.eclipse.lsp4j.websocket.jakarta) version)

Please see [Launch and connect with a LanguageClient](https://github.com/eclipse/lsp4j/blob/main/documentation/README.md#launch-and-connect-with-a-languageclient)
