### ISSUE TITLE
Deprecated SymbolInformation and impact on documentSymbol

### ISSUE THREAD

**Issue by carueda** [eclipse/lsp4j#697]
Hello lsp4j team:

Related: https://github.com/eclipse/lsp4j/issues/252

A language server of mine does not use `SymbolInformation` directly at all, but it does use  `CompletableFuture<List<Either<SymbolInformation, DocumentSymbol>>> documentSymbol(DocumentSymbolParams)`. 

It would be great if there's a way to avoid the related compile warnings caused by [deprecated `SymbolInformation`](https://github.com/eclipse/lsp4j/blob/3397180c0e163b479ac0524113c76c2070d0b8b8/org.eclipse.lsp4j/src/main/java/org/eclipse/lsp4j/Protocol.xtend#L6680-L6687).

(In my projects I usually instruct my compiler to treat compile warnings as errors--but that's just a personal preference.)

In my particular (>23K LOC) project the only warnings are happening in my overridden `documentSymbol` method.

I'm aware of the backwards-compatibility considerations, etc., and don't have really definitive suggestions to address this, but can think of perhaps lsp4j also offering an alternative "documentSymbol2" (or some other name/suffix) method only involving `DocumentSymbol`:

```java
@JsonRequest
@ResponseJsonAdapter(DocumentSymbolResponseAdapter.class)
default CompletableFuture<List<DocumentSymbol>> documentSymbol2(DocumentSymbolParams params) {
   throw new UnsupportedOperationException();
}
```

But there are probably other possible ways.

Thanks for considering.

**Comment by jonahgraham** [comment]
What about removing the class level `@Deprecated`, but leave a comment and make the fields deprecated. That way any "real" use of the class would generate warnings, but simply using the `documentSymbol` method would not.

WDYT?

**Comment by carueda** [comment]
That would work, thanks!

**Comment by jonahgraham** [comment]
@carueda the change has been made. The 0.21.0-SNAPSHOT version should be automatically built and published in a few minutes.
