### ISSUE TITLE
Missing ClientParameters for completion

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lsp4j#70]
Here is the condition used on the ClientParameters by VSCode CSS server
```var snippetSupport = params.capabilities && params.capabilities.textDocument && params.capabilities.textDocument.completion && params.capabilities.textDocument.completion.completionItem && params.capabilities.textDocument.completion.completionItem.snippetSupport;```

LSP4J doesn't offer a way to set the `completion` attribute and its children on the ClientCapabilites object.

**Comment by mickaelistria** [comment]
BTW, the requirement on completion was introduced by VSCode 1.9.0, it was working well without it in 1.8.0

**Comment by akosyakov** [comment]
@mickaelistria fixed, thx for pointing out!

**Comment by mickaelistria** [comment]
Thanks a lot for the quick and good fix.
