### ISSUE TITLE
"Unsupported notification method"

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lsp4j#73]
I'm trying to setup a basic language server with LSP4J as a Maven project (using a "jar-with-dependencies" containing all classes in a single jar). I see
```
Feb 27, 2017 11:28:25 PM org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint request
WARNING: Unsupported notification method: textDocument/didOpen
Feb 27, 2017 11:28:25 PM org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint request
WARNING: Unsupported request method: textDocument/hover
```
And similar errors for everything related to the Language server.

I tried to find out a cause but couldn't conclude anything useful. What can be a cause for such issues?

**Comment by akosyakov** [comment]
Could you share a reproducible example? It would be interesting to debug `org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.recursiveFindRpcMethods` to see why methods are not collected.

**Comment by mickaelistria** [comment]
Here is a reproducer: http://www.screencast.com/t/ZAaAyayXpiqg . A `mvn test` should show test failures, and in case of failures, those error messages show up.

**Comment by akosyakov** [comment]
@mickaelistria `ToulouseLanguageServer.getTextDocumentService` returns `null`, but we need an object to traverse its members. It is a contract of `JsonDelegate` annotation that methods are annotated with it should not return `null`. The same for `getWorkspaceService`. I will update the java doc and add a warning on `null`.

**Comment by mickaelistria** [comment]
Ok, thanks for the hint. So those fields need to be set in constructor *before* initialize. Makes sense. A more explicit warning is indeed a nice addition.
