### ISSUE TITLE
How does the versioning correspond to the language server protocol spec version?

### ISSUE THREAD

**Issue by vazexqi** [eclipse/lsp4j#74]
I wanted to ask this on http://dev.eclipse.org/mhonarc/lists/lsp4j-dev/yearindex.php but it seems to not have any activity. Let me know if you prefer to move it there.

I see on https://mvnrepository.com/artifact/org.eclipse.lsp4j/org.eclipse.lsp4j that we have versions 0.1.0, 0.1.1, 0.1.2. How do these relate to the different versions of the spec (https://github.com/Microsoft/language-server-protocol/tree/master/versions)?

Apologies if this was mentioned somewhere, but I couldn't find it on the main README.md

**Comment by akosyakov** [comment]
lsp4j 0.1.0 is for LSP 2.x
lsp4j 0.1.1 - 0.1.2 is for LSP 3.x

Generally it was not planed to keep a mapping between lsp4j and lsp versions. Since LSP is backward compatible you can use the latest lsp4j always and only implement capabilities which are required in your case.

**Comment by vazexqi** [comment]
Thanks! Closing this issue now.
