### ISSUE TITLE
Release a milestone for 0.2.0 ?

### ISSUE THREAD

**Issue by smarter** [eclipse/lsp4j#76]
I'm working on a language server implementation that uses lsp4j 0.2.0-SNAPSHOT. I'd like to release it but depending on a snapshot is dangerous since it could break at any moment. It would be great if a milestone for 0.2.0 could be published so that language server implementations can depend on a stable artefact. I suspect this is also an issue for other language servers like the Ecllipse JDT one: https://github.com/eclipse/eclipse.jdt.ls/blob/master/org.eclipse.jdt.ls.core/pom.xml#L14

**Comment by akosyakov** [comment]
We will review the protocol and release lsp4j soon.

**Comment by spoenemann** [comment]
Done:
http://download.eclipse.org/lsp4j/updates/milestones/S201704261209/
https://oss.sonatype.org/service/local/repositories/releases/content/org/eclipse/lsp4j/org.eclipse.lsp4j/0.2.0.M7/

**Comment by smarter** [comment]
Thanks!
