### ISSUE TITLE
Is there a reason we bound the version of guava at [14.0, 19.0)?

### ISSUE THREAD

**Issue by vazexqi** [eclipse/lsp4j#80]
Looking at https://github.com/eclipse/lsp4j/blob/master/gradle/versions.gradle#L13 it seems that we bound the version of the Guava library.

We are using lsp4j internally and we have Guava 19. That non-inclusive bound is causing an unresolved issue from Eclipse (plug-in development).

Is it possible to include version 19 or is there a reason why version 19 was deliberately excluded?

**Comment by spoenemann** [comment]
We chose the same upper bound as used by `org.eclipse.xtext.xbase.lib`, which we depend on. With #84 I removed our direct dependency to Guava, but the same constraint remains through the indirect dependency. See eclipse/xtext-lib#30.

**Comment by guw** [comment]
Is the dependency on Guava a hard one or can it be optional, i.e. are only those pieces of `org.eclipse.xtext.xbase.lib` being used that do not require Guava?

**Comment by spoenemann** [comment]
Now LSP4J doesn't have any direct dependency to Guava anymore, but we need the dependency to xbase.lib as long as we want to generate the protocol classes (getters, setters, equals, hashCode). The dependency of xbase.lib to Guava is not optional.

**Comment by guw** [comment]
Is this a compile time or runtime dependency?

**Comment by spoenemann** [comment]
It's a runtime dependency. [xbase.lib](https://repo.maven.apache.org/maven2/org/eclipse/xtext/org.eclipse.xtext.xbase.lib/2.11.0/) is quite small (148 kB), so it shouldn't harm anyone.
