### ISSUE TITLE
Protocol: Consistent enumerations

### ISSUE THREAD

**Issue by spoenemann** [eclipse/lsp4j#85]
* ResponseErrorCode is implemented as an enum.
 * InitializeErrorCode is implemented as an interface with static final fields.

Can we make this consistent?

**Comment by akosyakov** [comment]
I would go for numbers then.

**Comment by spoenemann** [comment]
I would go for enums because we have implemented all other constants as enums (e.g. MessageType, CompletionItemKind etc.)

**Comment by spoenemann** [comment]
Another variant: ColoringStyle is implemented as a class with static final fields :-/

**Comment by jonahgraham** [comment]
This issues is being fixed on a case by case basis, see recent example in #523.
