### ISSUE TITLE
Issue with Rename

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lsp4j#96]
I'm trying to send a rename request to VSCode CSS Language Server
```js
{
  "jsonrpc": "2.0",
  "id": "2",
  "method": "textDocument/rename",
  "params": {
    "textDocument": {
      "uri": "file:///home/mistria/runtime-EclipseApplication/project/test.css"
    },
    "position": {
      "line": 0,
      "character": 0
    },
    "newName": "newName"
  }
}
```
and it seems like the response cannot be parsed by LSP4J
```
SEVERE: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 49 path $.result.changes[0]
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 49 path $.result.changes[0]
```

Unfortunately, I didn't manage yet to retrieve the response from the Language Server to compare it with the spec and with the LSP4J model. Maybe the issue is on LS side...

**Comment by spoenemann** [comment]
Could you get the response text somehow? You could try with a `FilterInputStream` that writes everything to `System.out`.

**Comment by mickaelistria** [comment]
Ok, I managed to put my hand on the response message:
```
{"jsonrpc":"2.0","id":"3","result":{"changes":[{"textDocument":{"version":1,"uri":"file:///home/mistria/runtime-EclipseApplication/project/test.css"},"edits":[{"range":{"start":{"line":0,"character":0},"end":{"line":0,"character":1}},"newText":"newName"}]}]}}
```
Seems like this LS is actually not conforming to the spec as it's sending versioned `textDocument` instead of `uri`s.

**Comment by mickaelistria** [comment]
I upgraded to last insiders version of VSCode and things are working as expected. Sorry for the noise and thanks for sharing the tip of proxying with FilterInputStream to easily get message.

**Comment by akosyakov** [comment]
@mickaelistria right, we should use `documentChanges´ property if they want to apply changes to the specific version of a document.
